#2689
craftercms/studio-ui pull request #1017
Opened 2018-12-17 19:28 UTC by vestrada

https://github.com/craftercms/craftercms/issues/2689 - [studio-ui] S3datasource enhancements #2689

2018-12-17 19:39 UTC, sumerjabri requested changes

2018-12-17 19:39 UTC, sumerjabri commented on static-assets/components/cstudio-forms/data-sources/video-S3-upload.js
> +        if(properties[i].name == "repoPath") {
Is this the right indentation?

2018-12-17 19:39 UTC, sumerjabri commented on static-assets/components/cstudio-forms/data-sources/video-S3-repo.js
> +        ];s
`;s`?

2018-12-17 19:39 UTC, sumerjabri commented on static-assets/components/cstudio-forms/data-sources/video-S3-upload.js
> +            { label: CMgs.format(langBundle, "repositoryPath"), name: "repoPath", type: "string" },
Is this the right indentation?

2018-12-19 04:54 UTC, vestrada commented on static-assets/components/cstudio-forms/data-sources/video-S3-repo.js
> +        ];s
Done

2018-12-19 14:49 UTC, sumerjabri approved these changes

2018-12-19 14:49 UTC, merged