#3120
craftercms/studio-ui pull request #1146
Opened 2019-04-29 18:47 UTC by vestrada

https://github.com/craftercms/craftercms/issues/3120 - [studio-ui] Preview Assets in Browse page for s3, cmis webdav is not working #3120

2019-04-29 19:46 UTC, rart reviewed
@vestrada please confirm: 

The FTLs contain markup for what looks to be a pop up (modal dialog). Are these related to the recent hide/destroy issue?

Since these dialogs are on the FTL destroying them might cause issues reopening them without refreshing the page. 

Do all of the hide/destroy fixes work when being opened various times without refreshing the page?

Why are these pop ups on the ftl but are basically blank?

2019-04-29 21:04 UTC, vestrada commented
No, It is not related. This is a custom pop up created for browse page, to preview a specific asset, I was just changing it because seems like there was a change when the search page was created. In this case there is just one dialog that will preview different assets. And it isn't yui dialog.

2019-04-30 06:42 UTC, rart requested changes

2019-04-30 06:42 UTC, rart commented on static-assets/components/cstudio-browse/browseWebDAV.js
> +            CStudioAuthoring.Utils.previewAssetDialog(path, type);
Will `CStudioAuthoring.Utils.previewAssetDialog` make use of the markup on the FTL to create the dialog? There's no FreeMarker output or unique differences between the different browse FTLs; it looks like duplicated HTML. 

Refactor for the pop up template to be on the JavaScript `previewAssetDialog` function and remove the HTML from the FTLs.

2019-04-30 16:12 UTC, vestrada commented
Done

2019-04-30 17:19 UTC, rart approved these changes

2019-04-30 17:21 UTC, merged