#2808
craftercms/studio-ui pull request #1161
Opened 2019-05-15 14:40 UTC by vestrada

https://github.com/craftercms/craftercms/issues/2808 - [studio-ui] child-content data source should allow user to decide if add or browse options are enabled #2808

2019-05-17 16:25 UTC, rart requested changes

2019-05-17 16:25 UTC, rart commented on static-assets/components/cstudio-forms/data-sources/child-content.js
> +        if(properties[i].name == "enableCreateNew"){
3ple equals

2019-05-17 16:25 UTC, rart commented on static-assets/components/cstudio-forms/data-sources/child-content.js
> +        if(properties[i].name == "enableBrowseExisting"){
===

2019-05-17 16:25 UTC, rart commented on static-assets/components/cstudio-forms/data-sources/child-content.js
> +            if (datasourceDef[x].id == this.id){
===

2019-05-17 16:25 UTC, rart commented on static-assets/components/cstudio-forms/data-sources/child-content.js
> +                if (_self.type == "") {
===

2019-05-21 21:46 UTC, vestrada commented on static-assets/components/cstudio-forms/data-sources/child-content.js
> +        if(properties[i].name == "enableCreateNew"){
Done

2019-05-21 21:46 UTC, vestrada commented on static-assets/components/cstudio-forms/data-sources/child-content.js
> +        if(properties[i].name == "enableBrowseExisting"){
Done

2019-05-21 21:46 UTC, vestrada commented on static-assets/components/cstudio-forms/data-sources/child-content.js
> +            if (datasourceDef[x].id == this.id){
Done

2019-05-21 21:46 UTC, vestrada commented on static-assets/components/cstudio-forms/data-sources/child-content.js
> +                if (_self.type == "") {
Done

2019-05-22 06:58 UTC, rart approved these changes

2019-05-22 13:45 UTC, merged