[studio-ui] Add highlight to Sidebar #2901
craftercms/studio-ui pull request #1171
Opened 2019-05-28 14:11 UTC by jvega190

https://github.com/craftercms/craftercms/issues/2901

2019-05-28 15:04 UTC, rart requested changes

2019-05-28 15:04 UTC, rart commented on static-assets/components/cstudio-common/common-api.js
> +                amplify.publish("SET_TREE_HIGHLIGHT", {
The event should rather be `SELECTED_CONTENT_SET`

2019-05-28 15:04 UTC, rart commented on static-assets/components/cstudio-common/common-api.js
> +            updateTreePath: function(treeName, cookieKey, path){
rename to `updateTreeCookiePath`

2019-05-28 15:04 UTC, rart commented on static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-assets-folder.js
> +        var WcmAssets = CStudioAuthoring.ContextualNav.WcmAssetsFolder,
Was this file meant to be modified? You were originally working with `wcm-root-folder.js`.

2019-05-28 15:04 UTC, rart commented on static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-root-folder.js
> +                        treeNode.html.onload = loadedNode();
Is this really what you wanted to do?

You're essentially setting `.onload = undefined` (setting the `.onload` to the return value of the `loadedNode` function which will always be undefined.

2019-05-28 15:04 UTC, rart commented on static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-root-folder.js
> -	                		Self.drawSubtree(treeData.item.children, args.node, args.pathToOpenTo, args.instance);
@sumerjabri this is another reason to call up GitHub support. This part wasn't really changed in content but it's getting modified marks and as a reviewer is confusing.

2019-05-28 15:04 UTC, rart commented on static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-root-folder.js
> +            amplify.subscribe("SET_TREE_HIGHLIGHT", function (message) {
Change event name as suggested on common-api comment.

2019-05-28 15:04 UTC, rart commented on static-assets/scripts/crafter.js
> +        "SET_TREE_HIGHLIGHT": "SET_TREE_HIGHLIGHT",
Change name as suggested

2019-05-29 14:59 UTC, jvega190 commented on static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-assets-folder.js
> +        var WcmAssets = CStudioAuthoring.ContextualNav.WcmAssetsFolder,
We need the highlight in both root and assets folders, for example, assets like images can be previewed in studio, while being previewed they should be highlighted

2019-05-30 10:26 UTC, rart approved these changes

2019-05-30 15:32 UTC, merged