#2959
craftercms/studio-ui pull request #1197
Opened 2019-06-14 16:20 UTC by jvega190

#2959 - Add support for aws uploading/transcoding video data source

Video player in react app

2019-06-14 17:13 UTC, sumerjabri requested changes

2019-06-14 17:13 UTC, sumerjabri commented on ui/app/src/models/AsyncVideoPlayerProps.tsx
> +import { PlayerOptions } from './PlayerOptions';
Add copyright notice.

2019-06-14 17:13 UTC, sumerjabri commented on ui/app/src/models/PlayerOptions.tsx
> +export interface PlayerOptions {
Add copyright notice.

2019-06-14 17:13 UTC, sumerjabri commented on ui/app/src/styles/async-video-player.scss
> +.async-video-player--unavailable-message, .async-video-player--loading {
Add copyright notice.

2019-06-14 17:20 UTC, rart requested changes

2019-06-14 17:20 UTC, rart commented on ui/app/src/components/App.tsx
> +const playerOptions = {
Get rid of everything AsyncVideoPlayer from this file. Leave it with just the CrafterCMSNextBridge and a hello world message inside.

2019-06-14 17:20 UTC, rart commented on ui/app/src/components/AsyncVideoPlayer.tsx
> +import { AsyncVideoPlayerProps } from '../models/AsyncVideoPlayerProps';
Keep component props interfaces in the component file.

2019-06-14 17:20 UTC, rart commented on ui/app/src/components/AsyncVideoPlayer.tsx
> +      const playerStyle = {
Let's leave the responsibility of these defaults on the VideoPlayer component

2019-06-14 17:20 UTC, rart commented on ui/app/src/components/AsyncVideoPlayer.tsx
> +      if ( playable ) {
Let's ditch this function, move this whole `if` block out to the present component's body replacing the whole return statement on the component body that calls renderPlayer

2019-06-14 17:20 UTC, rart commented on ui/app/src/components/AsyncVideoPlayer.tsx
> +import { PlayerOptions } from '../models/PlayerOptions';
`PlayerOptions` is nothing more than the `VideoPlayerProps` interface so let's move the interface to the VideoPlayer component file.

If this makes the models directory empty, add a `.gitkeep` file on to it as we will certainly need it down the road for models that are actually shared.

You also don't need to import it. Your IDE will infer it.

2019-06-14 17:20 UTC, rart commented on ui/app/src/components/VideoPlayer.tsx
> +import { PlayerOptions } from '../models/PlayerOptions';
As mentioned above, move interface back into this file

2019-06-14 17:20 UTC, rart commented on ui/app/src/components/VideoPlayer.tsx
> +const SourceTypes: { [key: string]: string } = {
Use Enum instead

2019-06-14 17:20 UTC, rart commented on ui/app/src/components/VideoPlayer.tsx
> +    const extensionRegex = /(?:\.([^.]+))?$/,
Cool regEx 😎

Kudos if you can actually explain it 😛

2019-06-14 17:20 UTC, rart commented on ui/app/src/components/VideoPlayer.tsx
> +class VideoPlayer extends React.Component {
Use/learn hooks, ditch the class :)

For `player` and `videoNode` -> useRef
For `videoJsOptions` -> useMemo

BTW, the optionality sign (`?`) on class properties doesn't make too much sense. That's for params and interfaces.

Ping me with questions.

2019-06-14 17:20 UTC, rart commented on ui/app/src/styles/async-video-player.scss
> +.async-video-player--unavailable-message, .async-video-player--loading {
Check for reuse of videojs's classes/markup instead of duplicating the styles. Code only your style extensions/additions.

2019-06-17 19:55 UTC, rart approved these changes

2019-06-17 20:55 UTC, merged