#3184
craftercms/studio-ui pull request #1233
Opened 2019-07-10 17:40 UTC by vestrada

https://github.com/craftercms/craftercms/issues/3184 - [studio-ui] UI locks the user out during form editing #3184

2019-07-10 17:41 UTC, rart commented on static-assets/components/cstudio-forms/forms-engine.js
> +                                            { text:CMgs.format(formsLangBundle, "no"),  handler:function(){this.destroy();}, isDefault:true } ]
Please format appropriately.

2019-07-11 19:16 UTC, rart requested changes
See comment

2019-07-17 23:48 UTC, vestrada commented
Done

2019-07-19 13:50 UTC, rart approved these changes

2019-07-19 13:50 UTC, merged