[studio-ui] Cleanse/escape the logs before displaying them in the site log viewer #2871
craftercms/studio-ui pull request #1309
Opened 2019-09-19 00:15 UTC by yureii00

[studio-ui] Cleanse/escape the logs before displaying them in the site log viewer #2871

2019-09-19 17:44 UTC, rart requested changes
use code or pre tags instead of blockquote for the exception

check rendering when exception is blank or null. in fact, check for all.

2019-09-20 06:20 UTC, rart approved these changes
Please submit the other locales (besides English)

2019-09-20 19:27 UTC, yureii00 commented
Updated.

2019-09-23 08:15 UTC, rart approved these changes

2019-09-23 14:13 UTC, merged