[studio-iu] Create Site Dialog Polish #3535
craftercms/studio-ui pull request #1344
Opened 2019-10-16 17:50 UTC by yureii00

https://github.com/craftercms/craftercms/issues/3532

2019-10-17 09:01 UTC, rart commented on ui/app/src/components/MobileStepper.tsx
> +  const capitalize = (s: string) => {
Function already exists in utils/string

2019-10-17 09:06 UTC, rart commented on ui/app/src/components/BlueprintCard.tsx
> +  },
Keep these translation keys scoped to this dialog.

2019-10-17 22:16 UTC, rart approved these changes

2019-10-18 13:40 UTC, sumerjabri requested changes
Add copyright to all files.

2019-10-18 13:40 UTC, sumerjabri commented on ui/app/src/components/ConfirmDialog.tsx
> +import Dialog from "@material-ui/core/Dialog";
Always add copyright.

2019-10-18 15:32 UTC, sumerjabri commented
@yureii00 I don't see the copyright added.

2019-10-18 15:33 UTC, sumerjabri commented on ui/app/src/components/ConfirmDialog.tsx
> +import Dialog from "@material-ui/core/Dialog";
Copyright is still missing.

2019-10-18 15:36 UTC, merged