#3537
craftercms/studio-ui pull request #1349
Opened 2019-10-17 21:54 UTC by vestrada

https://github.com/craftercms/craftercms/issues/3537 - [studio-ui] Item-Selector with File Upload and File Browse data sources fail on add action #3537

2019-10-17 22:06 UTC, rart requested changes

2019-10-17 22:06 UTC, rart commented on static-assets/components/cstudio-forms/data-sources/file-browse-repo.js
> +		console.log('here');
X

2019-10-17 22:06 UTC, rart commented on static-assets/components/cstudio-browse/browse.js
> +                var pathLabel = path ? path.replace(/\//g, ' / ') : "";
single quote

2019-10-17 22:23 UTC, vestrada commented on static-assets/components/cstudio-forms/data-sources/file-browse-repo.js
> +		console.log('here');
Done

2019-10-17 22:23 UTC, vestrada commented on static-assets/components/cstudio-browse/browse.js
> +                var pathLabel = path ? path.replace(/\//g, ' / ') : "";
Done

2019-10-18 07:19 UTC, rart approved these changes

2019-10-18 13:41 UTC, merged