Embedded dnd WIP
craftercms/studio-ui pull request #1393
Opened 2019-11-03 10:04 UTC by yureii00

### Ticket reference or full description of what's in the PR

2019-11-04 20:03 UTC, rart commented on static-assets/components/cstudio-common/resources/en/base.js
> +    componentsNotSupported: "The drop zone not support this type of Components",
Use new mechanism or include in all bundles.

2019-11-04 20:03 UTC, rart commented on static-assets/components/cstudio-forms/controls/node-selector.js
> +            if(this.form.datasourceMap[datasource] && this.form.datasourceMap[datasource].itemsAreContentReferences) {
This feels dangerous for preexisting situations covered

2019-11-04 20:03 UTC, rart commented on static-assets/components/cstudio-forms/forms-engine.js
> +              //cfe.engine.saveForm(false, message.draft, true);
Remove if unused

2019-11-04 20:03 UTC, rart commented on static-assets/components/cstudio-preview-tools/mods/component-panel.js
> +                        [{ text: "OK",  handler:function(){
reformat

2019-11-04 20:03 UTC, rart commented on static-assets/components/cstudio-preview-tools/mods/component-panel.js
> +                  return new Promise((resolve, reject) => {
cache as you go and resolve immediately if already in cache

2019-11-04 20:03 UTC, rart commented on static-assets/components/cstudio-preview-tools/mods/component-panel.js
> +                  var getContentItemsCb = {
put callback directly on the call

2019-11-04 20:03 UTC, rart commented on static-assets/scripts/dnd-controller.js
> +    var embeddedId = $dropZone.attr('data-studio-embedded-item-id');
what would this be? where would it come from?

2019-11-04 20:13 UTC, yureii00 commented on static-assets/components/cstudio-forms/controls/node-selector.js
> +            if(this.form.datasourceMap[datasource] && this.form.datasourceMap[datasource].itemsAreContentReferences) {
will removed, this is not needed

2019-11-04 20:14 UTC, yureii00 commented on static-assets/scripts/dnd-controller.js
> +    var embeddedId = $dropZone.attr('data-studio-embedded-item-id');
still pending to use, will check if need it to move elements

2019-11-05 18:01 UTC, rart requested changes
Revert App.tsx

2019-11-05 18:02 UTC, rart requested changes
Revert App.tsx

2019-11-05 18:12 UTC, rart approved these changes

2019-11-06 15:12 UTC, merged