[3608] Improve site-component datasource
craftercms/studio-ui pull request #1409
Opened 2019-11-06 20:44 UTC by yureii00

https://github.com/craftercms/craftercms/issues/3608

2019-11-06 22:29 UTC, rart approved these changes

2019-11-06 22:29 UTC, rart commented on ui/app/src/services/content.ts
> +export function getContent(site: string, path: string): Observable<string> {
This one should directly return the string, not the object with the content property

2019-11-06 22:29 UTC, rart commented on static-assets/components/cstudio-forms/data-sources/taxonomy-selector.js
> +                "unableLoad-dialog",
Show new error state dialog

2019-11-06 22:29 UTC, rart commented on static-assets/components/cstudio-forms/data-sources/taxonomy-selector.js
> +                return { key: item.querySelector('key').innerHTML, value: item.querySelector('value').innerHTML }
Format, semi colon

2019-11-06 22:29 UTC, rart commented on static-assets/components/cstudio-forms/data-sources/taxonomy-selector.js
> +    return "item";
reformat whole doc with single quotes

2019-11-06 22:29 UTC, rart commented on static-assets/components/cstudio-forms/data-sources/taxonomy-selector.js
> +      {label: CrafterCMSNext.i18n.intl.formatMessage(this.messages.taxonomySelectorMessages.required), name: "required", type: "boolean"}
format, semi

2019-11-06 22:29 UTC, rart requested changes
Approved pressed by mistake.

See individual comments.

2019-11-07 04:25 UTC, yureii00 commented on static-assets/components/cstudio-forms/data-sources/taxonomy-selector.js
> +                "unableLoad-dialog",
we need to check this tomorrow

2019-11-07 18:25 UTC, rart approved these changes

2019-11-07 18:49 UTC, merged