[#3642] [studio-ui] Add rexgex support to wcm-root-folder path excludes
craftercms/studio-ui pull request #1420
Opened 2019-11-08 20:58 UTC by vestrada

https://github.com/craftercms/craftercms/issues/3642 - [studio-ui] Add rexgex support to wcm-root-folder path excludes #3642

2019-11-08 21:34 UTC, rart requested changes

2019-11-08 21:34 UTC, rart commented on static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-root-folder.js
> +            if(config.params.excludes.exclude){
same if as above. did you mean `.regex`

2019-11-08 21:34 UTC, rart commented on static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-root-folder.js
> +        for (const excludeRegexCache in instance.excludeRegexCache) {
Use foreach

2019-11-08 21:34 UTC, rart commented on static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-root-folder.js
> +      isExclude: function (path, instance) {
Is this use only for regex type? Use better/more specific name

2019-11-11 20:43 UTC, vestrada commented on static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-root-folder.js
> +        for (const excludeRegexCache in instance.excludeRegexCache) {
This is for objects .

2019-11-11 21:14 UTC, rart approved these changes

2019-11-11 21:19 UTC, merged