[3672] Drag and Drop issues
craftercms/studio-ui pull request #1435
Opened 2019-11-13 19:22 UTC by yureii00

Adding notify to pointer-controller
fixing issue with browse for shared components.
https://github.com/craftercms/craftercms/issues/3672

2019-11-13 21:27 UTC, rart commented on static-assets/components/cstudio-forms/controls/node-selector.js
> +            if (order) {
Order = 0 will go to else too. Test specifically for what you need `!= null` (single equals) for example will catch what you seem to want here.

2019-11-13 21:33 UTC, rart commented on static-assets/components/cstudio-preview-tools/mods/component-panel.js
> +                          debugger;
x

2019-11-13 21:34 UTC, rart commented on static-assets/components/cstudio-preview-tools/mods/component-panel.js
> +                            var order = zones[selectorId].findIndex((item) => item == tracking);
===

2019-11-14 15:54 UTC, rart requested changes

2019-11-14 15:54 UTC, rart commented on static-assets/scripts/pointer-controller.js
> +      $window.keyup(function (e) {
Need to remove listener once it executes or that the operation is finished.

2019-11-14 15:54 UTC, rart commented on static-assets/scripts/pointer-controller.js
>          //return;
x

2019-11-14 16:59 UTC, rart approved these changes

2019-11-14 17:10 UTC, merged

2019-11-14 18:48 UTC, russdanner reviewed
Looks self contained and code looks good.