[3629] Reactify Targeting dialog
craftercms/studio-ui pull request #1448
Opened 2019-11-19 20:49 UTC by vestrada

https://github.com/craftercms/craftercms/issues/3629 - Reactify Targeting dialog

2019-11-20 16:27 UTC, rart requested changes

2019-11-20 16:27 UTC, rart commented on ui/app/src/modules/Preview/Tools/AudiencesPanel.tsx
> +  getConfigurationFile();
This is a big react no-no. Side effects should be done inside useEffect never in the body of the render function.

2019-11-20 16:27 UTC, rart commented on ui/app/src/modules/Preview/Tools/AudiencesPanel.tsx
> +    get(`/studio/api/1/services/api/1/site/get-configuration.json?site=editorial&path=/targeting/targeting-config.xml`)
See `services/configuration`

Create a `getAudienceTargetingConfig` method. This method will use `getDOM` to retrieve the config and then deserialize it on to a JS object with the appropriate semantics.

2019-11-21 03:07 UTC, rart commented on ui/app/src/services/configuration.ts
> +          const name = elem.getElementsByTagName('name')[0].innerHTML,
1. use querySelector
2 use utils/xml/getInnerHtml 
3 use utils/xml/getInnerHtmlNumber for numeric values

2019-11-21 03:09 UTC, rart commented on ui/app/src/services/configuration.ts
> +export function getAudiencesPanelConfig(site: string): Observable<AudiencesPanelConfig> {
Notice the "region" comments on 35 and 189. Create a region for your module within this file outside of the Preview config region.

2019-12-06 16:54 UTC, sumerjabri commented
@rart is this ready?

2019-12-24 06:18 UTC, rart commented
Content will be merged as part of https://github.com/craftercms/studio-ui/pull/1507

2019-12-24 06:18 UTC, closed without merging