[3626] Reactify Request Publish dialog
craftercms/studio-ui pull request #1449
Opened 2019-11-19 23:04 UTC by jvega190

https://github.com/craftercms/craftercms/issues/3626

2019-12-04 09:02 UTC, rart requested changes

2019-12-04 09:02 UTC, rart commented on ui/app/package.json
> +    "date-fns": "^2.0.0-beta.5",
Are both date-fns needed? date-fns and @date-io/date-fns

2019-12-04 09:02 UTC, rart commented on ui/app/src/modules/Content/Approve/ApproveDialog.tsx
> +    defaultMessage: 'Selected files will go live upon submission. Hard dependencies are automatically submitted with the' +
Space missing between the and main

2019-12-04 09:02 UTC, rart commented on ui/app/src/modules/Content/Dependencies/DependencySelection.tsx
> +                  {...onItemClicked ? {
This expression looks very suspicious. I don’t think you can spread null.

2019-12-04 09:02 UTC, rart commented on ui/app/src/modules/Content/Dependencies/DependencySelection.tsx
> +                  {...onItemClicked ? {
Put some parenthesis around the ternary expression to make this clearer.

2019-12-04 09:02 UTC, rart commented on ui/app/src/modules/Content/Dependencies/DependencySelection.tsx
> +                    {...onItemClicked ? {
😱 same as above

2019-12-04 09:02 UTC, rart commented on ui/app/src/modules/Content/Submit/DateTimePicker.tsx
> +    initialDate,
initailDate= moment()

the on the useState you can simply use initialDate. Same for other props like time zone and controls. Provide default / fallback values.

For example, with controls, you would no longer need the showall var, nor check if controls is null; just check if it includes the control you wish to check for.

2019-12-04 09:02 UTC, rart commented on ui/app/src/modules/Content/Submit/DateTimePicker.tsx
> +          { timezones &&
Format

2019-12-04 09:02 UTC, rart commented on ui/app/src/modules/Content/Submit/RequestPublishDialog.tsx
> +export const PublishDialogUI = withStyles(dialogStyles)((props: PublishDialogUIProps) => {
Move to separate file. (IntelliJ does this for you brilliantly: use Refactor > Move)

2019-12-04 09:02 UTC, rart commented on ui/app/src/services/content.ts
> -  return getContent(site, path).pipe(map(fromString));
Looks like you accepted yours on the merge. You overwrote recent changes. Rollback.

2019-12-04 09:02 UTC, rart commented on ui/app/src/services/publishing.ts
> +  return post(`/studio/api/1/services/api/1/workflow/submit-to-go-live.json?site=${siteId}&user=${user}`, data,
Format: all params on its own line

```
post(
  p1
  p2
  p3
)
```

2019-12-04 09:02 UTC, rart commented on ui/app/src/services/publishing.ts
> +  return post(`/studio/api/1/services/api/1/workflow/submit-to-go-live.json?site=${siteId}&user=${user}`, data,
same for similar instances on thispr

2019-12-06 20:15 UTC, jvega190 commented on ui/app/package.json
> +    "date-fns": "^2.0.0-beta.5",
I tested and it seems like `date-fns` is used by `@date-io/date-fns`.

2019-12-17 06:03 UTC, rart commented on static-assets/components/cstudio-common/common-api.js
> +
render function now returns the unmount function
```js
let unmount;
CrafterNext.render({
...
onClose: () => unmount()
...
}).then(done => unmount = done.unmount)
```

2019-12-20 14:45 UTC, rart requested changes

2019-12-20 14:45 UTC, rart commented on static-assets/components/cstudio-common/common-api.js
> +                // CSA.Operations._showDialogueView({
x

2019-12-20 14:45 UTC, rart commented on static-assets/components/cstudio-common/common-api.js
> +              CrafterCMSNext.render(container, 'RequestPublishDialog',
onclose

2019-12-20 14:45 UTC, rart commented on ui/app/package.json
> +    "@date-io/date-fns": "^1.3.11",
check for updates on all new deps

2019-12-20 14:45 UTC, rart commented on static-assets/components/cstudio-common/common-api.js
> +                  siteId: site,
site and user may now be retrieved from the react context store

2019-12-20 14:45 UTC, rart commented on ui/app/src/components/DateTimePicker.tsx
> +    onChangeDate && onChangeDate(updatedDateTime.format('YYYY-MM-DD'));
Date and time formats should be props. Maybe compute datetime format from the two.

Also:
`onChange?.(updatedDateTime...)`

2019-12-20 18:32 UTC, jvega190 commented on ui/app/package.json
> +    "@date-io/date-fns": "^1.3.11",
@rart none of the new deps have updates, but I saw some others outdated, should I update?

2019-12-24 16:02 UTC, rart approved these changes

2019-12-24 16:22 UTC, avasquez614 approved these changes

2019-12-24 16:22 UTC, merged