[3652] Add Display Format property to grouped checkbox
craftercms/studio-ui pull request #1472
Opened 2019-11-27 21:11 UTC by jvega190

https://github.com/craftercms/craftercms/issues/3652

2019-12-03 20:00 UTC, rart requested changes

2019-12-03 20:00 UTC, rart commented on static-assets/components/cstudio-forms/controls/checkbox-group.js
> +    this.i18n = CrafterCMSNext.i18n;
don’t use i18n libs as an own prop. create closures to use it locally.

2019-12-03 20:00 UTC, rart commented on static-assets/components/cstudio-forms/controls/checkbox-group.js
> +    // rowEl.setAttribute("for", _self.id + "-" + item.key);
x

2019-12-03 22:20 UTC, jvega190 commented on static-assets/components/cstudio-forms/controls/checkbox-group.js
> +    this.i18n = CrafterCMSNext.i18n;
I created a closure for the control to use the i18n lib locally

2019-12-06 17:02 UTC, sumerjabri commented
@rart is this ready now?

2019-12-09 09:49 UTC, rart approved these changes

2019-12-09 17:15 UTC, merged