[3732] Add new tool for encrypting text
craftercms/studio-ui pull request #1505
Opened 2019-12-20 21:51 UTC by jvega190

https://github.com/craftercms/craftercms/issues/3732

2019-12-20 21:54 UTC, rart requested changes

2019-12-20 21:54 UTC, rart commented on static-assets/components/cstudio-admin/base.js
> +    // TODO: To be removed once development is over
🤦🏻‍♂️

2019-12-20 21:58 UTC, jvega190 commented on static-assets/components/cstudio-admin/base.js
> +    // TODO: To be removed once development is over
done

2019-12-20 22:01 UTC, rart commented on static-assets/components/cstudio-admin/mods/admin-configurations.js
> +            parseValidateDocument(xml);
Don’t see where xml is declared inside this function ?

2019-12-20 22:03 UTC, rart commented on static-assets/components/cstudio-admin/mods/admin-configurations.js
> +            const { rxjs: { forkJoin, operators: { map } }, util: { ajax } } = CrafterCMSNext;
Did you test this syntax on firefox and safari at minimum? but preferably edge too.

2019-12-23 14:55 UTC, rart commented on static-assets/components/cstudio-admin/mods/admin-configurations.js
> +                  tag.innerHTML = text;
Per @jdrossl, the value needs to be wrapped in `${enc:VALUE}`.

Change to 
```js
tag.innerHTML = `\${enc:${text}}`;
```

2019-12-24 16:03 UTC, rart approved these changes

2019-12-24 16:41 UTC, avasquez614 approved these changes

2019-12-24 16:48 UTC, merged