[3767] Add new ICE panel 'Welcoming receptacles'
craftercms/studio-ui pull request #1532
Opened 2020-01-21 22:03 UTC by yureii00

https://github.com/craftercms/craftercms/issues/3767

2020-01-24 19:42 UTC, yureii00 commented on ui/guest/src/components/Guest.js
> +        case SHOW_RECEPTACLES_BY_CONTENT_TYPE: {
RevealContentTypeReceptacles

2020-01-24 19:43 UTC, yureii00 commented on ui/guest/src/components/Guest.js
> +          post({ type: SET_CONTENT_TYPE_RECEPTACLES, payload: receptacles });
ContentTypeReceptaclesResponse

2020-01-28 17:21 UTC, rart requested changes

2020-01-28 17:21 UTC, rart commented on ui/app/src/models/GlobalState.ts
> +    };
Not global state.

2020-01-28 17:21 UTC, rart commented on ui/app/src/models/PreviewToolIDs.ts
> +  'craftercms.ice.receptacles';
contentTypeReceptacles

2020-01-28 17:21 UTC, rart commented on ui/app/src/models/Receptacle.ts
> + */
You're copyright string is borked (has double spacing and asterisk). Update:

```
Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3 as published by
the Free Software Foundation.
 
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
 
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

2020-01-28 17:21 UTC, rart commented on ui/app/src/models/Receptacle.ts
> +export interface Receptacle {
=> ContentTypeReceptacle

Are you using this across files? If possible keep locally.

2020-01-28 17:21 UTC, rart commented on ui/app/src/modules/Preview/Tools/ReceptaclesPanel.tsx
> +import MoveToInboxIcon from '@material-ui/icons/MoveToInbox';
Remember to use Rounded icon set

2020-01-28 17:21 UTC, rart commented on ui/app/src/modules/Preview/Tools/ReceptaclesPanel.tsx
> +    defaultMessage: 'Receptacles'
This title needs to be dynamic with a format. It should read "{contentTypeName} Receptacles"

2020-01-28 17:21 UTC, rart commented on ui/app/src/modules/Preview/Tools/ReceptaclesPanel.tsx
> +          receptacles && receptacles.map((receptacle: Receptacle) =>
receptacles?.map

2020-01-28 17:21 UTC, rart commented on ui/app/src/state/actions/preview.ts
> +export function setContentTypeReceptacles(receptacles): StandardAction {
createAction<...>(...

2020-01-28 17:21 UTC, rart commented on ui/guest/src/components/Guest.js
> +  SHOW_RECEPTACLES_BY_CONTENT_TYPE,
Let's chat about these couple of messages. I think one should be something like CONTENT_TYPE_RECEPTACLES_REQUEST and the other not sure what it's for

2020-01-28 17:21 UTC, rart commented on ui/app/src/modules/Preview/Tools/ComponentsPanel.tsx
> +  const onListWelcomingReceptaclesClick = () => {
let's just name receptacles instead of welcoming receptacles all across

e.g. `onListReceptacles`

2020-01-28 17:21 UTC, rart commented on ui/app/src/modules/Preview/Tools/ComponentsPanel.tsx
> +        <MenuItem onClick={onListWelcomingReceptaclesClick}>List welcoming receptacles</MenuItem>
List receptacles

2020-01-28 19:56 UTC, yureii00 commented on ui/app/src/models/GlobalState.ts
> +    };
so? where?

2020-01-28 20:00 UTC, yureii00 commented on ui/app/src/modules/Preview/Tools/ReceptaclesPanel.tsx
> +          receptacles && receptacles.map((receptacle: Receptacle) =>
I think that should show a 'false' string

2020-01-30 16:25 UTC, rart approved these changes

2020-01-30 17:55 UTC, merged