[3845] [studio] Add to audit log when a publishing package is cancelled
craftercms/studio-ui pull request #1595
Opened 2020-02-26 20:44 UTC by dejan-brkic

added new audit action

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/3845

2020-02-26 22:28 UTC, sumerjabri commented on static-assets/components/cstudio-admin/mods/encrypt-tool.js
> + * Copyright (C) 2007-2019 Crafter Software Corporation. All Rights Reserved.
Fix copyright notice.

2020-02-27 11:38 UTC, rart requested changes
Translations are incorrect for "CANCEL_PUBLISHING_PACKAGE" key on all but English.

2020-02-27 16:03 UTC, sumerjabri approved these changes

2020-02-27 16:52 UTC, rart requested changes
`.../cstudio-admin/mods/encrypt-tool.js` - this is generated code, should not be checked in

2020-02-27 16:59 UTC, rart approved these changes

2020-02-27 17:03 UTC, merged