[3899] Remove all usage of `environment-config.xml`
craftercms/studio-ui pull request #1632
Opened 2020-03-16 23:02 UTC by jvega190

https://github.com/craftercms/craftercms/issues/3889

2020-03-17 11:56 UTC, rart requested changes
Don't remove the variables. These are used all over the place. Replace the values.
The task is not to remove `envConfig` uses but replace the references to `environment-config.xml`

2020-03-18 16:22 UTC, jvega190 commented
@rart variables were not removed, they were just being set some lines after, but it was not necessary so I moved them back to where they were (using location.origin)

2020-04-14 20:45 UTC, sumerjabri commented
@jvega190 this needs to go to 3.1.x as draft, and as non-draft for `develop`

2020-04-19 10:10 UTC, rart commented on templates/web/common/js-global-context.ftl
> -    "GUEST_BASE": "${env_config.previewServerUrl!"http://localhost:8080"}",
Rollback

2020-04-19 10:11 UTC, rart requested changes
- Freemarker files got misformatted
- For the overlayhook & js-global-context changes, let's discuss. Would want those things to come from the freemarker and/or do something more centralized.

2020-04-19 10:11 UTC, rart commented on ui/app/src/state/store.ts
> +
Rollback

2020-04-19 10:11 UTC, rart commented on templates/web/common/js-global-context.ftl
> -    "GUEST_BASE": "${env_config.previewServerUrl!"http://localhost:8080"}",
Rollback

2020-04-21 21:21 UTC, rart requested changes

2020-04-21 21:21 UTC, rart commented on templates/web/common/js-global-context.ftl
> +<#assign locationOrigin = '${request.scheme}://${request.serverName}:${request.serverPort?c}' />
What if there’s no port? (e.g. :80)

2020-04-21 21:21 UTC, rart commented on templates/web/common/page-fragments/studio-context.ftl
> +    authoringAppBaseUri: window.location.origin + '/studio',
Same work here

2020-04-21 21:21 UTC, rart commented on templates/web/overlayhook.ftl
> +<#assign locationOrigin = '${request.scheme}://${request.serverName}:${request.serverPort?c}' />
What if there’s no port? (e.g. :80)

2020-04-22 18:47 UTC, rart commented
Closed in favour of https://github.com/craftercms/studio-ui/pull/1724

2020-04-22 18:47 UTC, closed without merging