Merging develop
craftercms/studio-ui pull request #1634
Opened 2020-03-17 19:59 UTC by rart

2020-03-17 20:38 UTC, sumerjabri requested changes

2020-03-17 20:38 UTC, sumerjabri commented on ui/app/package.json
> +  "proxy": "http://authoring.sample.com:8080/",
Did you really want to do this?

2020-03-18 07:35 UTC, rart commented on ui/app/package.json
> +  "proxy": "http://authoring.sample.com:8080/",
Yes.

2020-03-18 14:08 UTC, sumerjabri approved these changes

2020-03-18 14:08 UTC, merged