Fix dependencies showing incorrect item
craftercms/studio-ui pull request #1637
Opened 2020-03-18 16:04 UTC by jvega190

[1938] Viewing dependencies of a new article page with an uploaded image displays dependencies of image instead of page

2020-03-18 16:56 UTC, rart requested changes
Please test generously.

2020-03-18 16:56 UTC, rart commented on static-assets/components/cstudio-view-controllers/dependencies.js
>      });
Off the handler, not the event.

2020-03-19 10:37 UTC, rart requested changes
If the dialog is not closed via escape key, the listener still remains active. 
- Listen for the end event of the dialog to also destroy the event listener
- Make sure you remove the listener **before** you call on me.end on the escape listener
- Test

2020-03-19 16:40 UTC, jvega190 commented
@rart I made a little refactor, I added a wrong commit message, but the commit is for the last comment you added

2020-03-19 18:00 UTC, rart approved these changes

2020-03-19 22:27 UTC, merged