[3890i] Update the Bulk Upload function to support larger amounts of files and be more precise
craftercms/studio-ui pull request #1638
Opened 2020-03-18 23:53 UTC by yureii00

https://github.com/craftercms/craftercms/issues/3890

2020-03-19 17:53 UTC, rart requested changes

2020-03-19 17:53 UTC, rart commented on ui/app/src/components/BulkUpload.tsx
> +    path = '/static-assets/test',
Fix

2020-03-19 17:53 UTC, rart commented on ui/app/src/components/BulkUpload.tsx
> +    site = 'editorial',
Fix

2020-03-19 17:53 UTC, rart commented on ui/app/src/components/BulkUpload.tsx
> +    limit = 2
Rename to maxSimultaneousUploads, default to 1

2020-03-19 17:53 UTC, rart commented on ui/app/src/components/BulkUpload.tsx
> +  };
Think it makes sense to have a single prop for this: `onStatusChange`

2020-03-19 17:53 UTC, rart commented on ui/app/src/components/BulkUpload.tsx
> +}
- Format nicely
- Rename to ArrowPointingDown

2020-03-19 17:53 UTC, rart commented on ui/app/src/components/BulkUpload.tsx
> +        .setMeta({ site });
Format

2020-03-19 17:53 UTC, rart commented on ui/app/src/components/DialogTitle.tsx
> +/*
All the annotations done on the Site Translation / Pages widgets PR for this component apply here.

2020-03-19 17:53 UTC, rart commented on ui/app/src/utils/string.ts
> +export function bytesToSize(bytes: number, seperator: string = '') {
```ts
export function bytesToSize(bytes: string, separator: string = '');
export function bytesToSize(bytes: number, separator: string = '');
export function bytesToSize(bytes: number | string, separator: string = '') {
  ...
```
(notice typo in the word separator)

Add to default exports

2020-03-19 18:22 UTC, yureii00 commented on ui/app/src/components/BulkUpload.tsx
> +}
removed

2020-03-23 18:30 UTC, yureii00 commented on ui/app/src/components/DialogTitle.tsx
> +export default function DialogTitle(props: DialogTitleProps) {
Change the name to DialogHeader

2020-03-23 18:34 UTC, yureii00 commented on ui/app/src/components/DialogTitle.tsx
> +        <Typography variant="h6">{title}</Typography>
add props (with default values) for titleTypographyProps, subtitleTypographyProps. Put variants in there

2020-03-24 18:52 UTC, rart approved these changes

2020-03-24 18:55 UTC, rart approved these changes

2020-03-24 18:57 UTC, merged