Init DeleteDialog and usage of DependencySelectionDelete
craftercms/studio-ui pull request #1639
Opened 2020-03-19 22:40 UTC by jvega190

https://github.com/craftercms/craftercms/issues/3628

2020-03-20 10:06 UTC, rart commented
Fix PR title

2020-03-20 10:08 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +      {/* TODO: this dialog title is the same as the one used in PublishDialog and can be reused, move to a global component? */}
Good catch. This is already done in one of the active draft PRs. Once those are merged, we should replace this one with — as well as previously completed dialogs.

2020-03-20 10:12 UTC, rart requested changes

2020-03-20 10:12 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialog.tsx
> +}
Keep an eye on how this component evolves. If it just literally wraps the UI without any container logic, then it's not worth keeping. I do anticipate this one having the container logic (e.g. pulling stuff from redux).

DeleteDialog & DeleteDialogUI can both be in this file.

2020-03-20 10:12 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +              console.log('result', result)
x

2020-03-20 10:12 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +            siteId={'editorial'}
hardcoded

2020-03-24 21:07 UTC, rart requested changes

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialog.tsx
> +  const [apiState, setApiState] = useState({
use spread state and remove spreading in all set state calls

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialog.tsx
> +          setApiState({ ...apiState, error: true, errorResponse: (response.response) ? response.response : response });
no spread

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialog.tsx
> +    setApiState({ ...apiState, error: false, global: false });
no spread

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialog.tsx
> +    setApiState({ ...apiState, submitting: true });
no spread

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialog.tsx
> +        setApiState({ ...apiState, error: false, submitting: false });
spread

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialog.tsx
> +  const user = useSelector<GlobalState, GlobalState['user']>(state => state.user);
isn’t there a custom hook for this?

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +import { TextField } from '@material-ui/core';
import from its own file

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +                <Button variant="contained" autoFocus onClick={handleSubmit} color="primary"
Format

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +                          defaultMessage={`Delete`}
format

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +                    defaultMessage={`Cancel`}
format

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +                  siteId={'editorial'}
hardcoded

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +      maxWidth={'sm'}
format

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +      fullWidth={true}
simplify bool syntax

2020-03-24 21:07 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +                    id="outlined-multiline-static"
use appropriate id and camelcased

2020-03-24 21:07 UTC, rart commented on ui/app/src/services/content.ts
> +export function deleteItems(siteId: string, user: string, submissionComment: string, data): Observable<any> {
data missing type

2020-03-24 21:07 UTC, rart commented on ui/app/src/services/content.ts
> +  return post(
use post json util

2020-03-24 21:29 UTC, rart commented
Pull/merge conflict

2020-03-25 13:00 UTC, rart commented
DialogTitle component is now merged

2020-03-25 15:52 UTC, jvega190 commented on ui/app/src/modules/Content/Delete/DeleteDialog.tsx
> +  const user = useSelector<GlobalState, GlobalState['user']>(state => state.user);
@rart there wasn't. I Created one, please let me know if it's ok

2020-03-25 15:57 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +      {/* TODO: this dialog title is the same as the one used in PublishDialog and can be reused, move to a global component? */}
Dialog title is now merged.

2020-04-01 11:44 UTC, rart commented on ui/app/src/components/ComponentMenu.tsx
> +          setDeleteDialog({ items: [item] });
Wrap API response in service

2020-04-01 11:46 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +      maxWidth={'sm'}
👆🏻

2020-04-01 11:48 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +      aria-labelledby="simple-dialog-title"
Where is this ID?
Use a semantic/specific title

2020-04-01 11:50 UTC, rart commented on ui/app/src/services/content.ts
> +      if (response.response.success) {
Abstract error response in API 2 error response

2020-04-04 18:25 UTC, rart requested changes
Co-locate DeleteDialog & DeleteDialogUI on same file

2020-04-04 18:25 UTC, rart commented on ui/app/src/components/ComponentMenu.tsx
>        }
Dialog manager

2020-04-04 18:25 UTC, rart commented on ui/app/src/services/content.ts
> +      if (response.response.success) {
When would !response.success? What then?

2020-04-06 17:19 UTC, rart commented on ui/app/src/components/ComponentMenu.tsx
> +  });
Spread state with a single prop doesn't make too much sense.

2020-04-06 17:20 UTC, rart commented on ui/app/src/components/ComponentMenu.tsx
>        }
Dispatch to dialog manager

2020-04-06 17:22 UTC, rart commented on ui/app/src/models/GlobalState.ts
> +    deleteDialog: DeleteDialogStateProps;
Follow the pattern: remove the word dialog

2020-04-06 17:29 UTC, rart commented on ui/app/src/services/dependencies.ts
> +    })
pluck

2020-04-06 17:30 UTC, rart commented on ui/app/src/state/reducers/dialogs/index.ts
> +  deleteDialog
Follow the pattern: remove the word dialog

2020-04-06 17:33 UTC, rart commented on ui/app/src/modules/Content/Dependencies/DependencySelection.tsx
> +                    id="deleteDialog.uploadingDepenedents"
uploading?
Depenedents?

Typos

2020-04-06 17:34 UTC, rart commented on ui/app/src/modules/Content/Dependencies/DependencySelection.tsx
> +                defaultMessage={` Will have broken references`}
Is the space at the beginning intentional? There be a better way of achieving it even if it is.
Please change all these curly brackets with side ticks to regular double quotes

2020-04-06 17:36 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialogUI.tsx
> +function DeleteDialogContentUI(props: DeleteDialogContentUIProps) {
Move DeleteDialogUI to DeleteDialog.tsx (i.e. remove this file and move all to the main file).

2020-04-06 17:37 UTC, rart commented on ui/app/src/modules/Content/Delete/DeleteDialog.tsx
> +      errorSelector: () => apiState.error
Do not use closures. Use the supplied arguments of each checker.

2020-04-06 17:37 UTC, rart requested changes
Please fix conflicts

2020-04-07 09:21 UTC, rart requested changes

2020-04-07 09:21 UTC, rart commented on ui/app/src/state/reducers/dialogs/index.ts
> +import deleteDialog from './delete';
Follow the pattern: remove “dialog”

2020-04-07 09:21 UTC, rart commented on ui/app/src/services/content.ts
> +export function getItem(site: string, path: string): Observable<any> {
Checkout the **file** from your other PR

2020-04-08 09:00 UTC, rart requested changes
Consolidate other PR updates to shared files

2020-04-08 09:00 UTC, rart commented on ui/app/src/state/reducers/dialogs/delete.ts
> +      onSuccess: closeDeleteDialog(),
onSuccess not required to provide default

2020-04-13 16:38 UTC, jvega190 commented
Checked & ready

2020-04-15 10:41 UTC, rart approved these changes

2020-04-15 17:49 UTC, merged