[3963] [studio-ui] Refactor PublishDialog to use "Suspencified" and add to GlobalDialogManager
craftercms/studio-ui pull request #1682
Opened 2020-04-07 23:09 UTC by jvega190

https://github.com/craftercms/craftercms/issues/3963

2020-04-13 16:37 UTC, jvega190 commented
Checked & ready

2020-04-14 19:33 UTC, rart requested changes
PublishDialog/PublishDialogUI are still on separate files.

2020-04-14 19:36 UTC, rart requested changes
Conflicts

2020-04-15 10:14 UTC, rart approved these changes

2020-04-15 15:38 UTC, merged