[4059] Fix form engine close exception
craftercms/studio-ui pull request #1767
Opened 2020-05-11 22:13 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4059

2020-05-11 22:13 UTC, jvega190 commented
Pending unlock on unload event, need to discuss

2020-05-13 07:07 UTC, rart requested changes
- See comments.
- Let's fix 3.1.x too please.

2020-05-13 07:07 UTC, rart commented on ui/app/src/services/content.ts
> +  unlock
This is outdated. Pull.

2020-05-13 07:07 UTC, rart commented on static-assets/components/cstudio-forms/forms-engine.js
> +                  YAHOO.util.Event.removeListener(window, 'unload', unloadFn, me);
Unload should be removed once the unlock has succeeded.

2020-05-13 07:07 UTC, rart commented on static-assets/components/cstudio-forms/forms-engine.js
> +              YAHOO.util.Event.removeListener(window, 'unload', unloadFn, me);
Unload should be removed once the unlock has succeeded.

2020-05-13 19:11 UTC, rart commented on static-assets/components/cstudio-forms/forms-engine.js
> +            console.log('UNLOAD');
x

2020-05-13 19:16 UTC, rart approved these changes

2020-05-13 19:30 UTC, merged