[4006] Reactify "Reject" dialog
craftercms/studio-ui pull request #1773
Opened 2020-05-13 23:06 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4006

2020-05-20 17:00 UTC, rart requested changes
Please address comments.

2020-05-20 17:00 UTC, rart commented on ui/app/src/models/Item.ts
> +  deleted: boolean;
These props aren't in any of the [new items](https://app.swaggerhub.com/apis/craftercms/studio/3.1.7.1#/DetailedItem), are they? Remove unless they are.

2020-05-20 17:00 UTC, rart commented on ui/app/src/services/configuration.ts
> +   )
Semi missing. Do you have the reformat, organize and clean up code checks on?

Add Api1 error handler

2020-05-20 17:00 UTC, rart commented on ui/app/src/services/publishing.ts
> +export function reject(siteId: string, dependencies: string[], items: string[], reason: string, submissionComment: string): Observable<any> {
Type missing

2020-05-20 17:00 UTC, rart commented on ui/app/src/utils/content.ts
> +    deleted: item.isDeleted
Remove if not part of the new items

2020-05-20 17:00 UTC, rart commented on ui/app/src/components/Dialogs/RejectDialog.tsx
> +          () => {
Compose the observables on the reject service. Do a single call here.

2020-05-22 15:24 UTC, rart approved these changes

2020-05-22 15:25 UTC, rart requested changes
- Conflicts
- Is the dialog receiving Sandbox items from legacy? Who calls the reject function con common api. That's unlikely to be sandbox items already.

2020-05-26 18:36 UTC, jvega190 commented
@rart dialog was not receiving sandbox items from legacy, `parseLegacyItemToSandBoxItem` is now being used for the items to be sent properly (sandboxItems)

2020-05-28 08:49 UTC, rart requested changes

2020-05-28 08:49 UTC, rart commented on ui/app/src/components/ComponentMenu.tsx
> +          (item && (item.state === 5 || item.state === 6 || item.state === 2)) &&
I don't think the state will ever be a plain number. This is supposed to be a bit map.

2020-05-28 08:49 UTC, rart commented on ui/app/src/components/Dialogs/RejectDialog.tsx
> +      border: '1px solid #D8D8DC',
Use color from palette

2020-05-28 08:49 UTC, rart commented on ui/app/src/components/Dialogs/RejectDialog.tsx
> +                    />
Don't think we need the keys here. 
Also, change the syntax so plain strings are double quoted and without the curly braces

2020-06-01 17:30 UTC, rart approved these changes

2020-06-01 18:58 UTC, merged