[4198][3.1.x] Change the character limit for username when creating a user
craftercms/studio-ui pull request #1860
Opened 2020-07-17 21:58 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4198

2020-07-23 16:29 UTC, rart requested changes

2020-07-23 16:29 UTC, rart commented on ui/scss/user-dashboard/_admin.scss
> +.username.trim {
Have a look if there’s a common sass file for all the spaces that need this to locate this. create it otherwise

2020-07-28 14:35 UTC, rart requested changes
The idea was rather to include the scss on the existing sheets so we don't have to pull in an additional sheet on the client.

2020-07-28 21:22 UTC, jvega190 commented
@rart imported the styles in the `user-dashboard.scss` file (for angular) and for the other studio part I found that `global.scss` was not being updated anymore (the built file was under /themes/cstudioTheme`, so I updated the source and generated under `/styles`.

2020-07-30 16:40 UTC, rart approved these changes

2020-07-30 16:41 UTC, merged