[4136] - Site Translation - Allow editing of localized view templates
craftercms/studio-ui pull request #1918
Opened 2020-09-16 19:44 UTC by aachavarria

https://github.com/craftercms/craftercms/issues/4136

Refactor on template-editor styles;
Adding ability to edit locale templates;

2020-09-17 17:21 UTC, rart commented on static-assets/components/cstudio-common/common-api.js
> +          html = '<div><svg class="notifyjs-material-icon-root" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><path d="M20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4C12.76,4 13.5,4.1
review

2020-09-17 17:40 UTC, rart requested changes
- fix typos
- notifications are showing incrementally (first time once, second time twice, 3rd thrice)
- fix adding event listener every time a snack is opened

2020-09-17 17:58 UTC, aachavarria commented on static-assets/components/cstudio-common/common-api.js
> +          html = '<div><svg class="notifyjs-material-icon-root" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><path d="M20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4C12.76,4 13.5,4.1
fixed.

2020-09-18 12:02 UTC, rart approved these changes

2020-09-18 13:27 UTC, merged