Fixing Merge Issues;
craftercms/studio-ui pull request #1959
Opened 2020-10-08 20:57 UTC by aachavarria

### Ticket reference or full description of what's in the PR

2020-10-08 20:58 UTC, aachavarria commented
@sumerjabri could you merge this?

2020-10-09 10:10 UTC, rart requested changes

2020-10-09 10:10 UTC, rart commented on ui/app/src/components/SystemStatus/GlobalDialogManager.tsx
>  import EditSiteDialog from '../../modules/System/Sites/Edit/EditSiteDialog';
These should all be lazy imports below like the rest of dialogs

2020-10-09 10:36 UTC, rart commented
https://github.com/craftercms/studio-ui/pull/1962

2020-10-09 10:36 UTC, closed without merging