[4422] Persist content clipboard across refreshes
craftercms/studio-ui pull request #2044
Opened 2020-11-26 21:15 UTC by aachavarria

https://github.com/craftercms/craftercms/issues/4422

2020-12-01 16:51 UTC, rart commented on ui/app/src/components/Navigation/PathNavigator/PathNavigator.tsx
>            }
What happens if you try to paste-from-cut an item on a child? We may need a validation there since I don't think that's allowed.

2020-12-01 16:51 UTC, rart commented on ui/app/src/components/Navigation/PathNavigator/PathNavigator.tsx
>          case itemsPasted.type: {
I'm thinking we should always send/refresh the path to which you're pasting on. If you're there refresh, if you're not there, get the navigator to display that path on which you pasted the new item (same for cut or copy).

2020-12-01 16:51 UTC, rart commented on ui/app/src/models/Item.ts
> +  path?: string;
🤦🏻‍♂️

2020-12-01 16:51 UTC, rart commented on ui/app/src/state/epics/content.ts
> +              emitSystemEvent(itemsPasted({ target: payload.path, clipboard: state.content.clipboard })),
Isn't the state.clipboard empty by this point?

2020-12-01 16:51 UTC, rart commented on ui/app/src/utils/path.ts
> +  sourcePath = withoutIndex(sourcePath);
Should this be done to all paths?

2020-12-01 19:52 UTC, aachavarria commented on ui/app/src/state/epics/content.ts
> +              emitSystemEvent(itemsPasted({ target: payload.path, clipboard: state.content.clipboard })),
no because we are calling unSetClipBoard after this, so in this point the state still contains the clipboard

2020-12-01 19:53 UTC, aachavarria commented on ui/app/src/utils/path.ts
> +  sourcePath = withoutIndex(sourcePath);
already fixed

2020-12-03 08:28 UTC, rart requested changes

2020-12-03 08:28 UTC, rart commented on static-assets/themes/cstudioTheme/yui/assets/skin.css
> +  background-color: #e2e2e2;
Use rgba(...). Try to mimic material. (We're going to require some theming work legacy side to support dark mode.)

2020-12-03 08:28 UTC, rart commented on ui/app/src/components/SystemStatus/GlobalDialogManager.tsx
> +      {state.itemMenu.open && (
This will disrupt animation. Why the if?

2020-12-03 08:28 UTC, rart commented on ui/scss/src/temp.scss
> +    }
Are these styles for the ellipsis? Perhaps better to name as such, then. E.g. item-menu-trigger

2020-12-04 18:45 UTC, rart approved these changes

2020-12-04 18:52 UTC, merged