[studio-ui] Updating LegacyFormDialog;
craftercms/studio-ui pull request #2059
Opened 2020-12-10 22:01 UTC by aachavarria

Updating LegacyFormDialog.tsx to show it on a Dialog;
Adding success messages on wcm_content.js and wcm-dashboardwidget-common.js Edit;

2020-12-11 10:12 UTC, rart requested changes

2020-12-11 10:12 UTC, rart commented on ui/app/src/state/epics/system.ts
> +          message = getIntl().formatMessage(itemSuccessMessages.itemSavedAsDraft);
These two actions do regular save. Why showing save draft message?

2020-12-11 10:12 UTC, rart commented on ui/app/src/utils/i18n-legacy.ts
> +    defaultMessage: 'Item saved as draft'
Item draft saved

2020-12-15 02:35 UTC, aachavarria commented on ui/app/src/state/epics/system.ts
> +          message = getIntl().formatMessage(itemSuccessMessages.itemSavedAsDraft);
fixed

2020-12-15 16:10 UTC, rart commented on ui/app/src/utils/i18n-legacy.ts
> +    defaultMessage: 'There are an edit in progress, to open a new edit form please close or save the previous one'
Message: "Another form is currently open & minimized. Please close the current form before opening another."

We need this case for template editor too.

2020-12-15 16:10 UTC, rart commented on ui/app/src/utils/codebase-bridge.tsx
> +            >
PR mixup 😣

2020-12-15 16:53 UTC, rart commented on static-assets/components/cstudio-forms/forms-engine.js
> +      // deprecated
?

2020-12-15 17:16 UTC, aachavarria commented on ui/app/src/utils/codebase-bridge.tsx
> +            >
no idea

2020-12-15 17:22 UTC, aachavarria commented on ui/app/src/utils/codebase-bridge.tsx
> +            >
this is already on develop, should not be listed here

2020-12-16 09:07 UTC, rart requested changes

2020-12-16 09:07 UTC, rart commented on ui/app/src/utils/i18n-legacy.ts
> +    defaultMessage: 'Another form is currently open & minimized. Please close the current form before opening another'
"Another **editor** is currently..."

2020-12-16 09:07 UTC, rart commented on ui/app/src/state/epics/dialogs.ts
> +            })
The confirm dialog presents a question and this isn't one. We need to change the graphic and only the accept button should show up. See Confirm Dialog designs on Figma (3.2 project) for guidance.

We need to tweak ConfirmDialog to allow graphic swapping.
```jsx
function ConfirmDialogWrapper(props: ConfirmDialogProps) {
  const { onOk, onCancel, body, title, children, classes, imageUrl = questionGraphicUrl } = props;
  const { formatMessage } = useIntl();
  useUnmount(props.onClosed);
  return (
    <>
      <DialogContent id="confirmDialogBody" className={classes.dialogBody}>
        <img src={imageUrl} alt="" />
```

2020-12-16 15:23 UTC, rart commented on ui/app/src/utils/i18n-legacy.ts
> +    defaultMessage: 'Another editor is currently open & minimized. Please close the current form before opening another'
"Please close the current **editor** before opening another"

2020-12-16 15:23 UTC, rart commented on ui/app/src/state/epics/dialogs.ts
> +              body: getIntl().formatMessage(codeEditorMessages.inProgressConfirmation)
info graphic

2020-12-17 11:48 UTC, rart requested changes

2020-12-17 11:48 UTC, rart commented on ui/app/src/utils/i18n-legacy.ts
> +      'Another editor is currently open & minimized. Please close the current editor before opening another'
This is a form. The other is an editor. This was was fine saying form in both sentences. The one above should say editor in both sentences.

2020-12-17 11:48 UTC, rart commented on ui/app/src/state/epics/dialogs.ts
> +              body: getIntl().formatMessage(codeEditorMessages.inProgressConfirmation)
Why is this resolved? It isn’t fixed yet.

2020-12-17 15:00 UTC, rart approved these changes

2020-12-17 15:14 UTC, sumerjabri commented
@aachavarria please fix conflicts

2020-12-17 15:34 UTC, aachavarria commented
> @aachavarria please fix conflicts

done

2020-12-17 17:00 UTC, rart approved these changes

2020-12-17 17:08 UTC, merged