updating content inheritance on page builder
craftercms/studio-ui pull request #2067
Opened 2020-12-16 18:50 UTC by aachavarria

### Ticket reference or full description of what's in the PR

2020-12-17 12:01 UTC, rart requested changes

2020-12-17 12:01 UTC, rart commented on ui/app/src/models/ContentInstance.ts
> +  sourceMap?: { [fieldId: string]: string }; // fieldId: path
I’m thinking we could have both things here. When parsing content the sourceMap would be populated with both { fieldId: path, path: contentTypeId }.

2020-12-17 12:01 UTC, rart commented on ui/guest/src/classes/ICERegistry.ts
> +    field = record.fieldId ? contentTypeUtils.getField(contentType, record.fieldId) : null;
Add `inherited: boolean`?

2020-12-17 12:01 UTC, rart commented on ui/guest/src/controls/rte.ts
> +            const model = getReferentialEntries({ ...record, fieldId: field.id }).model;
Why not just sent the record? The records field and the field should match.

2020-12-17 12:01 UTC, rart commented on ui/guest/src/react/GuestProxy.tsx
> +          const field = ContentType.getField(contentType, fieldId);
Not using field later so looks like you can roll this back?

2020-12-18 14:27 UTC, aachavarria commented on ui/guest/src/controls/rte.ts
> +            const model = getReferentialEntries({ ...record, fieldId: field.id }).model;
rollback

2020-12-21 15:49 UTC, rart requested changes

2020-12-21 15:49 UTC, rart commented on ui/app/src/services/content.ts
>        debugger;
👆

2020-12-21 15:49 UTC, rart commented on ui/app/src/utils/model.ts
> +  return !!model.craftercms.sourceMap?.[fieldId];
`!!model.craftercms.sourceMap?.[fieldId]` => `Boolean(model.craftercms.sourceMap?.[fieldId])`

2020-12-21 16:06 UTC, aachavarria commented on ui/app/src/services/content.ts
>        debugger;
removed

2020-12-23 16:51 UTC, rart approved these changes

2020-12-23 17:17 UTC, merged