[studio-ui] Receptacles datasource is not filtering options selected in configuration #4393
craftercms/studio-ui pull request #2129
Opened 2021-01-22 16:55 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4393

2021-01-25 13:07 UTC, rart requested changes
https://github.com/craftercms/craftercms/issues/4393#issuecomment-766803322

2021-01-26 06:58 UTC, rart commented on static-assets/components/cstudio-admin/mods/content-type-propsheet/boolean.js
> +          valueEl.dispatchEvent(new Event('propertyUpdate', { event }));
How about just subscribing to the change event of the control?

2021-01-27 03:41 UTC, rart requested changes
Is this ready?

2021-01-27 03:41 UTC, rart commented on static-assets/components/cstudio-admin/mods/content-types.js
> +      isDependencyMet: function(dependency) {
Add console logs for warning not supported stuff. Ping me to discuss message

2021-01-28 15:58 UTC, rart requested changes

2021-01-28 15:58 UTC, rart commented on ui/app/src/utils/i18n-legacy.ts
>    }
This was really just meant to be a console.log. No need for translation or UI popup etc. The file name should be fixed to the file name that issues the log so when we see it we can easily find, inspect and address if needed.

2021-01-31 10:09 UTC, rart approved these changes

2021-02-01 04:50 UTC, sumerjabri commented
@rart anything to be done regarding: https://app.codacy.com/gh/craftercms/studio-ui/pullRequest?prid=6840088

2021-02-01 07:08 UTC, rart commented
> @rart anything to be done regarding: https://app.codacy.com/gh/craftercms/studio-ui/pullRequest?prid=6840088

no, @sumerjabri

2021-02-01 14:01 UTC, merged