[3757] Add date format support to Crafter Studio
craftercms/studio-ui pull request #2261
Opened 2021-04-07 00:47 UTC by jvega190

https://github.com/craftercms/craftercms/issues/3757

2021-04-07 08:10 UTC, rart requested changes

2021-04-07 08:10 UTC, rart commented on ui/app/src/services/locale.ts
> +export function fetchLocaleSettings(site: string): Observable<any> {
move to configuration service

2021-04-07 08:10 UTC, rart commented on ui/app/src/state/actions/system.ts
> +export const fetchLocaleSettingsFailed = /*#__PURE__*/ createAction('FETCH_LOCALE_SETTINGS_FAILED');
FETCH_SITE_LOCALE_*

2021-04-08 08:58 UTC, rart requested changes

2021-04-08 08:58 UTC, rart commented on static-assets/components/cstudio-dashboard-widgets/approved-scheduled-items.js
> -        var lastEditTime = CStudioAuthoring.Utils.formatDateFromUTC(item.eventDate, studioTimeZone);
Why not rely on formatDateFromUTC to do the new mechanics?

2021-04-08 08:58 UTC, rart commented on ui/app/src/state/reducers/uiConfig.ts
> +    localeCode: '',
Default to en-US

2021-04-08 08:58 UTC, rart commented on ui/app/src/state/reducers/uiConfig.ts
> +    dateFormatOptions: {}
Default to { time zone: same default time zone as xml default }

2021-04-13 11:50 UTC, rart commented on static-assets/components/cstudio-dashboard-widgets/my-recent-activity.js
> +      CStudioAuthoring.Utils.formatDateFromUTC(item.eventDate, studioTimeZone) + '---',
What's the `'---'` for?

2021-04-13 11:50 UTC, rart commented on static-assets/scripts/admin.js
> +        sitesService.fetchSiteLocale(activeSite).then(function(locale) {
?

2021-04-13 11:50 UTC, rart commented on static-assets/scripts/main.js
> +        const activeSite = store.getState().sites.active ?? 'editorial';
?

2021-04-13 15:17 UTC, jvega190 commented on static-assets/components/cstudio-dashboard-widgets/my-recent-activity.js
> +      CStudioAuthoring.Utils.formatDateFromUTC(item.eventDate, studioTimeZone) + '---',
not needed, removing

2021-04-15 07:47 UTC, rart requested changes

2021-04-15 07:47 UTC, rart commented on static-assets/scripts/admin.js
> +              }
This wouldn't show any time info. We need some additional defaults to make sure time too is shown.
Call me to discuss.

2021-04-15 07:47 UTC, rart commented on static-assets/scripts/main.js
> +                };
Same deal. We should also place this somewhere common to all these.

2021-04-16 09:39 UTC, rart requested changes

2021-04-16 09:39 UTC, rart commented on static-assets/components/cstudio-forms/controls/date-time.js
> +    this.hour12 = this.locale.dateTimeFormatOptions?.hour12 ?? true;
Asynchrony may be an issue here. This would likely pick up the default and not realised when the actual config has loaded.

2021-04-16 09:39 UTC, rart commented on static-assets/components/cstudio-forms/controls/time.js
> +    this.hour12 = CrafterCMSNext.system.store.getState().uiConfig.locale.dateTimeFormatOptions?.hour12 ?? true;
Async issues

2021-04-16 09:39 UTC, rart commented on static-assets/scripts/admin.js
> +        sitesService.fetchSiteLocale(activeSite).then((locale) => {
There may not be an active site. Need fallback.

2021-04-20 11:19 UTC, rart approved these changes

2021-04-20 13:30 UTC, merged