[4474] Use material design icons all across UI next and remove font awesome
craftercms/studio-ui pull request #2266
Opened 2021-04-13 23:31 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4474

2021-04-14 21:22 UTC, jvega190 commented
Blueprints configs need to be updated, waiting for approval of ticket in case there are config updates pending

2021-04-15 07:38 UTC, rart requested changes

2021-04-15 07:38 UTC, rart commented on ui/app/src/assets/uiConfigDefaults.ts
> +              id: '@material-ui/icons/DashboardOutlined'
We're using rounded version on the Launcher. Let's keep it consistent.

2021-04-15 07:38 UTC, rart commented on ui/app/src/assets/uiConfigDefaults.ts
>                    },
This was mostly for testing purposes. Let's just leave `icon: { DescriptionOutlined }`

2021-04-15 07:38 UTC, rart commented on ui/app/src/assets/uiConfigDefaults.ts
>                    },
Same deal, just leave one. Use our custom "Component" icon.

2021-04-15 07:38 UTC, rart commented on ui/app/src/assets/uiConfigDefaults.ts
>                    },
Same

2021-04-15 07:38 UTC, rart commented on ui/app/src/assets/uiConfigDefaults.ts
>                    },
Same

2021-04-15 07:38 UTC, rart commented on ui/app/src/assets/uiConfigDefaults.ts
> +                    id: '@material-ui/icons/InsertDriveFileRounded'
Same

2021-04-15 07:38 UTC, rart commented on ui/app/src/assets/uiConfigDefaults.ts
> +                    collapsed: '@material-ui/icons/CodeRounded'
?

2021-04-15 07:38 UTC, rart commented on ui/app/src/components/Launcher/Launcher.tsx
> +
x empty line

2021-04-15 07:38 UTC, rart commented on ui/app/src/components/PathNavigator/PathNavigatorHeader.tsx
> +        {icon && <SystemIcon icon={icon} svgIconProps={{ className: classes.headerIcon }} />}
Please add className & style as direct props of SystemIcon too (and merge accordingly)

2021-04-15 07:38 UTC, rart commented on ui/app/src/modules/Preview/ToolsPanel.tsx
> +  '@material-ui/icons/DashboardOutlined': DashboardOutlined,
👆

2021-04-16 09:43 UTC, rart approved these changes

2021-04-16 14:05 UTC, merged