[4631] Different times are show in Studio between request publish, schedule and published item.
craftercms/studio-ui pull request #2284
Opened 2021-04-20 22:38 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4631
- Fixed time format inconsistencies in item tooltips.

2021-04-20 22:41 UTC, jvega190 commented
@rart I need to discuss with you one finding that is affecting date timezone conversions, making it inconsistent between sidebar tree items tooltips and dashboard items tooltips

2021-04-21 15:57 UTC, jvega190 commented
@rart Updated timezones library with the one without moment and moment-timezone, tested in publish dialogs and targeting. Imported moment and momen-timezone libraries are already minified.

2021-04-21 15:59 UTC, rart requested changes

2021-04-21 15:59 UTC, rart commented on static-assets/components/cstudio-components/loader.js
> +    path: 'jquery/timezones/timezones-0.1.0.min.js?version=' + CStudioAuthoring.UIBuildId
remove `?version=`+uibuildid

2021-04-21 16:19 UTC, rart approved these changes

2021-04-21 16:23 UTC, merged