[4639] Create Item Megamenu
craftercms/studio-ui pull request #2287
Opened 2021-04-22 00:31 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4639

2021-04-22 00:33 UTC, jvega190 commented
@rart I created another ContextMenu file to make the megamenu updates without messing with the current (used for other things). Need to discuss how to update to reuse the actual component

2021-04-23 06:19 UTC, rart requested changes

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/ItemDisplay/ItemDisplay.tsx
> +      {showItemType && <ItemTypeIcon item={item} classes={{ root: clsx(classes.icon, classes.typeIcon) }} />}
Let's add the `className` prop to all these (which internally, is applied to the root element).

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/ItemMegaMenu/ItemMegaMenu.tsx
> +        [
Why wrap this in an array? Use fragment. Remove unnecessary keys.

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/ItemMegaMenu/ItemMegaMenu.tsx
> +        </div>
Use EmptyState component. Size the graphic accordingly.

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/ItemMegaMenu/ItemMegaMenu.tsx
> +  classes?: MenuProps['classes'] & Partial<Record<'menuItem' | 'emptyRoot', string>>;
create ClassKey & Styles types and apply them (see ItemDisplay for example)

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/ItemMegaMenu/ItemMegaMenu.tsx
> +              <ItemPublishingTargetIcon item={item} classes={{ root: classes.icon }} />
use className instead of classes={root...}

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/ItemMegaMenu/ItemMegaMenu.tsx
> +              <ItemStateIcon item={item} classes={{ root: classes.icon }} />
use className instead of classes={root...}

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/ItemMegaMenu/ItemMegaMenu.tsx
> +  const publishingOptions = options.slice(1);
These aren't just "publishing options". Find better name (i.e. nonEditorialOptions, restOptions).

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/ItemMegaMenu/ItemMegaMenu.tsx
> +                id="workflowCancellation.title"
?

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/ItemStateIcon/ItemStateIcon.tsx
> +      <TheIcon className={clsx(classes.root, propClasses.root, classes.publishingIcon, stateSpecificClass)} />
```suggestion
      <TheIcon className={clsx(classes.root, propClasses?.root, classes.publishingIcon, stateSpecificClass)} />
```

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/ItemPublishingTargetIcon/ItemPublishingTargetIcon.tsx
> +          propClasses.root,
```suggestion
          propClasses?.root,
```

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/ItemPublishingTargetIcon/ItemPublishingTargetIcon.tsx
> +  classes: Partial<Record<ItemPublishingTargetIconClassKey, string>>;
```suggestion
  classes?: Partial<Record<ItemPublishingTargetIconClassKey, string>>;
```

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/ItemStateIcon/ItemStateIcon.tsx
> +  classes: Partial<Record<ItemStateIconClassKey, string>>;
```suggestion
  classes?: Partial<Record<ItemStateIconClassKey, string>>;
```

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/ItemTypeIcon/ItemTypeIcon.tsx
> +  classes: ItemDisplayProps['classes'];
Declare class key (even if it's just 1).

```suggestion
  classes?: ItemTypeIconClassKey;
```

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/PathNavigator/PathNavigator.tsx
>        />
Let's look into removing it here from and using GlobalDialogManager

2021-04-23 06:19 UTC, rart commented on ui/app/src/components/SystemStatus/GlobalDialogManager.tsx
> +      />
Split `ItemMegaMenu` into container & presentational — right now it's sort of mixed. After the refactor, global dialog manager won't need to supply it with any props.

2021-04-23 16:13 UTC, jvega190 commented on ui/app/src/components/ItemMegaMenu/ItemMegaMenu.tsx
> +        [
I originally wrapped it with a fragment, but it shows this warning on the console: 
`Material-UI: The Menu component doesn't accept a Fragment as a child.
Consider providing an array instead.`

2021-04-23 16:22 UTC, jvega190 commented on ui/app/src/components/ItemDisplay/ItemDisplay.tsx
> +      {showItemType && <ItemTypeIcon item={item} classes={{ root: clsx(classes.icon, classes.typeIcon) }} />}
instead of classes or both the props should be supported by the component?

2021-04-23 16:23 UTC, rart commented on ui/app/src/components/ItemDisplay/ItemDisplay.tsx
> +      {showItemType && <ItemTypeIcon item={item} classes={{ root: clsx(classes.icon, classes.typeIcon) }} />}
Both

2021-04-23 17:48 UTC, rart commented on ui/app/src/components/ItemMegaMenu/ItemMegaMenu.tsx
> +            <Typography variant="body2" component="h2">
```suggestion
            <Typography variant="body2">
```

2021-04-23 17:48 UTC, rart commented on ui/app/src/components/ItemMegaMenu/ItemMegaMenu.tsx
> +              />
Must handle the cases of unavailable pieces of this string (e.g. a null `by`, etc)

2021-04-23 22:53 UTC, jvega190 commented on ui/app/src/components/ItemMegaMenu/ItemMegaMenu.tsx
> +        </div>
Updated, it looks like this:
![Screenshot from 2021-04-23 16-25-19](https://user-images.githubusercontent.com/18267471/115937141-58442080-a454-11eb-9c5f-6e415303e5a6.png)

2021-04-27 09:35 UTC, rart commented on ui/app/src/components/ItemMegaMenu/ItemMegaMenu.tsx
> +        </div>
That's ok, but leave the item info on (above & below) and show empty state on the options area.

2021-04-27 09:40 UTC, rart commented on static-assets/components/cstudio-contextual-nav/wcm-site-dropdown-mods/wcm-root-folder.js
> -          );
Considering legacy, perhaps we do need a loader on the Megamenu. Check how it looks with throttled network opening menu on legacy.

2021-04-28 18:38 UTC, rart approved these changes

2021-04-28 19:20 UTC, merged