[4712] Item States Reactify
craftercms/studio-ui pull request #2360
Opened 2021-06-02 23:56 UTC by aachavarria

### Ticket reference or full description of what's in the PR

2021-06-08 14:05 UTC, rart requested changes

2021-06-08 14:05 UTC, rart commented on ui/app/src/components/ItemStatesManagement/ItemStatesManagement.tsx
> +    400
Wasn't this callback getting changed ignored by useDebouncedInput?

2021-06-08 14:05 UTC, rart commented on ui/app/src/components/ActionsBar/ActionsBar.tsx
> +      background: palette.blue.highlight
`theme.palette.action.active`

2021-06-08 14:05 UTC, rart commented on ui/app/src/components/ItemStatesGrid/styles.ts
> +      backgroundColor: palette.blue.highlight
theme.palette.action.active

2021-06-08 14:05 UTC, rart commented on ui/app/src/components/ItemStatesManagement/styles.ts
> +      textTransform: 'uppercase',
What's this for? I don't remember anything uppercased in the designs.

2021-06-08 14:05 UTC, rart commented on ui/app/src/components/PersistentDrawer/PersistentDrawer.tsx
> +      top: 64,
See recent changes on ResizesableDrawer in regards to adding this top value.

2021-06-08 14:05 UTC, rart commented on ui/app/src/components/SetWorkflowStateDialog/SetWorkFlowStateDialogContainer.tsx
> +export function SetWorkflowStateDialogContainer(props: SetWorkflowStateDialogProps) {
SetItemStateDialog*
Remember to change directory names too

2021-06-08 14:05 UTC, rart commented on ui/app/src/services/workflowStates.ts
> +export function fetchItemStates(
rename as `workflow.ts`

2021-06-08 14:05 UTC, rart commented on ui/app/src/components/PersistentDrawer/PersistentDrawer.tsx
> +export default function PersistentDrawer(props: ResizeableDrawerProps) {
Not sure I see much value in this component. 
Perhaps we could just use the ResizableDrawer with resize={false} or something of sorts.

2021-06-08 14:14 UTC, aachavarria commented on ui/app/src/components/ItemStatesManagement/styles.ts
> +      textTransform: 'uppercase',
"Show Items In"

2021-06-09 05:25 UTC, rart approved these changes

2021-06-09 13:31 UTC, merged