[4796] Reactify Code Editor
craftercms/studio-ui pull request #2393
Opened 2021-06-22 14:30 UTC by aachavarria

https://github.com/craftercms/craftercms/issues/4796

2021-06-23 11:00 UTC, rart requested changes

2021-06-23 11:00 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialog.tsx
> +  open?: boolean;
should not be optional

2021-06-23 11:00 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialog.tsx
> +      dispatch(ConditionallyUnlockItem({ path: props.path, notify: false }));
action name should not be capitalised

2021-06-23 11:00 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialog.tsx
> +    <Dialog open={open && !minimized} keepMounted={minimized} onClose={onClose} {...rest} fullWidth maxWidth="xl">
fullwidth and maxwidth can be overridden too
```suggestion
    <Dialog open={open && !minimized} keepMounted={minimized} onClose={onClose} fullWidth maxWidth="xl" {...rest}>
```

2021-06-23 11:00 UTC, rart commented on ui/app/src/utils/string.ts
> +export function isCamelCase(str: string) {
This doesn't test for camel case.
```suggestion
export function hasUppercaseChars(str: string) {
```

2021-06-23 11:00 UTC, rart commented on ui/app/src/utils/hooks.ts
> +  }, [dispatch, item, path]);
We need a mechanism to make sure we don't dispatch a million of these calls due to subsequent renders when the item hasn't loaded yet.

2021-06-23 11:00 UTC, rart commented on ui/app/src/state/epics/content.ts
> +      ofType(ConditionallyUnlockItem.type),
```suggestion
  // region conditionallyUnlockItem
  (action$, state$) =>
    action$.pipe(
      ofType(conditionallyUnlockItem.type),
```

2021-06-23 11:00 UTC, rart commented on ui/app/src/state/epics/content.ts
> +          return NEVER;
`filter` instead of `NEVER`

2021-06-23 11:00 UTC, rart commented on ui/app/src/state/actions/content.ts
> +export const ConditionallyUnlockItem = /*#__PURE__*/ createAction<{ path: string; notify?: boolean }>(
```suggestion
export const conditionallyUnlockItem = /*#__PURE__*/ createAction<{ path: string; notify?: boolean }>(
```

2021-06-23 11:00 UTC, rart commented on ui/app/src/state/actions/content.ts
> +export const ConditionallyUnlockItem = /*#__PURE__*/ createAction<{ path: string; notify?: boolean }>(
Add a bit of a comment explaining what the action does — explain it's conditionality

2021-06-23 11:00 UTC, rart commented on ui/app/src/services/content.ts
> +  unlock: boolean = true
Please check if `user` is optional for the service. Let's try to modify the abstraction to be like this:
```suggestion
  site: string,
  path: string,
  content: string,
  options?: { user?: string, unlock?: boolean }
```

2021-06-23 11:00 UTC, rart commented on ui/app/src/components/CodeEditorDialog/utils.ts
> +  }
Please move snippets to ui.xml

@sumerjabri @russdanner fyi

2021-06-24 14:09 UTC, rart requested changes

2021-06-24 14:09 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +            <FormattedMessage id="codeEditor" defaultMessage="Content model" />
bad message id

2021-06-24 14:09 UTC, rart commented on ui/app/src/services/content.ts
> +          ...ajaxResponse,
fake out the `500` status

2021-06-24 14:09 UTC, rart commented on ui/app/src/state/actions/content.ts
> +// To unlock a item the item.lockOwner should be empty or should be equals to the current user, this action check if can be unlocked
Why would you issue an unlock call for an item that's already unlocked?
```suggestion
// This action's semantic is to unlock the item only if the lock owner is the current user.
```

2021-06-24 14:09 UTC, rart commented on ui/app/src/state/epics/content.ts
> +          state.content.itemsByPath[payload.path].lockOwner === state.user.username
Why would you issue an unlock call for an item that's already unlocked?
```suggestion
        ([{ payload }, state]) =>
          state.content.itemsByPath[payload.path].lockOwner === state.user.username
```

2021-06-24 14:09 UTC, rart commented on ui/app/src/state/epics/content.ts
> +      filter(
```suggestion
      withLatestFrom(state$),
      filter(
```

2021-06-24 14:09 UTC, rart commented on ui/app/src/state/epics/content.ts
> +            payload.notify === false
Would this cause two snacks?
Perhaps it'd better to only notify if notify === true

2021-06-24 14:09 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +            <FormattedMessage id="codeEditor.addCode" defaultMessage="Insert Code" />
```suggestion
            <FormattedMessage id="codeEditor.insertCode" defaultMessage="Insert Code" />
```

2021-06-24 14:09 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +            theme={`ace/theme/${type === 'light' ? 'chrome' : 'tomorrow_night'}`}
Let's move the theme switching logic to the AceEditor component. If theme prop is received, it uses that, if undefined, it does the theme.palette.type check to determine which of these to use.

2021-06-24 14:09 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +            enableLiveAutocompletion={true}
```suggestion
            enableBasicAutocompletion
            enableSnippets
            enableLiveAutocompletion
```

2021-06-24 14:09 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +  }, [readonly, editorRef.current, content, disableEdit]);
Explain/comment why you're suppressing the exhaustive deps

2021-06-24 14:09 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +                hasUppercaseChars(fields[key].id) ? `["${dasherize(underscore(fields[key].id))}"]` : fields[key].id
Please explain this logic. What is it that the presence of uppercase chars dictates? What's happening here.

2021-06-24 14:09 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +  const disableEdit = !item || (item.stateMap.locked && item.lockOwner !== user.username);
Would the util that we created for edit mode work here? We're not checking for write permission here, which perhaps we should be.

2021-06-24 14:09 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +export function CodeEditorDialogContainer(props: CodeEditorDialogContainerProps) {
Where is the item getting locked throughout opening it for edit? 
Do we need a conditionallyLockItem too?

2021-06-25 16:05 UTC, rart requested changes

2021-06-25 16:05 UTC, rart commented on ui/app/src/components/AceEditor.tsx
> +  );
```suggestion
  const options = pluckProps(props as AceOptions, true, ...aceOptions);
  options.theme = options.theme ?? `ace/theme/${type === 'light' ? 'chrome' : 'tomorrow_night'}`;
```

2021-06-25 16:05 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +                'VARIABLENAME',
```suggestion
                'VARIABLE_NAME',
```

2021-06-25 16:05 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +                hasUppercaseChars(fields[key].id) ? `["${dasherize(underscore(fields[key].id))}"]` : fields[key].id
Logic not explained as requested. 👆

2021-06-25 16:05 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +                hasUppercaseChars(fields[key].id) ? `"${dasherize(underscore(fields[key].id))}"` : fields[key].id
Don't understand. Call me to review.

2021-06-25 16:05 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +            icon: 'MinimizeIcon',
Icon is a string?

2021-06-25 16:20 UTC, aachavarria commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +            icon: 'MinimizeIcon',
can be a string or icon

2021-06-27 09:34 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +            icon: 'MinimizeIcon',
But if a string, doesn't it have to be an id? Like @material-ui/icons/Minimize? Otherwise, where/how are the string options defined?

2021-07-01 09:32 UTC, rart requested changes

2021-07-01 09:32 UTC, rart commented on ui/app/src/services/configuration.ts
> +          config.datasets[tag.id.replace('craftercms.', '')] = applyDeserializedXMLTransforms(
```suggestion
          config.datasets[tag.id] = applyDeserializedXMLTransforms(
```

2021-07-01 09:32 UTC, rart commented on ui/app/src/components/AceEditor.tsx
> -      className={props.className ?? classes.base}
add prop `classes.{root,editorRoot}`.
please create class key and Styles typing

2021-07-01 09:32 UTC, rart commented on ui/app/src/components/AceEditor.tsx
>        }}
Move style on to `root` class

2021-07-05 09:17 UTC, rart approved these changes

2021-07-06 13:26 UTC, merged