[4805] Create image editor control
craftercms/studio-ui pull request #2401
Opened 2021-06-28 21:52 UTC by aachavarria

https://github.com/craftercms/craftercms/issues/4805

2021-06-30 17:08 UTC, rart commented on ui/app/src/components/BrowseFilesDialog/BrowseFilesDialog.tsx
> +export interface BrowseFilesDialogProps {
Extend dialog props and use them

2021-06-30 17:08 UTC, rart commented on ui/app/src/components/BrowseFilesDialog/BrowseFilesDialogUI.tsx
> +  }, [path, site]);
We should look at how the legacy browse dialog works and what it does.

2021-06-30 17:08 UTC, rart commented on ui/app/src/components/MediaCard.tsx
> +          onClick={() => onPreview && onPreview(item)}
```suggestion
          onClick={() => onPreview?.(item)}
```

2021-06-30 17:08 UTC, rart commented on ui/app/src/utils/path.ts
> +  }
```suggestion
path = path.replace(/{(year|yyyy)}/g, String(currentDate.getFullYear()));
```
same deal for the ones below. No need for if.

2021-06-30 17:08 UTC, rart commented on ui/app/src/utils/path.ts
> +export function expandPathMacros(path: string) {
Let's go with the `values` argument that would internally call another `format` util.

2021-06-30 18:23 UTC, aachavarria commented on ui/app/src/components/BrowseFilesDialog/BrowseFilesDialogUI.tsx
> +  }, [path, site]);
it is a new approach, and I think it is better because is using api2

2021-07-01 09:50 UTC, rart requested changes

2021-07-01 09:50 UTC, rart commented on ui/app/src/utils/path.ts
> +    .replace(/{(dd)}/g, ('0' + currentDate.getDate()).slice(-2));
```suggestion
    .replace(/{dd}/g, ('0' + currentDate.getDate()).slice(-2));
```

2021-07-01 09:50 UTC, rart commented on ui/app/src/services/content.ts
> -  path: string,
How come this isn't used? How does it know where to upload?

2021-07-01 09:50 UTC, rart commented on ui/app/src/components/BrowseFilesDialog/BrowseFilesDialogUI.tsx
> +  }, [path, site]);
Not suggesting to change it just yet. Just check what the old one does to make sure this covers all of that.

2021-07-01 09:50 UTC, rart commented on ui/app/src/components/BrowseFilesDialog/BrowseFilesDialog.tsx
> +  const { open, path, type, onClose, onClosed, ...rest } = props;
```suggestion
  const { path, type, onClosed, ...rest } = props;
```

2021-07-01 09:50 UTC, rart commented on ui/app/src/components/BrowseFilesDialog/BrowseFilesDialog.tsx
> +    <Dialog open={open} onClose={onClose} {...rest} fullWidth maxWidth="md">
```suggestion
    <Dialog fullWidth maxWidth="md" {...rest}>
```

2021-11-19 16:08 UTC, rart commented
Will revisit this when we're ready to proceed. Please keep the branch.

2021-11-19 16:08 UTC, closed without merging