[studio-ui] 4.0.0/stability
craftercms/studio-ui pull request #2411
Opened 2021-07-06 19:52 UTC by aachavarria

- Renaming default SearchBar placeholder to 'Filter...'

2021-07-07 15:45 UTC, rart requested changes

2021-07-07 15:45 UTC, rart commented on ui/app/src/components/PreviewSearchPanel/PreviewSearchPanel.tsx
> +    defaultMessage: 'Search...'
```suggestion
    defaultMessage: 'Search'
```

2021-07-07 15:45 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialog.tsx
> +    <Dialog open={open && !minimized} keepMounted={minimized} onClose={onDialogClose} fullWidth maxWidth="xl" {...rest}>
```suggestion
    <Dialog fullWidth maxWidth="xl" {...rest} open={open && !minimized} keepMounted={minimized} onClose={onDialogClose}>
```

2021-07-08 12:48 UTC, rart approved these changes

2021-07-08 14:11 UTC, sumerjabri approved these changes

2021-07-08 14:11 UTC, merged