[4782] Add <- and -> (forward and back) buttons to the URL/internal browser in Preview Toolbar
craftercms/studio-ui pull request #2421
Opened 2021-07-09 18:59 UTC by aachavarria

https://github.com/craftercms/craftercms/issues/4782

2021-07-12 20:00 UTC, rart approved these changes

2021-07-12 21:52 UTC, rart approved these changes

2021-07-13 20:23 UTC, sumerjabri commented
@rart I'll wait for the final updates we did today to make it in (I wasn't able to find it in this PR).

2021-07-16 20:01 UTC, rart requested changes

2021-07-16 20:01 UTC, rart commented on ui/app/src/state/reducers/previewNavigation.ts
> +    [checkInGuest.type]: (state, { payload }) => {
Please add these type of comments to each action
```suggestion
    // A page is being visited or reloaded
    // - Push the url into the back stack (if not already pushed)
    // - Clear the forward stack (if not already pushed)
    // - Update the current url
    [checkInGuest.type]: (state, { payload }) => {
```

2021-07-16 20:01 UTC, rart commented on ui/guest/src/react/GuestProxy.tsx
> +              ifrm.setAttribute('src', `${currentFullUrl}`);
```suggestion
              ifrm.setAttribute('src', currentFullUrl);
```

2021-07-16 20:01 UTC, rart commented on ui/app/src/state/reducers/previewNavigation.ts
> +    }
```suggestion
    [changeSite.type]: (state, { payload }) => ({
      ...state,
      historyBackStack: [],
      historyForwardStack: [],
      historyNavigationType: null,
      currentUrlPath: payload.nextUrl ?? state.currentUrlPath
    })
```

2021-07-16 20:01 UTC, rart commented on ui/app/src/modules/Preview/PreviewConcierge.tsx
> +                payload: { ...payload, currentFullUrl: guestBase + currentUrlPath }
```suggestion
                payload: { ...payload, currentFullUrl: ˋ${guestBase}${currentUrlPath}ˋ }
```

2021-07-16 20:01 UTC, rart commented on ui/app/src/modules/Preview/PreviewConcierge.tsx
> +                payload: { ...payload, currentFullUrl: guestBase + currentUrlPath }
```suggestion
                payload: { ...payload, currentFullUrl: ˋ${guestBase}${currentUrlPath}ˋ }
```

2021-07-16 20:01 UTC, rart commented on ui/app/src/modules/Preview/Host.tsx
> +        url={currentUrlPath === '' ? previewLandingBase : guestBase + currentUrlPath}
```suggestion
        url={currentUrlPath === '' ? previewLandingBase : ˋ${guestBase}${currentUrlPath}ˋ}
```

2021-07-19 14:53 UTC, rart requested changes

2021-07-19 14:53 UTC, rart commented on ui/app/src/state/reducers/previewNavigation.ts
> +    [checkInGuest.type]: (state, { payload }) => {
Still missing the comments for the rest of the actions

2021-07-19 15:11 UTC, rart approved these changes

2021-07-19 15:48 UTC, merged