[4716] Item icons in dashboard and site explorer does not match
craftercms/studio-ui pull request #2427
Opened 2021-07-13 16:09 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4716

Update for Recently Published widget to handle multiple events for the same item.

2021-07-13 16:09 UTC, jvega190 commented
Leaving as draft as we're waiting for this: https://github.com/craftercms/craftercms/issues/4832

2021-07-15 10:41 UTC, rart approved these changes

2021-07-15 10:41 UTC, rart commented on ui/app/src/components/RecentlyPublishedDashlet/RecentlyPublishedDashlet.tsx
> +                return `${item.uri}${item.eventDate}`;
```suggestion
                const key = `${item.uri}:${item.eventDate}`:
                childrenLookup[key] = parseLegacyItemToDetailedItem(item);
                return key;
```

2021-07-15 10:42 UTC, rart requested changes
Pressed wrong button. Please see requested changes on comments above.

2021-07-15 16:10 UTC, rart approved these changes

2021-07-15 20:44 UTC, merged