[4716] Item icons in dashboard and site explorer does not match
craftercms/studio-ui pull request #2447
Opened 2021-07-16 22:20 UTC by jvega190

Fix dashboard issues 
- Items not checking on recentlyPublishedDashlet
- Add save dashboard preferences

https://github.com/craftercms/craftercms/issues/4716

2021-07-16 22:20 UTC, jvega190 commented
@rart created PR as draft since I need some confirmation from Vita

2021-07-20 13:13 UTC, rart requested changes
Store all prefs of all widgets
- ItemsAwaitingApproval: collapsed, showUnpublished
- ApprovedScheduled: collapsed, filter
- RecentlyPublished: collapsed, numOfItems, filter
- MyRecent: collapsed, numOfItems, filter

2021-07-20 13:13 UTC, rart commented on ui/app/src/utils/state.ts
> +}
Shouldn't these be per dashlet?

2021-07-20 13:13 UTC, rart commented on ui/app/src/utils/content.ts
> +      lastPublishedDate: item.publishedDate ?? item.eventDate,
- `eventDate` can't be both. it's either `datePublished` or `dateScheduled`.
- These prop names are actually outdated. Please update `PublishEnvProps` interface
  -  lastScheduledDate => dateScheduled
  - lastPublishedDate => datePublished
<img width="421" alt="image" src="https://user-images.githubusercontent.com/3928341/126327073-1b699af8-3143-4fac-a43d-f36a55bc1767.png">

2021-07-20 13:13 UTC, rart commented on ui/app/src/utils/content.ts
> +      lastPublishedDate: item.publishedDate ?? item.eventDate,
Same as above.

2021-07-20 13:13 UTC, rart commented on ui/app/src/models/Dashboard.ts
> +}
Should probably be in each dashlet. Is it the same preference(s) for all?

2021-07-20 14:49 UTC, rart commented on ui/app/src/utils/state.ts
> +  return window.localStorage.setItem(`craftercms.${user}.dashboardPreferences.${site}`, JSON.stringify(value));
```suggestion
  return window.localStorage.setItem(`craftercms.dashboard.${dashletId}.${site}.${user}`, JSON.stringify(value));
```

2021-07-21 14:30 UTC, rart commented on ui/app/src/components/IconGuideDashlet/IconGuideDashlet.tsx
>    levelDescriptor: { id: 'iconGuide.levelDescriptor', defaultMessage: 'levelDescriptor' },
```suggestion
  levelDescriptor: { id: 'iconGuide.levelDescriptor', defaultMessage: 'Section Defaults' },
```

2021-07-21 14:30 UTC, rart approved these changes

2021-07-21 14:34 UTC, merged