[4854] Add RTE config to page builder
craftercms/studio-ui pull request #2453
Opened 2021-07-21 23:50 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4854

2021-07-22 12:31 UTC, rart commented on ui/guest/src/store/epics/root.ts
> +        const rteConfig = action.payload.rteConfig;
What's the ts-ignore needed for?

2021-07-22 12:31 UTC, rart commented on ui/guest/src/react/Guest.tsx
> +            dispatch({ type: type, payload: { event, record, rteConfig } });
No need to send config here as the RTE config is already in the state.
No need for the const above either once this is removed.

2021-07-22 17:00 UTC, jvega190 commented on ui/guest/src/store/epics/root.ts
> +        const rteConfig = action.payload.rteConfig;
not needed anymore, removing

2021-07-22 18:51 UTC, rart commented on ui/guest/src/controls/rte.ts
> +    ...rteConfig
We must make sure that certain props prevail — like setup and possibly other important behavioural props — hence they must be after the `...rteConfig` statement

2021-07-29 20:30 UTC, rart requested changes

2021-07-29 20:30 UTC, rart commented on ui/guest/src/controls/rte.ts
> +    inline: false,
Don't think this makes sense? This is backwards.

2021-07-29 20:30 UTC, rart commented on ui/guest/src/controls/rte.ts
> +    // No file picker is set by default, and functions are not supported in state.
```suggestion
    // No file picker is set by default, and functions are not supported in config file.
```

2021-07-29 20:30 UTC, rart commented on ui/guest/src/controls/rte.ts
> +  window.tinymce.init(settings);
What is settings var useful for? Why not leave with the single line init i.e. `init({ ourNonOverridableSettings, ...rteConfig, ourNonOverridableSettings })`?

2021-07-30 03:32 UTC, jvega190 commented
@rart changing to draft PR to wait for https://github.com/craftercms/studio-ui/pull/2458 to be merged so this can be updated

2021-07-30 23:27 UTC, jvega190 commented on ui/app/src/modules/Preview/PreviewConcierge.tsx
> +              payload: { editMode: false, highlightMode, rteConfig: rteConfig.pageBuilder ?? {} }
I added this for the pageBuilder rte to read a setup with id `pageBuilder`, is that ok? or should this one read base?

2021-09-09 16:50 UTC, rart requested changes

2021-09-09 16:50 UTC, rart commented on ui/app/src/modules/Preview/PreviewConcierge.tsx
> +              payload: { editMode: false, highlightMode, rteConfig: rteConfig ?? {}, site: siteId }
- We must resend rte config if it changes.
- Why are you sending the siteId now?

2021-09-09 16:50 UTC, rart commented on ui/guest/src/controls/rte.ts
> +  rteConfig?: LookupTable<any>,
You have enough information to create a proper type for rteConfig

2021-09-09 16:50 UTC, rart commented on ui/guest/src/controls/rte.ts
> +  }
Expanding the `{site}` expression should be done at the reducer when parsing the config.
```suggestion
  const external = {
    ...rteConfig?.tinymceOptions?.external_plugins,
    acecode: '/studio/static-assets/js/tinymce-plugins/ace/plugin.min.js',
    editform: '/studio/static-assets/js/tinymce-plugins/editform/plugin.js'
  };
```

2021-09-09 16:50 UTC, rart commented on ui/guest/src/store/epics/root.ts
> +                return initTinyMCE(record, validations, state.rteConfig[setupId], state.activeSite);
if setup is not defined, should use whatever is available

2021-09-09 16:50 UTC, rart commented on ui/guest/src/store/models/GuestStore.ts
> +  rteConfig: LookupTable<any>;
type

2021-09-10 12:27 UTC, rart requested changes

2021-09-10 12:27 UTC, rart commented on ui/app/src/modules/Preview/PreviewConcierge.tsx
> +    getHostToGuestBus().next({ type: UPDATE_RTE_CONFIG, payload: { rteConfig } });
```suggestion
  if (rteConfig)
    getHostToGuestBus().next({ type: UPDATE_RTE_CONFIG, payload: { rteConfig } });
```

2021-09-10 14:53 UTC, rart approved these changes

2021-09-10 15:11 UTC, merged