[studio-ui] Path Navigator updating local storage restore logic
craftercms/studio-ui pull request #2503
Opened 2021-08-19 18:25 UTC by aachavarria

### Ticket reference or full description of what's in the PR

2021-08-19 21:12 UTC, rart commented on ui/app/src/state/epics/pathNavigator.ts
> +      )
```suggestion
      map(
        ([
          {
            payload: { id, excludes }
          },
          state
        ]) => {
          return of(
            pathNavigatorFetchParentItems({
              id,
              path: state.pathNavigator[id].currentPath,
              offset: state.pathNavigator[id].offset,
              keyword: state.pathNavigator[id].keyword,
              excludes: excludes,
              limit: state.pathNavigator[id].limit
            })
          );
        }
      )
```

2021-08-19 21:13 UTC, rart commented on ui/app/src/state/epics/pathNavigator.ts
> +import { forkJoin, of } from 'rxjs';
```suggestion
import { forkJoin } from 'rxjs';
```

2021-08-19 21:13 UTC, rart requested changes
Comments above

2021-08-20 15:53 UTC, rart approved these changes

2021-08-20 15:55 UTC, sumerjabri commented
@aachavarria conflict, please fix.

2021-08-20 17:31 UTC, rart approved these changes

2021-08-20 18:13 UTC, merged