Update dependencies - #270E
craftercms/studio-ui pull request #2513
Opened 2021-08-24 01:32 UTC by jvega190

https://github.com/craftersoftware/craftercms/issues/270

2021-08-24 01:33 UTC, jvega190 commented
@rart I need to discuss about material-ui/pickers lib that is deprecated and causing warnings

2021-08-24 17:05 UTC, jvega190 commented
As we discussed, material-ui/pickers can't be updated yet so this is a pending update to work on

2021-08-24 23:50 UTC, rart requested changes

2021-08-24 23:50 UTC, rart commented on ui/app/src/components/CommitResolutionDialog/CommitResolutionDialog.tsx
> +  };
The idea was that the hook returns the handler directly; why not send these arguments directly to the hook?

2021-08-24 23:50 UTC, rart commented on ui/app/src/components/ItemStatesManagement/ItemStatesManagement.tsx
> +            className={!embedded ? classes.filterButton : ''}
```suggestion
            className={embedded ? '' : classes.filterButton}
```
just for fun & clarity

2021-08-24 23:50 UTC, rart commented on ui/app/src/utils/hooks/useOnClose.ts
> +    onClose?.();
Should propagate arguments received by the original event.

2021-08-25 21:46 UTC, rart commented on ui/app/src/utils/hooks/useOnClose.ts
> +  onClose?(event: {}, reason: 'backdropClick' | 'escapeKeyDown'): void;
This isn't the right type. Even any is preferable here.
```suggestion
  onClose?(event: any, reason: 'backdropClick' | 'escapeKeyDown'): void;
```

2021-08-25 21:46 UTC, rart approved these changes

2021-08-26 01:40 UTC, merged