[4124][3.1.x] Bulk upload dialog becomes unresponsive with large volume of files
craftercms/studio-ui pull request #2552
Opened 2021-09-15 23:16 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4124

2021-09-21 20:32 UTC, rart requested changes

2021-09-21 20:32 UTC, rart commented on ui/app/src/components/BulkUpload.tsx
> +    defaultMessage: 'Max active uploads reached.'
```suggestion
    defaultMessage: '{maxFiles} maximum active uploads reached. Excess has been discarded.'
```

2021-09-21 20:32 UTC, rart commented on ui/app/src/components/BulkUpload.tsx
> +    defaultMessage: 'Max active uploads reached.'
Also update 4

2021-09-21 20:32 UTC, rart commented on ui/app/src/components/BulkUpload.tsx
> +              &nbsp; (
Double check this. Pretty sure this will show the text.
```
              &nbsp; (
```

2021-09-22 18:55 UTC, jvega190 commented on ui/app/src/components/BulkUpload.tsx
> +              &nbsp; (
It works, but I changed it to be a span with styles for the spacing

2021-09-22 18:56 UTC, jvega190 commented on ui/app/src/components/BulkUpload.tsx
> +    defaultMessage: 'Max active uploads reached.'
Updated, the maxFiles parameter in the translation was already being sent (forgot to remove before) so it doesn't need to be added (in 3.1)

2021-09-22 19:13 UTC, rart approved these changes

2021-09-23 19:58 UTC, sumerjabri commented
@russdanner do we want this in 3.1.18 or hold off to reduce risk?

2021-09-27 18:43 UTC, merged