[4854] - Add RTE config to page builder - Do not show full rte-text-editing in plain text controls
craftercms/studio-ui pull request #2558
Opened 2021-09-21 15:49 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4854

2021-09-21 20:03 UTC, rart requested changes

2021-09-21 20:03 UTC, rart commented on ui/guest/src/store/epics/root.ts
> +                return initTinyMCE(record, validations, type === 'html' ? setup : {});
This is not good enough. The point is that it's plain text. We need a toolbar that reflects that (or no toolbar at all).
With the default setup there's still stuff that doesn't apply:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/3928341/134239764-51d0b0f4-22a5-4486-8a11-85a7f22fa140.png">

2021-09-22 18:26 UTC, jvega190 commented on ui/guest/src/store/epics/root.ts
> +                return initTinyMCE(record, validations, type === 'html' ? setup : {});
Per discussion, I tested on a clean installation and it works properly. The issue where the label of the 'Hero Title' field is not showing `(Rich Text)` is due to a `@label` attribute set on the field (in the bp). I'll remove it from the repo.

2021-09-22 18:30 UTC, jvega190 commented on ui/guest/src/store/epics/root.ts
> +                return initTinyMCE(record, validations, type === 'html' ? setup : {});
done in here https://github.com/craftercms/studio/pull/2747

2021-09-22 22:31 UTC, rart approved these changes

2021-09-23 17:32 UTC, merged