[4994] Add ability to set site image in site edit dialog
craftercms/studio-ui pull request #2572
Opened 2021-09-27 23:10 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4994

2021-09-27 23:13 UTC, rart commented on ui/app/src/components/EditSiteDialog/EditSiteDialogUI.tsx
> +import Tooltip from '@material-ui/core/Tooltip/Tooltip';
```suggestion
import Tooltip from '@material-ui/core/Tooltip';
```

2021-10-05 09:00 UTC, rart commented on ui/app/src/components/SingleFileUploadDialog/SingleFileUploadDialog.tsx
> +import Dialog from '@mui/material/Dialog';
Use EnhancedDialog and handle isSubmitting, hasPendingChanges, etc

2021-10-05 09:00 UTC, rart commented on ui/app/src/components/SingleFileUploadDialog/SingleFileUploadDialogContainer.tsx
> +      />
Header is part of the EnhacedDialog

2021-10-07 07:20 UTC, rart requested changes
Make sure it all builds and there aren't **any** compilation warnings (browser and terminal)

2021-10-07 07:20 UTC, rart commented on static-assets/components/cstudio-common/common-api.js
> +        });
We only need one event, really. Try something like this...
```ts
        const eventId = 'uploadAsset.event.singleFileUploadDialog';
        CrafterCMSNext.system.store.dispatch({
          type: 'SHOW_SINGLE_FILE_UPLOAD_DIALOG',
          payload: {
            ...
            onUploadComplete: {
              ...
                {
                  type: 'DISPATCH_DOM_EVENT',
                  payload: { id: eventId, type: 'uploadComplete' }
                },
                ...
            },
            onClosed: {
               ...
                {
                  type: 'DISPATCH_DOM_EVENT',
                  payload: { id: eventId, type: 'dialogClosed' }
                },
               ...
          }
        });

        CrafterCMSNext.createLegacyCallbackListener(eventIdClosed, (result) => {
          if (result.type === 'uploadComplete') {
            let uploaded = result.successful[0];
            if (!uploaded.fileExtension) {
              uploaded.fileExtension = uploaded.extension;
            }
            if (!uploaded.fileName) {
              uploaded.fileName = uploaded.name;
            }
            uploadCb.success(uploaded);
          }
        });

```

2021-10-07 07:20 UTC, rart commented on ui/app/src/components/Controls/SingleFileUpload.tsx
> +  uppy.on('file-added', (file: UppyFile) => {
Non of these should be outside an effect

2021-10-07 07:20 UTC, rart commented on ui/app/src/components/EditSiteDialog/EditSiteDialogContainer.tsx
>  export function EditSiteDialogContainer(props: EditSiteDialogContainerProps) {
```suggestion
export function EditSiteDialogContainer(props: EditSiteDialogContainerProps) {
  const siteImagePath = `/.crafter/screenshots/default.png?crafterSite=`;
```

2021-10-07 07:20 UTC, rart commented on ui/app/src/components/EditSiteDialog/EditSiteDialogContainer.tsx
> +  document.addEventListener(idEditSiteImageComplete, editSiteImageCompleteCallback, false);
Why not use `createLegacyCallbackListener(...)`

2021-10-07 07:20 UTC, rart commented on ui/app/src/components/EditSiteDialog/styles.ts
> +      height: '234px'
add object fit

2021-10-07 07:20 UTC, rart commented on ui/app/src/components/EditSiteDialog/EditSiteDialogContainer.tsx
> +  const [siteImage, setSiteImage] = useState(`${siteImagePath}${site.id}`);
make sure the fallback is in place. just like the sites grid, when there's no pic, it should show the fallback.

2021-10-07 07:20 UTC, rart commented on ui/app/src/components/SingleFileUploadDialog/utils.ts
> +export interface SingleFileUploadDialogContainerProps extends SingleFileUploadDialogProps {}
This could be cleaner. Buch of props in this interface are not used by the container.

2021-10-07 07:20 UTC, rart commented on ui/app/src/components/SingleFileUploadDialog/utils.ts
> +export interface SingleFileUploadDialogUIProps extends SingleFileUploadDialogProps {}
Same as above.

2021-10-07 07:20 UTC, rart commented on ui/app/src/components/SingleFileUploadDialog/SingleFileUploadDialog.tsx
> +        onClose={onClose}
Clean the interfaces, destruct the container props and spread rest into the EnhancedDialog

2021-10-07 07:20 UTC, rart commented on ui/app/src/components/SitesGrid/SiteCard.tsx
> +            image={`/.crafter/screenshots/default.png?crafterSite=${site.id}&v=${Date.now()}`}
We agreed on using some sort of count/state. This forces re-painting image on every render.

2021-10-07 07:20 UTC, rart commented on ui/app/src/state/actions/dialogs.ts
> +  'CLOSE_SINGLE_FILE_UPLOAD_DIALOG'
There's an epic that listens from pretty much all `close.*Dialog`. You need to add this event to that epic's `ofType()`

2021-10-07 15:26 UTC, jvega190 commented on ui/app/src/components/EditSiteDialog/styles.ts
> +      height: '234px'
right now it's using the default media style `object-fit: cover`

2021-10-08 23:03 UTC, rart requested changes

2021-10-08 23:03 UTC, rart commented on ui/app/src/components/Controls/SingleFileUpload.tsx
> +  }, [onError, uppy]);
All these effects are lacking destruction. Should unsubscribe from all these events in the cleanup phase

2021-10-08 23:03 UTC, rart commented on ui/app/src/components/EditSiteDialog/EditSiteDialog.tsx
> +        onUploadComplete={onUploadComplete}
Should rename to on site image change

2021-10-08 23:03 UTC, rart commented on ui/app/src/components/SitesGrid/SiteCard.tsx
> +  const siteImage = useMemo(
this guy should just receive the image and not have such rendering logic

2021-10-08 23:03 UTC, rart commented on ui/app/src/components/SitesManagement/SitesManagement.tsx
> +        onUploadComplete: dispatchDOMEvent({
event needs to be also onclose to unsubscribe if close without upload

2021-10-12 16:20 UTC, rart requested changes

2021-10-12 16:20 UTC, rart commented on ui/app/src/components/EditSiteDialog/EditSiteDialogContainer.tsx
> +  const [siteImage, setSiteImage] = useState(`${siteImagePath}${site.id}`);
this isn't needed any more, is it?

2021-10-12 16:20 UTC, rart commented on ui/app/src/components/EditSiteDialog/EditSiteDialogContainer.tsx
> +    setSiteImage(`${siteImagePath}${site.id}&v=${siteImageCounter + 1}`);
x

2021-10-12 16:20 UTC, rart commented on ui/app/src/components/EditSiteDialog/EditSiteDialogContainer.tsx
> +  const siteImagePath = `/.crafter/screenshots/default.png?crafterSite=`;
x

2021-10-12 16:20 UTC, rart commented on ui/app/src/components/EditSiteDialog/EditSiteDialogContainer.tsx
> +        siteImage={siteImage}
here, you would compose site.img+v

2021-10-12 16:20 UTC, rart commented on ui/app/src/components/SitesManagement/SitesManagement.tsx
> +        });
```suggestion
        setSitesRefreshCountLookup({
          [site.id]: (sitesRefreshCountLookup[site.id] ?? 0) + 1
        });
```

2021-10-12 16:20 UTC, rart commented on ui/app/src/components/SitesManagement/SitesManagement.tsx
> +      }
```suggestion
      }
```

2021-10-12 16:20 UTC, rart commented on ui/app/src/components/SitesManagement/SitesManagement.tsx
> +    const unsubscribe = createCustomDocumentEventListener(eventId, ({ type }) => {
```suggestion
    createCustomDocumentEventListener(eventId, ({ type }) => {
```

2021-10-13 14:05 UTC, rart requested changes

2021-10-13 14:05 UTC, rart commented on ui/app/src/components/EditSiteDialog/EditSiteDialogContainer.tsx
> +      update({ id, name, description, imageUrl: site.imageUrl }).subscribe(
Must think things through here... The correct thing was to fix the type on the service, not patch here when the image is never updated on that service. The compiler is there to help, don't just try to shut it up.
```suggestion
      update({ id, name, description }).subscribe(
```

2021-10-13 14:06 UTC, rart approved these changes

2021-10-13 14:52 UTC, merged