Add transition none style to Popper to avoid unwanted possible transitions set by sites #5098
craftercms/studio-ui pull request #2665
Opened 2021-11-12 23:15 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5098

2021-11-15 08:15 UTC, rart commented
Please explain

2021-11-15 15:08 UTC, jvega190 commented
@rart if there's a transition style set to a `role="tooltip"` element, it will apply to our `ZoneMarkers`, which I don't think we want. For example look at https://www.loom.com/share/5dfcb828862448ebb5305fee56f6b244

2021-11-15 16:04 UTC, rart requested changes

2021-11-15 16:04 UTC, rart commented on ui/guest/src/react/ZoneMarker.tsx
> +          }}
Add it to the sx and type it appropriately.

2021-11-16 10:42 UTC, rart approved these changes
@jvega190 popper does have a transition prop. does that not serve the purpose?

2021-11-16 10:42 UTC, rart approved these changes

2021-11-16 13:31 UTC, merged