[5075] Remember user-preference for save button sub-action
craftercms/studio-ui pull request #2694
Opened 2021-11-24 21:45 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5075

2021-11-25 12:53 UTC, rart requested changes
- Create a MultiChoiceSaveButton
  - Internally it uses SplitButton
  - This component should contain all the common save options and use props to turn them on/off
    - The `options` prop would be of type `Array<CommonSaveOptions | SplitButtonOption>`
      - By default, it has all the options
      - `type CommonSaveOptions = 'save' | 'saveAndClose' | etc...`
    -  The new button receives a single click handler of type `(e: event, type: CommonSaveOptions | T) => void`
      - e.g. `<MultiChoiceSaveButton onClick={(e, type) => ...} />` would have only but "save and save & close" options.
    - Also add a `additionalOptions` optional prop
- Move the preference storing/retrieving to SplitButton
  - The split button should have a `storageKey` prop which it checks to retrieve when it mounts and store when it changes. If no storage key is present, the button works without any storage (should not save to local storage).
  - Add `id` to `SplitButtonProps['options']` and use this as the selected option driver
  - `defaultSelected` too becomes of type string and it's default value would be `options[0].id`
  - If retrieving a storageKey produces a key that's not present on the option set, the key should be removed and fallback to `options[0]`.
  - Partition it all into SplitButton & SplitButtonUI
    - All logic and state goes to SplitButton
- Find any usages of SplitButton on the LegacyCode to make sure the new component is used with it's rightful options

2021-12-03 06:05 UTC, rart requested changes

2021-12-03 06:05 UTC, rart commented on static-assets/components/cstudio-forms/forms-engine.js
> +                const storedId = type.previewable ? 'formEditorPreviewable' : 'formEditorNotPreviewable';
Let’s remove the save & preview option all together (everywhere)

2021-12-03 06:05 UTC, rart commented on static-assets/components/cstudio-forms/template-editor.js
Where is the legacy editor still being used ?

2021-12-03 06:05 UTC, rart commented on ui/app/src/components/MultiChoiceSaveButton/MultiChoiceSaveButton.tsx
> +    id: 'codeEditor.saveAndMinimize',
rename these ids

2021-12-03 06:05 UTC, rart commented on ui/app/src/utils/state.ts
> +export function setStoredSaveButtonSubAction(user: string, id: string, value: string) {
```suggestion
export function setStoredSaveButtonSubAction(user: string, id: string, value: string): void {
```

2021-12-03 20:46 UTC, jvega190 commented on static-assets/components/cstudio-forms/template-editor.js
There are some parts where it's being used but seems like dead code. I'll revert the changes. Should I create a ticket to remove template-editor.js and dead usages?

2021-12-04 16:33 UTC, rart commented on static-assets/components/cstudio-forms/template-editor.js
yes

2021-12-05 21:10 UTC, rart requested changes
Let's discuss.

2021-12-05 21:10 UTC, rart commented on ui/app/src/components/SiteToolsApp/SiteToolsApp.tsx
> +                  configuration: { isContainerDialog: hideSidebarSiteSwitcher }
👆🏻

2021-12-05 21:10 UTC, rart commented on ui/app/src/components/ContentTypesManagement/ContentTypesManagement.tsx
> +  configuration?: LookupTable;
👆🏻

2021-12-05 21:10 UTC, rart commented on ui/app/src/components/ContentTypesManagement/ContentTypesManagement.tsx
> +            }
👆🏻

2021-12-05 21:10 UTC, rart commented on ui/app/src/components/WidgetDialog/utils.ts
> +  configuration?: LookupTable;
👆🏻

2021-12-07 18:01 UTC, jvega190 commented on static-assets/components/cstudio-forms/template-editor.js
ticket created https://github.com/craftercms/craftercms/issues/5138

2021-12-08 11:52 UTC, rart requested changes

2021-12-08 11:52 UTC, rart commented on static-assets/components/cstudio-forms/forms-engine.js
> +            const user = CStudioAuthoringContext.user;
I don't see this being used.

2021-12-08 11:52 UTC, rart commented on ui/app/src/components/ContentTypesManagement/ContentTypesManagement.tsx
> +                }
If the saveAndClose is available and an onClose function is sent, no reason not to call it independently of whether it is embedded or not.
```suggestion
                onClose?.();
```

2021-12-08 11:52 UTC, rart commented on ui/app/src/components/SiteToolsApp/SiteToolsApp.tsx
> +                  configuration: { isContainerDialog: hideSidebarSiteSwitcher },
👆🏻???

2021-12-08 11:52 UTC, rart commented on ui/app/src/components/SiteToolsApp/SiteToolsApp.tsx
> +                  ...(hideSidebarSiteSwitcher && {
Why is on minimize conditional to hideSidebarSiteSwitcher?

2021-12-09 11:19 UTC, rart requested changes

2021-12-09 11:19 UTC, rart commented on ui/app/src/components/SiteToolsApp/UrlDrivenSiteTools.tsx
> +      urlDriven={true}
```suggestion
      urlDriven
```

2021-12-09 11:19 UTC, rart commented on ui/app/src/components/ToolsPanelEmbeddedAppViewButton/ToolsPanelEmbeddedAppViewButton.tsx
> +  const isWidgetEmbedded = props.widget?.configuration?.embedded;
This component has no business reading the internals of widgets and their config.

2021-12-09 11:19 UTC, rart commented on ui/app/src/components/ToolsPanelEmbeddedAppViewButton/ToolsPanelEmbeddedAppViewButton.tsx
> +          ...(isWidgetEmbedded && { onClose })
What's the problem with simply providing the onClose?

2021-12-09 11:19 UTC, rart commented on ui/app/src/components/SiteToolsApp/SiteToolsApp.tsx
> +  urlDriven?: boolean;
```suggestion
  // Whether the component is mounted on a dialog or it's the main app on a page (i.e. `/studio/site-tools`)
  mountMode?: 'dialog' | 'page';
```

2021-12-09 11:19 UTC, rart commented on ui/app/src/components/ContentTypesManagement/ContentTypesManagement.tsx
> +  urlDriven?: boolean;
use mountMode all across

2021-12-10 15:19 UTC, rart requested changes

2021-12-10 15:19 UTC, rart commented on static-assets/components/cstudio-admin/base.js
> +        }
```suggestion
        if (mountMode === 'dialog') {
          options.push('saveAndMinimize');
        }
```

2021-12-10 15:19 UTC, rart commented on ui/app/src/components/ContentTypesManagement/ContentTypesManagement.tsx
> +  mountMode?: boolean;
mountMode is not a boolean 🤦🏻‍♂️

2021-12-10 15:19 UTC, rart commented on ui/app/src/components/SiteToolsApp/SiteToolsApp.tsx
> +                  }
Could we send this in from the parent component so we don't couple SiteToolsApp to redux?

2021-12-10 15:50 UTC, jvega190 commented
@rart since this ticket is rc2, should I change the PR to be a draft?

2022-01-11 14:15 UTC, rart commented on ui/app/src/components/ContentTypesManagement/ContentTypesManagement.tsx
> +        path={`/legacy-site-config?mode=embedded${mountMode ? '&mountMode=' + mountMode : ''}#tool/content-types`}
```suggestion
        path={`/legacy-site-config?mode=embedded${mountMode ? `&mountMode=${mountMode}` : ''}#tool/content-types`}
```

2022-01-11 14:16 UTC, rart approved these changes

2022-01-11 15:28 UTC, merged