[5096] Browse no longer supports upload
craftercms/studio-ui pull request #2697
Opened 2021-11-26 01:24 UTC by aachavarria

https://github.com/craftercms/craftercms/issues/5096

2021-12-06 14:07 UTC, rart requested changes
Let's remove the right click and context menu and leave the refresh and upload buttons at the top left of the items area. Search field on the right, smaller than it is now.

2021-12-06 14:07 UTC, rart commented on ui/app/src/components/BrowseFilesDialog/BrowseFilesDialogContainer.tsx
> +    console.log(element);
x

2021-12-06 14:07 UTC, rart commented on ui/app/src/components/FolderBrowserTreeView/RenderTreeNode.tsx
> +        <div role="button" data-path={node.id} onClick={(e) => onLabelClick?.(e, node)}>
What is the attribute for? Used where?

2021-12-07 14:28 UTC, aachavarria commented on ui/app/src/components/FolderBrowserTreeView/RenderTreeNode.tsx
> +        <div role="button" data-path={node.id} onClick={(e) => onLabelClick?.(e, node)}>
this attribute is the path. it is used to open the upload dialog in the selected path

2021-12-08 11:48 UTC, rart approved these changes

2021-12-08 15:03 UTC, merged