[5131] Site Explorer: pagination is not working
craftercms/studio-ui pull request #2710
Opened 2021-12-07 19:55 UTC by aachavarria

https://github.com/craftercms/craftercms/issues/5131

2021-12-09 11:06 UTC, rart requested changes

2021-12-09 11:06 UTC, rart commented on ui/app/src/components/PathNavigator/PathNavigator.tsx
> +  const dispatch = useDispatch();@ro
`@ro`? 👆 

Test your build!

2021-12-09 11:06 UTC, rart commented on ui/app/src/state/epics/pathNavigator.ts
> +            offset: offset
- Change doesn't seem to have a point. Revert?

2021-12-09 11:06 UTC, rart commented on ui/app/src/state/epics/pathNavigator.ts
>              limit: state.pathNavigator[id].limit,
You're not retrieving the limit from the action's payload but the offset is. Please double check.

2021-12-09 11:06 UTC, rart commented on ui/app/src/state/reducers/pathNavigator.ts
> +    }),
You're also sending offset on the action, shouldn't that be updated too?

2021-12-09 14:51 UTC, aachavarria commented on ui/app/src/components/PathNavigator/PathNavigator.tsx
> +  const dispatch = useDispatch();@ro
I did not send the fix, it was on my commits

2021-12-09 14:52 UTC, aachavarria commented on ui/app/src/state/reducers/pathNavigator.ts
> +    }),
no, the offset is being updated on the complete

2021-12-10 15:23 UTC, rart approved these changes

2021-12-10 15:30 UTC, merged