[next] Add option to file-name control to remove accent/diacritics
craftercms/studio-ui pull request #2750
Opened 2022-01-11 07:48 UTC by phuongnq

### Ticket reference or full description of what's in the PR
An option to replace accent/diacritics to English characters from file-name control.
Ex:
Original string: à la carte, pied-à-terre, or crème
Transform string: a-la-carte--pied-a-terre--or-creme
![2022-01-11_14-44](https://user-images.githubusercontent.com/2996543/148901791-24a59f51-4781-4399-8a0a-344b892b19b3.png)
![2022-01-11_14-44_1](https://user-images.githubusercontent.com/2996543/148901795-145246d0-4742-4560-b63f-f87e3a0678ef.png)

2022-01-11 15:28 UTC, sumerjabri requested changes
Please see the comments on the support/3.1.x PR

2022-01-13 07:08 UTC, rart requested changes

2022-01-13 07:08 UTC, rart commented on static-assets/components/cstudio-common/resources/de/base.js
> +  replaceAccent: 'Convert accent/diacritics to latin characters',
```suggestion
  replaceAccent: 'Konvertieren Sie Akzente/diakritische Zeichen in lateinische Zeichen',
```

2022-01-13 07:08 UTC, rart commented on static-assets/components/cstudio-common/resources/de/base.js
> +  allowEditWithoutWarning: 'Allow Edit Without Warning',
```suggestion
  allowEditWithoutWarning: 'Bearbeiten ohne Warnung zulassen',
```

2022-01-13 07:08 UTC, rart commented on static-assets/components/cstudio-common/resources/es/base.js
> +  allowEditWithoutWarning: 'Allow Edit Without Warning',
```suggestion
  allowEditWithoutWarning: 'Permitir edición sin advertencia',
```

2022-01-13 07:08 UTC, rart commented on static-assets/components/cstudio-common/resources/es/base.js
> +  replaceAccent: 'Convert accent/diacritics to latin characters',
```suggestion
  replaceAccent: 'Convertir acentos/diacríticos en caracteres latinos',
```

2022-01-13 07:08 UTC, rart commented on static-assets/components/cstudio-common/resources/kr/base.js
> +  allowEditWithoutWarning: 'Allow Edit Without Warning',
```suggestion
  allowEditWithoutWarning: '경고 없이 편집 허용',
```

2022-01-13 07:08 UTC, rart commented on static-assets/components/cstudio-common/resources/kr/base.js
> +  replaceAccent: 'Convert accent/diacritics to latin characters',
```suggestion
  replaceAccent: '악센트/분음 부호를 라틴 문자로 변환',
```

2022-01-13 07:10 UTC, rart approved these changes

2022-01-13 15:05 UTC, sumerjabri requested changes
See comments in 3.1.x PR.

2022-01-13 19:38 UTC, rart commented
Requirements were updated. Closing in favour of https://github.com/craftercms/studio-ui/pull/2761

2022-01-13 19:38 UTC, closed without merging