[5287] Code editor doesn't focus on the edit panel
craftercms/studio-ui pull request #2819
Opened 2022-02-07 18:05 UTC by aachavarria

https://github.com/craftercms/craftercms/issues/5287

### Ticket reference or full description of what's in the PR

2022-02-08 19:30 UTC, rart reviewed
PRs got mixed. Please remove the LogConsole work from this PR.

2022-02-09 15:41 UTC, rart requested changes
Let's try adding a `default` background to the editor when in readonly; make it more distinct from the editable editor

2022-02-09 15:41 UTC, rart commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +            autoFocus
1. What happens to this flag when opening readonly?
2. When you go from ready only to edit, does the autoFocus pick up?

2022-02-09 15:48 UTC, aachavarria commented on ui/app/src/components/CodeEditorDialog/CodeEditorDialogContainer.tsx
> +            autoFocus
1 and 2>  Readonly does not uses the codeEditorDialog, it uses Preview Dialog, to this autofocus only applies to edit

2022-02-10 08:37 UTC, rart approved these changes

2022-02-10 14:31 UTC, merged