[5357] Duplicating a featured item in Editorial BP for the first time, causes issues with XB
craftercms/studio-ui pull request #2872
Opened 2022-03-07 22:33 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5357

2022-03-09 15:51 UTC, rart requested changes

2022-03-09 15:51 UTC, rart commented on ui/app/src/services/content.ts
> +      let elementToDuplicate = doc.documentElement;
Rename appropriately

2022-03-09 15:51 UTC, rart commented on ui/app/src/services/content.ts
> +        const item: Element = extractNode(elementToDuplicate, fieldId, targetIndex).cloneNode(true) as Element;
Duplicate line

2022-03-09 15:51 UTC, rart commented on ui/app/src/services/content.ts
> +        const item: Element = extractNode(elementToDuplicate, fieldId, targetIndex).cloneNode(true) as Element;
Duplicate line

2022-03-09 15:51 UTC, rart commented on ui/app/src/services/content.ts
> +        updateModifiedDateElement(elementToDuplicate);
Check if this can be refactored above (common to both flows)

2022-03-09 15:51 UTC, rart commented on ui/app/src/services/content.ts
> +        updateModifiedDateElement(elementToDuplicate);
Check if this can be refactored above (common to both flows)

2022-03-09 18:12 UTC, jvega190 commented
@rart I also updated the code to update embedded components ids inside the item being duplicated

2022-03-11 11:34 UTC, rart requested changes

2022-03-11 11:34 UTC, rart commented on ui/app/src/services/content.ts
> +      let elementToDuplicate = doc.documentElement;
Rename appropriately

2022-03-11 11:34 UTC, rart commented on ui/app/src/modules/Preview/PreviewConcierge.tsx
> +            .pipe(switchMap(({ newItem }) => fetchContentInstanceDescriptor(siteId, newItem.path, { flatten: true })))
I think we need to do a little bit more here. See `issueDescriptorRequest`. Perhaps we can even invoke that one.

2022-03-11 11:34 UTC, rart commented on ui/guest/src/contentController.ts
> +    });
I think If we manage to use `issueDescriptorRequest` we won't need this.

2022-03-14 16:25 UTC, rart requested changes

2022-03-14 16:25 UTC, rart commented on ui/guest/src/contentController.ts
> +  duplicateItemOperationComplete,
Not in use

2022-03-14 16:25 UTC, rart commented on ui/guest/src/contentController.ts
> +import { message$ } from './utils/communicator';
Not in use

2022-03-15 09:53 UTC, rart approved these changes

2022-03-15 13:10 UTC, merged