[5064] RTE dialogs - data source issues
craftercms/studio-ui pull request #2908
Opened 2022-04-04 22:44 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5064

2022-04-06 12:55 UTC, rart requested changes

2022-04-06 12:55 UTC, rart commented on ui/app/src/models/ContentType.ts
> +  | 'imgDesktopUpload';
```suggestion
  | 'allowImagesFromRepo'
  | 'allowImageUpload';
```

2022-04-08 00:22 UTC, jvega190 commented on ui/app/src/utils/path.ts
> +      // processedPath = processedPath.replace('{objectId}', CStudioAuthoring.Utils.generateUUID());
@rart need to discuss this utility

2022-04-08 11:40 UTC, rart requested changes

2022-04-08 11:40 UTC, rart commented on static-assets/components/cstudio-common/common-api.js
> -            : CStudioAuthoring.Utils.getQueryParameterByName('parentPath');
All these should become arguments to the new function. Don't read URL there.

2022-04-08 11:40 UTC, rart commented on ui/app/src/components/DataSourcesActionsList/DataSourcesActionsList.tsx
> +        <Dialog
Use `Menu`

2022-04-08 11:40 UTC, rart commented on ui/app/src/components/DataSourcesActionsList/DataSourcesActionsList.tsx
> +              <ListItem key={index} disableGutters>
Use `MenuItem`

2022-04-08 11:40 UTC, rart commented on ui/app/src/state/actions/dialogs.ts
> +// region Rte Picker Action Result
unclosed region

2022-04-08 11:40 UTC, rart commented on ui/app/src/utils/path.ts
> +  const urlParams = new URLSearchParams(window.location.search);
Don't. See above. This function should be pure.

2022-04-08 11:40 UTC, rart commented on ui/app/src/utils/path.ts
> +export function processPathMacros(path: string, model: any | ContentInstance, useUUID?: boolean): string {
```suggestion
export function processPathMacros(dependencies: { define all here }): string {
```

2022-04-08 11:40 UTC, rart commented on ui/app/src/utils/path.ts
> +      // processedPath = processedPath.replace('{objectId}', CStudioAuthoring.Utils.generateUUID());
We have a `uuid` lib. 
```js
import { v4 as uuid } from 'uuid';
id = uuid();
```

2022-04-08 11:40 UTC, rart commented on ui/guest/src/controls/rte.ts
> +          filter((e) => e.type === rtePickerActionResult.type),
Make sure you're sending both ok and cancel actions so this observable dies with either result.

2022-04-08 11:41 UTC, rart commented
Conflicts

2022-04-13 14:19 UTC, rart approved these changes

2022-04-13 14:22 UTC, merged