[5469] Deleting the last item on a page in sidebar doesn't refresh the sidebar
craftercms/studio-ui pull request #2923
Opened 2022-04-08 22:46 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5469

2022-04-09 18:56 UTC, rart requested changes

2022-04-09 18:56 UTC, rart commented on ui/app/src/state/reducers/pathNavigator.ts
> +      } else {
First line is not used on the if statement nor in it's body. Move to the else.
```ts
       if (children.offset >= children.limit && children.length === 0) {
         return state;
       } else {
         const path = parent?.path ?? state[id].currentPath;
```

2022-04-09 18:56 UTC, rart commented on ui/app/src/state/reducers/pathNavigator.ts
> +      if (children.offset >= children.limit && children.length === 0) {
What is this trying to accomplish? Add comment/description.
When/why does this happen?

2022-04-12 15:21 UTC, jvega190 commented on ui/app/src/state/reducers/pathNavigator.ts
> +      if (children.offset >= children.limit && children.length === 0) {
Comment added according to our conversation

2022-04-12 20:04 UTC, rart approved these changes

2022-04-12 21:18 UTC, merged