[5569] Add option to image picker to disallow upload of SVG
craftercms/studio-ui pull request #3014
Opened 2022-05-26 22:23 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5569

2022-05-27 17:37 UTC, rart requested changes

2022-05-27 17:37 UTC, rart commented on static-assets/components/cstudio-forms/controls/image-picker.js
> +      { label: CMgs.format(langBundle, 'allowSVG'), name: 'allowSVG', type: 'boolean', defaultValue: 'true' }
Disallow by default. Should the defaultValue here be a string or a boolean?
```suggestion
      { label: CMgs.format(langBundle, 'allowSVG'), name: 'allowSVG', type: 'boolean', defaultValue: 'false' }
```

2022-05-27 23:00 UTC, jvega190 commented on static-assets/components/cstudio-forms/controls/image-picker.js
> +      { label: CMgs.format(langBundle, 'allowSVG'), name: 'allowSVG', type: 'boolean', defaultValue: 'true' }
Even though the value is type boolean it is set as a string and the content-type engine handles/parses it as a boolean

2022-05-30 17:10 UTC, rart approved these changes

2022-05-30 19:03 UTC, merged