[4077] Add publisher review workflow option
craftercms/studio-ui pull request #3015
Opened 2022-05-27 16:51 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4077

2022-05-27 17:33 UTC, rart requested changes

2022-05-27 17:33 UTC, rart commented on ui/app/src/components/PublishDialog/PublishDialogContainer.tsx
> +  const hasPublishPermission = items?.every((item) => item.availableActionsMap.publish);
This runs on every render; `some` would be best: doesn't iterate through the whole array and doesn't return true with an empty array
```suggestion
  const hasPublishPermission = items?.some((item) => !item.availableActionsMap.publish);
```

2022-05-27 22:56 UTC, jvega190 commented on ui/app/src/components/PublishDialog/PublishDialogContainer.tsx
> +  const hasPublishPermission = items?.every((item) => item.availableActionsMap.publish);
It should be with a `!` at he beggining: `!items?.some((item) => !item.availableActionsMap.publish)` (if there are some items without publish permission => negate to get if it has publish permission)

2022-05-30 17:09 UTC, rart approved these changes

2022-05-30 19:03 UTC, merged