[5610][3.1.x] Update the Pull from Remote dialog
craftercms/studio-ui pull request #3016
Opened 2022-05-27 23:01 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5610

2022-05-27 23:03 UTC, jvega190 commented
@rart need to discuss the handling of errors of fetch site API

2022-05-31 12:10 UTC, rart requested changes
Let's move all of the sandbox branch retrieval stuff to the PullDialogContainer

2022-05-31 12:10 UTC, rart commented on ui/app/src/services/sites.ts
> +}
```suggestion
export function fetchLegacySite(siteId: string): Observable<LegacySite> {
  return get(`/studio/api/1/services/api/1/site/get.json?site_id=${siteId}`).pipe(pluck('response'));
}
```

2022-05-31 12:13 UTC, rart requested changes

2022-05-31 12:13 UTC, rart commented on ui/app/src/components/GitManagement/PullDialog/PullDialogContainer.tsx
> +const useStyles = makeStyles((theme) =>
Update your code and make sure to use `makeStyles` from `tss-react` and remove `createStyles`.

2022-06-01 13:57 UTC, rart commented on ui/app/src/services/sites.ts
> +}
Changing the function name was not done

2022-06-01 14:15 UTC, rart requested changes

2022-06-01 14:15 UTC, rart commented on ui/app/src/services/sites.ts
> +export function fetchSite(siteId: string): Observable<LegacySite> {
Change name as requested in last review

2022-06-01 14:15 UTC, rart commented on ui/app/src/components/GitManagement/PullDialog/PullDialogContainer.tsx
> +              id="repositories.pullInfo"
```suggestion
              id="repositories.pullFromCreatedBranchOnlyHint"
```

2022-06-01 14:15 UTC, rart commented on ui/app/src/components/GitManagement/PullDialog/PullDialogContainer.tsx
> +                  id="repositories.sandboxBranchError"
```suggestion
                  id="repositories.sandboxBranchRetrievalError"
```

2022-06-01 14:15 UTC, rart commented on ui/app/src/components/GitManagement/PullDialog/PullDialogContainer.tsx
> +  const [sandboxBranchError, setSandboxBranchError] = useState<ApiResponse>(null);
merge these into a _spread state_ and add a loading flag and implement it in the brach display area.

2022-06-01 14:15 UTC, rart commented on ui/app/src/components/GitManagement/PullDialog/PullDialogContainer.tsx
>      }
Is this the only option now? Change the const name and remove the `if`, if so.

2022-06-01 17:08 UTC, rart approved these changes

2022-06-02 16:12 UTC, merged