[5631] Approve a pending publish request failed with a blank page
craftercms/studio-ui pull request #3035
Opened 2022-06-10 16:45 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5631

2022-06-10 16:47 UTC, jvega190 commented
Updated AwaitingForApproval and ApprovedScheduledItems dashlets to do what the RecentActivity dashlet does right now. RecentlyPublish doesn't need the update because there is no selection in that dashlet

2022-06-12 09:06 UTC, rart requested changes

2022-06-12 09:06 UTC, rart commented on ui/app/src/components/LegacySiteDashboard/LegacyApprovedScheduledDashlet/ApprovedScheduledDashlet.tsx
> +  const { itemsByPath } = useDetailedItems(Object.keys(selectedLookup));
Can we get by with SandboxItems here, in all these cases? Detailed items are more expensive.

2022-06-14 10:52 UTC, rart requested changes

2022-06-14 10:52 UTC, rart commented on ui/app/src/state/actions/content.ts
> +export const fetchSandboxItemsComplete = /*#__PURE__*/ createAction<SandboxItem[]>('FETCH_SANDBOX_ITEMS_COMPLETE');
```suggestion
export const fetchSandboxItemsComplete = /*#__PURE__*/ createAction<{ items: SandboxItem[] }>('FETCH_SANDBOX_ITEMS_COMPLETE');
```

2022-06-14 10:52 UTC, rart commented on ui/app/src/state/epics/content.ts
> +          map((items) => fetchSandboxItemsComplete(items as SandboxItem[])),
```suggestion
          map((items) => fetchSandboxItemsComplete({ items })),
```

2022-06-16 06:27 UTC, rart requested changes

2022-06-16 06:27 UTC, rart commented on ui/app/src/state/epics/content.ts
> +import { DetailedItem, SandboxItem } from '../../models';
Doesn't look like SandboxItem is in use. 

(Build & review for warnings always before final push)

2022-06-17 09:47 UTC, rart approved these changes

2022-06-17 13:08 UTC, merged