[5632] Reject dialog not showing
craftercms/studio-ui pull request #3039
Opened 2022-06-14 21:07 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5632

2022-06-16 06:17 UTC, rart requested changes

2022-06-16 06:17 UTC, rart commented on ui/app/src/components/RejectDialog/RejectDialogContainer.tsx
> +      classes={classes}
Classes not used here at all? move to the component that consumes and remove as prop

2022-06-16 16:12 UTC, jvega190 commented on ui/app/src/components/RejectDialog/RejectDialogUI.tsx
> -        <Grid container spacing={3} className={classes.contentRoot}>
contentRoot didn't exist in styles, not needed

2022-06-17 20:10 UTC, rart approved these changes

2022-06-17 20:16 UTC, merged