[5486] Report socket connection issues on the UI via snacks
craftercms/studio-ui pull request #3083
Opened 2022-07-08 22:16 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5486

2022-07-11 15:32 UTC, rart requested changes

2022-07-11 15:32 UTC, rart commented on ui/app/src/state/epics/env.ts
> +          showSystemNotification({
This needs to be persistent until the socket gets back online or otherwise dismissed so this doesn't work

2022-07-11 15:34 UTC, rart requested changes
We should:
- Disconnect the socket when session expires
- Reconnect when session resumes

2022-07-11 15:34 UTC, rart commented on ui/app/src/state/epics/env.ts
> +    defaultMessage: 'Socket connection was interrupted. Studio will continue to retry the connection.'
```suggestion
    defaultMessage: 'Connection with the server was interrupted. Studio will continue to retry the connection.'
```

2022-07-11 18:30 UTC, jvega190 commented on ui/app/src/state/epics/env.ts
> +    defaultMessage: 'Socket connection was interrupted. Studio will continue to retry the connection.'
When the session expires it does disconnect (and shows the snack).

2022-07-11 18:31 UTC, jvega190 commented on ui/app/src/state/epics/auth.ts
> +            ? [messageSharedWorker(openSiteSocket({ site: state.sites.active, xsrfToken: getXSRFToken() }))]
Right now it opening the socket connection on login complete (not only re-login). Should it be only when logging in after a session expiration?

2022-07-12 18:23 UTC, rart requested changes

2022-07-12 18:23 UTC, rart commented on ui/app/src/components/PreviewConcierge/PreviewConcierge.tsx
> +      <Snackbar
Make sure guest & socket snacks don't overlap

2022-07-12 18:23 UTC, rart commented on ui/app/src/components/PreviewConcierge/PreviewConcierge.tsx
> +  useEffect(() => {
Consider session status (should not see socket snack and re-login dialog)

2022-07-12 18:23 UTC, rart commented on ui/app/src/components/PreviewConcierge/PreviewConcierge.tsx
> +      startGuestDetectionTimeout(socketConnectionTimeoutRef, setSocketConnectionSnackbarOpen);
Rename to non-guest specific name

2022-07-12 18:23 UTC, rart commented on ui/app/src/state/epics/auth.ts
> +        ];
```suggestion
        return [
          messageSharedWorker(refreshAuthToken()),
          // This action here assumes this epic is ran only when login from session timeout, not on initial login too
          hasActiveSite &&
            messageSharedWorker(openSiteSocket({ site: state.sites.active, xsrfToken: getXSRFToken() }))
        ].filter(Boolean);
```

2022-07-13 16:02 UTC, rart requested changes

2022-07-13 16:02 UTC, rart commented on ui/app/src/components/PreviewConcierge/PreviewConcierge.tsx
> +  useEffect(() => {
Keep the Snackbar state tied to a single prop: check authActive here.

2022-07-13 16:02 UTC, rart commented on ui/app/src/components/PreviewConcierge/PreviewConcierge.tsx
> +        open={socketConnectionSnackbarOpen && authActive}
See above.

2022-07-14 12:32 UTC, rart approved these changes

2022-07-14 14:35 UTC, merged