[5556] Studio Search and Search Dialogs have Path filter that limits to current path only
craftercms/studio-ui pull request #3087
Opened 2022-07-11 22:33 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5556

2022-07-12 12:54 UTC, rart requested changes

2022-07-12 12:54 UTC, rart commented on ui/app/src/components/SiteSearchPathSelector/PathSelector.tsx
> +      </Paper>
Input should only shown when a base path is selected

2022-07-13 15:59 UTC, rart requested changes

2022-07-13 15:59 UTC, rart commented on ui/app/src/components/SiteSearchPathSelector/PathSelector.tsx
> +    defaultMessage: 'scripts'
```suggestion
    defaultMessage: 'Scripts'
```

2022-07-13 15:59 UTC, rart commented on ui/app/src/components/SiteSearchPathSelector/PathSelector.tsx
> +          <FormControlLabel value="" control={<Radio size="small" />} label="Any path" />
Label lacking i18n

2022-07-13 15:59 UTC, rart commented on ui/app/src/components/SiteSearchPathSelector/PathSelector.tsx
> +        <RadioGroup value={radioBasePath} onChange={handleBasePathChange}>
The value of the base path radio should still be checked when a subpath of his is selected. This won't work.

2022-07-13 18:38 UTC, jvega190 commented on ui/app/src/components/SiteSearchPathSelector/PathSelector.tsx
> +        <RadioGroup value={radioBasePath} onChange={handleBasePathChange}>
it does work, the radioBasePath updates to be the `root` of the path so it matches the radio values, so they're properly checked. (look at comment tag)

2022-07-13 18:39 UTC, jvega190 commented on ui/app/src/components/SiteSearchPathSelector/PathSelector.tsx
> +  const radioBasePath = path.split('/')[1] ? `/${path.split('/')[1]}` : '';
@rart here

2022-07-14 12:30 UTC, rart approved these changes

2022-07-14 14:33 UTC, merged