[5713] Broken component on drag and drop components
craftercms/studio-ui pull request #3115
Opened 2022-08-05 21:54 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5713

2022-08-06 01:45 UTC, rart commented
Either this is the wrong title/description for the PR or branch got mixed up with the react-intl update

2022-08-08 14:49 UTC, jvega190 commented
There was a mix up, fixed name/description of PR

2022-08-10 15:42 UTC, rart requested changes
See notes

2022-08-10 15:42 UTC, rart commented on ui/app/src/state/epics/content.ts
> +                // @ts-ignore - Type '(siteId: string, path: string) => Observable<any>' is not assignable to type 'FormatXMLElementFn<string, string>' Error.
This looks like a legitimate error

2022-08-10 15:42 UTC, rart commented on ui/app/src/components/PublishOnDemandWidget/PublishOnDemandWidget.tsx
> +                {mode === 'studio' ? (
Please test

2022-08-11 17:47 UTC, rart approved these changes

2022-08-11 17:55 UTC, merged