[5733] Renaming items or editing Page URL via UI, returns HTTP 404 on /content/item_by_path call
craftercms/studio-ui pull request #3129
Opened 2022-08-25 16:08 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5733

2022-08-30 11:20 UTC, rart requested changes

2022-08-30 11:20 UTC, rart commented on ui/app/src/components/CreateFolderDialog/CreateFolderContainer.tsx
> +  // if path changes
This comment is a bit confusing. If the folder name changes the path changes so whether it is useDetailed or this effect, they would both react to that no? What was the idea here? The comment needs to state 1. not to use useDetailedItem and why 2. why/how the effect solves.

2022-08-30 11:20 UTC, rart commented on ui/app/src/components/LegacyFormDialog/EmbeddedLegacyContainer.tsx
> +  // if path changes
As above. 

Also, is it worth creating a hook for both of these instances?

2022-08-30 20:11 UTC, jvega190 commented
@rart I updated the comments, and created a hook called useDetailedItemNoState

2022-09-01 08:05 UTC, rart requested changes
Do we actually need a **detailed** item here? It's a bit more expensive to fetch so if Sandbox does, we should go for that.

As far as the new hook, lets try something like....
```ts
export function useFetchItem(path: string, detailed: boolean = false): DetailedItem {
   const [item, setItem] = useState(null);
   const siteId = useActiveSiteId();
   useEffect(() => {
     if (detailed) 
       fetchDetailedItem(siteId, path).subscribe(setItem);
      else
       fetchSandboxItem(sideId, path, { caseAsDetailedItem: true }).subscribe(setItem)
   }, [siteId, path, detailed]);
   return item;
 }
```

2022-09-01 08:05 UTC, rart commented on ui/app/src/hooks/useDetailedItemNoState.ts
> +}
```suggestion
}

export default useDetailedItemNoState;

```

2022-09-01 16:59 UTC, jvega190 commented on ui/app/src/components/RenameAssetDialog/RenameAssetDialogContainer.tsx
> +            if (!renameDisabled) {
Pushed this as a small fix (issue preventing submit on enter)

2022-09-02 09:18 UTC, rart commented on ui/app/src/hooks/useFetchItem.ts
> +}
```suggestion
}

export default useFetchItem;

```

2022-09-02 09:20 UTC, rart commented on ui/app/src/hooks/useFetchItem.ts
> +import { DetailedItem } from '../models';
```suggestion
import { DetailedItem } from '../models/Item';
```

2022-09-02 09:20 UTC, rart approved these changes

2022-09-02 13:45 UTC, merged