[5780] Projects - don't cancel the marketplace/search request when loading the page.
craftercms/studio-ui pull request #3146
Opened 2022-09-09 22:46 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5780

2022-09-16 07:37 UTC, rart requested changes

2022-09-16 07:37 UTC, rart commented on ui/app/src/components/CreateSiteDialog/CreateSiteDialogContainer.tsx
> +// TODO: enhance this props
?

2022-09-16 17:11 UTC, jvega190 commented on ui/app/src/components/CreateSiteDialog/CreateSiteDialogContainer.tsx
> +// TODO: enhance this props
Forgot to remote the TODO comment

2022-09-19 11:16 UTC, rart requested changes

2022-09-19 11:16 UTC, rart commented on ui/app/src/components/CreateSiteDialog/CreateSiteDialogContainer.tsx
> +}
You removed the TODO but didn't actually fix it.

2022-09-21 11:27 UTC, rart requested changes

2022-09-21 11:27 UTC, rart commented on ui/app/src/components/CreateSiteDialog/CreateSiteDialogContainer.tsx
> +  setSite(site): void;
Type missing

2022-09-22 07:35 UTC, rart approved these changes

2022-09-22 12:48 UTC, merged