[5792] XB (react) - cursor not changing to pencil when hovering xb zones, padding mode not applying styles
craftercms/studio-ui pull request #3149
Opened 2022-09-20 21:05 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5792

2022-09-21 11:24 UTC, rart requested changes

2022-09-21 11:24 UTC, rart commented on ui/guest/src/react/Field.tsx
> +      ['node-selector', 'checkbox-group', 'repeat'].includes(field.type) && { 'data-craftercms-type': 'collection' }),
Why would the checkbox group require the attribute?
```suggestion
      ['node-selector', 'repeat'].includes(field.type) && { 'data-craftercms-type': 'collection' }),
```

Move this whole expression out of the primitive initialization. We don't need to inline everything here.

2022-09-21 11:24 UTC, rart commented on ui/guest/src/react/Field.tsx
> +
```suggestion
  const contentTypeId = model.craftercms.contentTypeId;
  const contentType = contentController.getCachedContentType(contentTypeId);
  const field = contentType?.fields[fieldId];
```

2022-09-21 11:24 UTC, rart commented on ui/guest/src/react/Field.tsx
> +    'data-craftercms-model-id': model.craftercms.id,
Use a different attribute (e.g. `data-craftercms-field`). Value is unnecessary. Add comment stating why we're adding these attributes.

2022-09-21 11:24 UTC, rart commented on ui/guest/src/react/RenderField.tsx
> +
```suggestion
  // Comment stating why these attributes...
  const contentTypeId = model.craftercms.contentTypeId;
  const contentType = contentController.getCachedContentType(contentTypeId);
  const field = contentType?.fields[fieldId];
  passDownProps['data-craftercms-model-id'] = model.craftercms.id;
  if (field && ['node-selector', 'checkbox-group', 'repeat'].includes(field.type)) {
    passDownProps['data-craftercms-type'] = 'collection';
  }
```

2022-09-22 07:33 UTC, rart approved these changes

2022-09-22 07:33 UTC, rart commented on ui/guest/src/react/GuestGlobalStyles.tsx
> +        '[data-craftercms-model-id], & [data-craftercms-model-id] a, & [data-craftercms-field]': {
missing the internal a style, like the pre-existing style

2022-09-22 07:33 UTC, rart commented on ui/guest/src/react/Field.tsx
> +import { contentController } from '../index';
import from direct file

2022-09-22 07:33 UTC, rart commented on ui/guest/src/react/RenderField.tsx
> +import { contentController } from '../index';
import from direct file

2022-09-22 07:34 UTC, rart requested changes
review above

2022-09-23 14:28 UTC, rart requested changes

2022-09-23 14:28 UTC, rart commented on ui/guest/src/react/RenderField.tsx
> +  if (field && ['node-selector', 'checkbox-group', 'repeat'].includes(field.type)) {
checkbox-group still

2022-09-27 19:30 UTC, rart requested changes
Check if we also need Model, RenderRepeat and RenderComponents to have the attributes

2022-09-27 19:30 UTC, rart commented on ui/guest/src/react/Field.tsx
> +import * as contentController from '../contentController';
import the thing you need

2022-09-27 19:30 UTC, rart commented on ui/guest/src/react/RenderField.tsx
> +import * as contentController from '../contentController';
import the thing you need only

2022-09-27 19:35 UTC, rart requested changes
Check if we also need Model, RenderRepeat and RenderComponents to have the attributes

2022-09-28 18:17 UTC, jvega190 commented
Those components don't need the attributes, since Model uses Field, `RenderRepeat` uses `RenderField` and `RenderComponent` uses `RenderRepeat`. Both `Field` and `RenderField` have all they need to include the attributes (no extra changes needed on the mentioned components)

2022-09-29 09:31 UTC, rart approved these changes

2022-09-29 19:23 UTC, merged