[5862] Component and Shared Content Node Selectors show incorrect dialog
craftercms/studio-ui pull request #3208
Opened 2022-12-02 16:18 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5862

2022-12-05 16:37 UTC, rart requested changes

2022-12-05 16:37 UTC, rart commented on ui/app/src/components/BrowseFilesDialog/BrowseFilesDialogContainer.tsx
> +    allowUpload
Add default

2022-12-05 16:37 UTC, rart commented on ui/app/src/components/BrowseFilesDialog/utils.ts
> +  allowUpload?: boolean;
Base props already provide allowUpload?

2022-12-06 16:31 UTC, jvega190 commented on ui/app/src/components/BrowseFilesDialog/utils.ts
> +  allowUpload?: boolean;
This one doesn't inherit from base props

2022-12-07 09:41 UTC, rart approved these changes

2022-12-07 14:31 UTC, merged