[5886] Upgrade Fast XML Parser
craftercms/studio-ui pull request #3222
Opened 2022-12-20 22:37 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5886

2022-12-22 09:51 UTC, rart requested changes
☢️ Must retest most of the app. I recall small deserialization issues attempting the upgrade some time ago. **Be thorough**.

2022-12-22 09:51 UTC, rart commented on ui/app/src/utils/xml.ts
> +    htmlEntities: true,
Please test what happens if there are html entities inside CDATA, also test if the ui.xml UM/CDATA issues get fixed by this

2022-12-22 22:23 UTC, jvega190 commented
@rart I performed and or checked redux states on each of the deserialize usages and saw nothing incorrect. Though I wonder what issues you found.

2022-12-27 18:05 UTC, rart approved these changes

2022-12-28 00:36 UTC, merged