[5888] Export SearchUI component so that it can easily be used by plugins
craftercms/studio-ui pull request #3225
Opened 2022-12-28 15:24 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5888

2022-12-29 15:25 UTC, rart requested changes

2022-12-29 15:25 UTC, rart commented on ui/app/src/components/Search/Search.tsx
> +    sortOrder: parameters?.sortOrder ?? undefined
I do wonder if this is even necessary. If these props aren't supplied, they will already be undefined. If only the sub-props are not supplied, they will also be undefined.
 ```suggestion
    sortBy: parameters?.sortBy ?? UNDEFINED,
    sortOrder: parameters?.sortOrder ?? UNDEFINED
```

2022-12-29 15:25 UTC, rart commented on ui/app/src/components/Search/utils.ts
> +  parameters?: SearchParameters;
```suggestion
  initialFilters?: SearchParameters;
```

2022-12-29 15:25 UTC, rart commented on ui/app/src/components/Search/utils.ts
> +export interface SearchParameters extends Partial<ElasticParams> {
```suggestion
export interface SearchFilters extends Partial<ElasticParams> {
```

2022-12-29 15:25 UTC, rart commented on ui/app/src/components/Search/Search.tsx
> +      });
Preferably this should be in a single place. Where does this concatenation and such usually occurs? I would have thought this all should be on the useSearchState hook.

2022-12-29 18:27 UTC, jvega190 commented on ui/app/src/components/Search/utils.ts
> +  parameters?: SearchParameters;
per conversation, it'll be called 'initialParameters'

2022-12-29 18:27 UTC, jvega190 commented on ui/app/src/components/Search/utils.ts
> +export interface SearchParameters extends Partial<ElasticParams> {
per conversation, it'll remain called 'SearchParameters'

2023-01-03 11:32 UTC, rart approved these changes

2023-01-03 16:37 UTC, merged