[5920] Close content type form after clicking on "Save & Close"
craftercms/studio-ui pull request #3251
Opened 2023-02-02 21:32 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5920

2023-02-03 13:53 UTC, rart requested changes
On the "no template dialog"...
-  Update title to "Missing Template"
- Update the body: "Confirm a template is not required for this content type. Failing to assign a template would cause rendering issues on templated apps."
- Update the button choices to: 
  - **Template not required, save & close** — Clicking would _check_ the "No template required" option, save & close
  - **Create a template** — Open the template creation experience. If completed, use that as the template, save & close. If cancelled, for simplicity, dismiss the dialog and remain in the editor.
  - **Choose existing template** — Open the template picking experience. Completed/cancelled same as "create"
  - **Stay & continue editing**

Use a dialog layout like the "Confirm Dialog" with centered copy and full width stacked buttons.

2023-02-08 17:52 UTC, rart requested changes
Refactor the ConfirmDialog to internally use a new `AlertDialog`. The alert dialog would be basically what the ConfirmDialog uses underneath. AlertDialog receives prop `buttons: React.ReactNode`. Get rid of the usage of makeStyles and put everything in place with sx. I think we can even remove the `classes` prop from confirm for now.

Remove the `NewTemplateDialog` components, this is too specific and probably soon to be discontinued. Simply render the new `AlertDialog` with the right props on the type editor.

2023-02-10 07:01 UTC, rart requested changes

2023-02-10 07:01 UTC, rart commented on ui/app/src/env/i18n-legacy.ts
> +  },
Is this in use?

2023-02-10 07:01 UTC, rart commented on ui/app/src/components/AlertDialog/AlertDialog.tsx
> +  const sx = getStyles();
Move the styles in place

2023-02-10 07:01 UTC, rart commented on ui/app/src/components/AlertDialog/AlertDialog.tsx
> +      aria-describedby="confirmDialogBody"
👆

2023-02-10 07:01 UTC, rart commented on ui/app/src/components/AlertDialog/AlertDialogContainer.tsx
> +      <DialogContent id="confirmDialogBody" sx={sx.dialogBody}>
👆

2023-02-10 07:01 UTC, rart commented on ui/app/src/components/AlertDialog/AlertDialogContainer.tsx
> +  const sx = getStyles();
Move styles in place

2023-02-10 07:01 UTC, rart commented on ui/app/src/components/AlertDialog/styles.ts
> +/*
Discard file

2023-02-10 07:01 UTC, rart commented on ui/app/src/components/AlertDialog/styles.ts
> +export type AlertDialogClassKey = 'dialog' | 'dialogImage' | 'dialogBody' | 'dialogTitle' | 'dialogFooter';
Update these keys.
Need to declare the `sxs?: PartialSxRecord<'root' | 'image' | 'body' | 'title' | 'footer'>` prop on the dialog props

2023-02-10 07:01 UTC, rart commented on ui/app/src/components/AlertDialog/AlertDialogContainer.tsx
> +        <Box component="img" src={imageUrl} alt="" sx={sx.dialogImage} />
Wrap image in conditional like title and body so we could have the dialog without image too

2023-02-10 07:01 UTC, rart commented on ui/app/src/components/AlertDialog/AlertDialogContainer.tsx
> +      <DialogFooter sx={sx.dialogFooter}>{nnou(buttons) && buttons}</DialogFooter>
```suggestion
      {nnou(buttons) && <DialogFooter sx={sxs?.footer}>{buttons}</DialogFooter>}
```

2023-02-10 15:35 UTC, jvega190 commented on ui/app/src/env/i18n-legacy.ts
> +  },
yeah that's one of the options when saving the content-type editor. (save, save & close, save & minimize)

2023-02-14 07:51 UTC, rart commented on ui/app/src/components/AlertDialog/AlertDialog.tsx
> +  const sx = getStyles();
This wasn't done.

2023-02-14 07:51 UTC, rart commented on ui/app/src/components/AlertDialog/AlertDialogContainer.tsx
> +  const sx = getStyles();
This wasn't done.

2023-02-14 14:41 UTC, rart approved these changes

2023-02-14 14:51 UTC, merged