[5961] Publishing queue - 'All' filter shouldn't uncheck options once they're all already checked.
craftercms/studio-ui pull request #3271
Opened 2023-02-28 22:13 UTC by jvega190

https://github.com/craftercms/craftercms/issues/5961

2023-03-01 11:32 UTC, rart requested changes
Ping me to discuss some additional updates

2023-03-01 21:25 UTC, jvega190 commented on ui/app/src/components/CreateSiteDialog/index.ts
> -export * from './FilterDropdown';
Moved this out of here since it is only being used by PublishingQueue

2023-03-01 21:25 UTC, jvega190 commented on ui/app/src/models/Publishing.ts
> +export type Selected = LookupTable<boolean>;
This is being used in multiple parts, but updated it since it is basically a LookupTable

2023-03-01 21:37 UTC, rart requested changes

2023-03-01 21:37 UTC, rart commented on ui/app/src/components/PublishingDashboard/PublishingDashboard.tsx
> +            <PublishingQueueWidget siteId={site} readOnly={!userPermissions.includes('publish')} />
Cache the possession of the publish permission to avoid running the `.includes` twice

2023-03-02 09:36 UTC, rart approved these changes

2023-03-02 14:21 UTC, merged