[6011] Content can't be unlocked or edited after Save & Close and Save & Minimize action
craftercms/studio-ui pull request #3295
Opened 2023-04-12 22:26 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6011

2023-04-18 14:07 UTC, rart commented on ui/app/src/pages/LegacyMultiChoiceSaveButton.tsx
We discussed not to putting this on the react source, only if **strictly** necessary. What happened?

2023-04-18 17:35 UTC, jvega190 commented on ui/app/src/pages/LegacyMultiChoiceSaveButton.tsx
Moved to forms-engine

2023-04-18 19:33 UTC, rart commented on static-assets/components/cstudio-forms/forms-engine.js
> +                // });
???

2023-04-18 19:33 UTC, rart commented on ui/app/src/components/LegacyFormDialog/LegacyFormDialog.tsx
> +  }, [dispatch]);
This should go in EmbeddedLegacyContainer where the rest of events are handled

2023-04-19 16:10 UTC, rart requested changes

2023-04-19 16:10 UTC, rart commented on ui/app/src/state/reducers/dialogs/edit.ts
> +  disableOnClose: false
Let's rename to isSubmitting, for consistency.

2023-05-02 06:29 UTC, rart approved these changes

2023-05-02 13:22 UTC, merged