[6014] Delete dialog - When users checks the Dependent Items the Child Items should update the child items to remove
craftercms/studio-ui pull request #3303
Opened 2023-04-20 17:46 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6014

2023-04-26 09:52 UTC, rart requested changes

2023-04-26 09:52 UTC, rart commented on ui/app/src/components/DeleteDialog/DeleteDialogContainer.tsx
> +    const setChecked = Boolean(selectableDependent.find((path) => !selectedItems[path]));
Perhaps .some is more appropriate here

2023-04-26 09:52 UTC, rart commented on ui/app/src/components/DeleteDialog/DeleteDialogContainer.tsx
> +  useFetchSandboxItems(dependentItems ?? []);
How are other items fetched? Could we use same block to load these?

2023-04-26 09:52 UTC, rart commented on ui/app/src/components/DependencySelection/SelectionList.tsx
> +    disabledPaths = [],
Might perform better for this to be a lookup?

2023-04-26 16:00 UTC, jvega190 commented on ui/app/src/components/DeleteDialog/DeleteDialogContainer.tsx
> +  useFetchSandboxItems(dependentItems ?? []);
The items are a prop of the DeleteDialog, so they're coming from outside the dialog (the items selected for deletion)

2023-05-02 06:28 UTC, rart requested changes

2023-05-02 06:28 UTC, rart commented on ui/app/src/components/DeleteDialog/DeleteDialogContainer.tsx
> +    dependentItems?.filter((item) => !itemsByPath[item].availableActionsMap.delete) ?? [],
Specially with the new logic, is there a moment where `itemsByPath` does't have all the paths loaded? You should throttle for testing
```suggestion
    dependentItems?.filter((path) => !itemsByPath[path]?.availableActionsMap.delete) ?? [],
```

2023-05-04 17:43 UTC, rart approved these changes

2023-05-04 18:02 UTC, merged