[6052] Dashboard responsive updates
craftercms/studio-ui pull request #3316
Opened 2023-05-11 23:02 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6052

2023-05-12 20:45 UTC, jvega190 commented on ui/app/src/components/DashletCard/DashletCard.tsx
> +    collapsible?: boolean;
Collapsible is needed for it not to be shown in the activityDashlet (in desktopMode). Defaults to true

2023-05-12 20:48 UTC, jvega190 commented on ui/app/src/components/DashletCard/DashletCard.tsx
> +      {isMaximized && renderCardContent()}
Card content rendered outside of accordion in maximized mode due to fixed height in accordion preventing the content to fully display

2023-05-16 14:50 UTC, rart requested changes

2023-05-16 14:50 UTC, rart commented on ui/app/src/components/DashletCard/DashletCard.tsx
> +import AccordionSummary from '@mui/material/AccordionSummary';
Rollback the use of accordion. Just wrap the body area in a conditonal. Can try a [transition component](https://mui.com/material-ui/transitions/) (e.g. Grow) or keep it simple. Also, don't add an icon for the collapsing for _desktop_.

Alternatively, rather use the Accordion alone — no card components. Accordion is a bit bloated in styles and features so think easiest to stick with card for now.

2023-05-17 18:02 UTC, rart requested changes

2023-05-17 18:02 UTC, rart commented on ui/app/src/components/DashletCard/DashletCard.tsx
> +  const showCardBody = isExpanded || desktopScreen || isMaximized;
It's ok to collapse on "desktopScreen". Only not when maximized.

2023-05-18 01:46 UTC, rart requested changes

2023-05-18 01:46 UTC, rart commented on ui/app/src/components/DashletCard/DashletCard.tsx
> +              )}
I'm thinking... let's make the whole header collapse/expand. Just make sure the actual button clicks stop the event so they don't unintentionally collapse the widget.

What if we wrap the CardHeader in CardActionArea.

Let's get rid of the icon/button all together; though not as discoverable, I'm hoping the action area highlight would help with that.

2023-05-22 15:52 UTC, rart approved these changes

2023-05-22 15:53 UTC, merged