[6054] Clear dashlet options after performing actions in new Dashboard
craftercms/studio-ui pull request #3317
Opened 2023-05-12 21:52 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6054

2023-05-17 17:45 UTC, rart requested changes
This seems possibly disruptive. Events flow through the system at all times and your selection can get lost as you're working. We should try to keep state as steady as possible.

When those events happen, it's ok to fetch but we should keep state steady:
- Stay in the same page, keep selection. You need to fetch up to that page (all prior pages) and check selection is still valid. There are some edge cases, we can refine later.
- Clear the selection after any action is triggered.

Also please default page size to 50 items on all widgets, enable a background refresh, the refresh button should disable (`loading={true}`) whist fetching/reloading.

2023-05-22 15:45 UTC, rart requested changes
Apply changes to all.

2023-05-22 15:45 UTC, rart commented on ui/app/src/components/ActivityDashlet/ActivityDashlet.tsx
> +  const [isFetching, setIsFetching] = useState(false);
Rename both appropriately. What's the distinction between them though? When is one true vs the other... 
Could/should this be a part of the existing spread state?

2023-05-22 15:45 UTC, rart commented on ui/app/src/components/ActivityDashlet/ActivityDashlet.tsx
>          </IconButton>
```suggestion
        <LoadingButton onClick={() => onRefresh(true)} loading={isFetching} sx={{ borderRadius: '50%', padding: '8px', minWidth: 0 }}>
          <DeleteIcon />
        </LoadingButton>
```

2023-05-22 15:45 UTC, rart commented on ui/app/src/components/ExpiringDashlet/ExpiringDashlet.tsx
> +        <IconButton onClick={onRefresh} disabled={state.loading}>
As above

2023-05-22 15:45 UTC, rart commented on ui/app/src/components/MyRecentActivityDashlet/MyRecentActivityDashlet.tsx
> +  const [isFetching, setIsFetching] = useState(false);
As above

2023-05-22 15:45 UTC, rart commented on ui/app/src/components/MyRecentActivityDashlet/MyRecentActivityDashlet.tsx
> +        <IconButton onClick={onRefresh} disabled={isFetching}>
As above

2023-05-22 19:27 UTC, rart requested changes

2023-05-22 19:27 UTC, rart commented on ui/app/src/components/ScheduledDashlet/ScheduledDashlet.tsx
> +      });
Why load pages separately?

2023-05-22 19:27 UTC, rart commented on ui/app/src/components/PendingApprovalDashlet/PendingApprovalDashlet.tsx
> +      });
Why load pages separately?

2023-05-22 19:27 UTC, rart commented on ui/app/src/components/UnpublishedDashlet/UnpublishedDashlet.tsx
> +      });
?

2023-05-22 19:27 UTC, rart commented on ui/app/src/components/UnpublishedDashlet/UnpublishedDashlet.tsx
> +  itemsByPathRef.current = itemsById;
```suggestion
  const itemsByPathRef = useUpdateRefs(itemsById);
```

2023-05-23 15:17 UTC, rart requested changes

2023-05-23 15:17 UTC, rart commented on ui/app/src/components/PendingApprovalDashlet/PendingApprovalDashlet.tsx
> +      setItemsById({});
Necessary?

2023-05-23 15:17 UTC, rart commented on ui/app/src/components/ScheduledDashlet/ScheduledDashlet.tsx
> +      setItemsById({});
necessary?

2023-05-23 15:17 UTC, rart commented on ui/app/src/components/UnpublishedDashlet/UnpublishedDashlet.tsx
> +
```suggestion
```

2023-05-23 15:17 UTC, rart commented on ui/app/src/components/UnpublishedDashlet/UnpublishedDashlet.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Doesn't matter, doesn't hurt to add it and that way we don't loose the linting.

2023-05-23 20:52 UTC, jvega190 commented on ui/app/src/components/ScheduledDashlet/ScheduledDashlet.tsx
> +      setItemsById({});
not needed, removing

2023-05-24 09:30 UTC, rart approved these changes

2023-05-24 13:54 UTC, sumerjabri commented
@jvega190 please fix conflict

2023-05-24 20:09 UTC, rart approved these changes

2023-05-24 20:16 UTC, merged