[6088] Scheduled publish date/time is not listed in the "Scheduled for Publish" and "Pending Approval" dashlet
craftercms/studio-ui pull request #3339
Opened 2023-05-31 16:37 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6088

2023-05-31 16:42 UTC, jvega190 commented
Pending sorting capabilities in APIs for the dashlets to be properly sorted

2023-06-05 10:34 UTC, rart approved these changes

2023-06-08 19:32 UTC, rart requested changes
- Change "Filter by..." > "Show"
- Pluralize filter options (Items, Content Types, etc)
- DashletFilter:
  - Receives: `selectedKey: FilterSystemTypeGroups` (item, asset, contentType, etc) 
  - Emits: `onChange(e: Event, key: FilterSystemTypeGroups)`
  - `useDashletFilterState(storageKey: string): { selectedKey, onChange(), selectedTypes }`
    - Internally manages localStorage
- fetchScheduled to receive array of itemTypes and service to `join(',')`
- Backend to correct default sorting for Scheduled for Publish api  
- Remove Avatar from skeletons were they don't apply

2023-06-08 19:32 UTC, rart commented on ui/app/src/components/ActionsBar/ActionsBar.tsx
> +        )}
Remove wrapper, move all conditions to the `if`

2023-06-08 19:50 UTC, rart commented on ui/app/src/models/SystemType.ts
> +  | 'unknown'
Remove unknown.

Per backend:
asset
component
content type
document
file
folder
levelDescriptor
page
renderingTemplate
script
taxonomy

2023-06-09 08:24 UTC, rart requested changes

2023-06-09 08:24 UTC, rart commented on ui/app/src/components/ActionsBar/ActionsBar.tsx
> +        {Boolean(noSelectionContent) && !isLoading && !isIndeterminate && !isChecked && noSelectionContent}
```suggestion
        {!isLoading && !isIndeterminate && !isChecked && noSelectionContent}
```

2023-06-09 08:24 UTC, rart commented on ui/app/src/components/ActivityDashlet/DashletFilter.tsx
> +        <FormattedMessage defaultMessage="Filter Active ({count})" values={{ count: selectedKeys.length }} />
```suggestion
        <FormattedMessage defaultMessage="Filters active: {count}" values={{ count: selectedKeys.length }} />
```

2023-06-09 08:24 UTC, rart commented on ui/app/src/components/ActivityDashlet/DashletFilter.tsx
> +        <FormattedMessage defaultMessage="Show" />
```suggestion
        <FormattedMessage defaultMessage="Show all" />
```

2023-06-09 08:24 UTC, rart commented on ui/app/src/hooks/useDashletFilterState.ts
> +  const [selectedKeys, setSelectedKeys] = useState<FilterSystemTypeGroups[]>(initialKeys);
```suggestion
  const [selectedKeys, setSelectedKeys] = useState<FilterSystemTypeGroups[]>(() => getDashletFilterTypeGroups(uuid, storageKey) ?? ['all']);
```

2023-06-09 08:24 UTC, rart commented on ui/app/src/utils/state.ts
> +export function getDashletFilterTypeGroups(
```suggestion
// Explain here...
export function getDashletFilterSystemTypeGroups(
```

2023-06-09 08:24 UTC, rart commented on ui/app/src/utils/state.ts
> +export function setDashletFilterTypeGroups(
```suggestion
// Explain..
export function setDashletFilterSystemTypeGroups(
```

2023-06-09 08:24 UTC, rart commented on ui/app/src/components/UnpublishedDashlet/UnpublishedDashlet.tsx
> +              }}
onChange={filterState.onChange}

2023-06-09 08:24 UTC, rart commented on ui/app/src/components/ActivityDashlet/DashletFilter.tsx
> +      onMenuItemClick={(e, key) => onChange(e, key as FilterSystemTypeGroups)}
```suggestion
      onMenuItemClick={onChange}
```

2023-06-09 08:24 UTC, rart commented on ui/app/src/hooks/useDashletFilterState.ts
> +  onChange(key: FilterSystemTypeGroups): void;
```suggestion
  onChange(e: Ev, key: FilterSystemTypeGroups): void;
```

2023-06-12 09:42 UTC, rart requested changes

2023-06-12 09:42 UTC, rart commented on ui/app/src/components/ActivityDashlet/DashletFilter.tsx
> +        <FormattedMessage defaultMessage="Filters active: ({count})" values={{ count: selectedKeys.length }} />
```suggestion
        <FormattedMessage defaultMessage="Filters active: {count}" values={{ count: selectedKeys.length }} />
```

2023-06-12 09:42 UTC, rart commented on ui/app/src/components/PendingApprovalDashlet/PendingApprovalDashlet.tsx
> +  });
Can we move `loadPagesUntil` here and keep a single _refs_? You could move this declaration below the others.

2023-06-12 09:42 UTC, rart commented on ui/app/src/components/ScheduledDashlet/ScheduledDashlet.tsx
> +  });
Same deal

2023-06-12 09:42 UTC, rart commented on ui/app/src/components/UnpublishedDashlet/UnpublishedDashlet.tsx
> +  });
"

2023-06-12 09:42 UTC, rart commented on ui/app/src/utils/state.ts
> +// Gets the stored list of type groups used by a dashlet (identified by storageKey) for filtering
```suggestion
// Gets the stored list of system type groups used by a dashlet (identified by storageKey) for filtering
```

2023-06-12 09:42 UTC, rart commented on ui/app/src/utils/state.ts
> +): (FilterSystemTypeGroups | 'all')[] {
Declare this locally as a type above so you can reuse

2023-06-12 09:42 UTC, rart commented on ui/app/src/utils/state.ts
> +  return typeGroups?.split(',') as (FilterSystemTypeGroups | 'all')[];
Will this ever store `'all'`?

2023-06-12 09:42 UTC, rart commented on ui/app/src/utils/state.ts
> +// Stores a list of group types (from where we retrieve the system types) for dashlet filtering.
```suggestion
// Stores a list of system type groups (from where we retrieve the system types) for dashlet filtering.
```

2023-06-12 14:48 UTC, jvega190 commented on ui/app/src/utils/state.ts
> +): (FilterSystemTypeGroups | 'all')[] {
My bad, FilterSystemTypeGroups already has 'all' as it is a part of the possible values

2023-06-12 14:58 UTC, jvega190 commented on ui/app/src/utils/state.ts
> +  return typeGroups?.split(',') as (FilterSystemTypeGroups | 'all')[];
yeah 'all' gets stored

2023-06-12 18:40 UTC, rart approved these changes

2023-06-12 18:58 UTC, merged