[6099] Add feedback when creating a folder with the same name as a page
craftercms/studio-ui pull request #3344
Opened 2023-06-01 21:14 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6099

2023-06-05 10:17 UTC, rart requested changes

2023-06-05 10:17 UTC, rart commented on ui/app/src/components/CreateFolderDialog/CreateFolderContainer.tsx
> +    : itemLookupTable[newFolderPath] !== UNDEFINED || itemLookupTable[withIndex(newFolderPath)] !== UNDEFINED;
There's a útil that checks the same path doing both withIndex and withoutIndex on a given lookup table. Use that one.

2023-06-05 10:20 UTC, rart commented
Also, i s the backend exception covered?

2023-06-05 14:55 UTC, jvega190 commented
Yeah, the exception is covered by the backend

2023-06-06 06:44 UTC, rart approved these changes

2023-06-06 14:19 UTC, merged