[6091] Expiry/Expired date shown in "Expiring" dashlet is off by 4 hours
craftercms/studio-ui pull request #3345
Opened 2023-06-02 18:27 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6091

2023-06-05 10:38 UTC, rart requested changes

2023-06-05 10:38 UTC, rart commented on static-assets/components/cstudio-forms/controls/date-time.js
> +    // this.defaultTimezone = 'UTC';
Did you mean to delete?

2023-06-05 10:38 UTC, rart commented on static-assets/components/cstudio-forms/controls/time.js
> +    // this.defaultTimezone = 'UTC';
Delet?

2023-06-05 15:06 UTC, jvega190 commented on static-assets/components/cstudio-forms/controls/date-time.js
> +    // this.defaultTimezone = 'UTC';
Yeah, deleting

2023-06-05 15:06 UTC, jvega190 commented on static-assets/components/cstudio-forms/controls/time.js
> +    // this.defaultTimezone = 'UTC';
Yeah, deleting

2023-06-06 06:43 UTC, rart approved these changes

2023-06-06 14:19 UTC, merged