[6085] Item path is not displayed in dashlet
craftercms/studio-ui pull request #3348
Opened 2023-06-05 22:44 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6085

2023-06-06 06:55 UTC, rart requested changes

2023-06-06 06:55 UTC, rart commented on ui/app/src/components/UnpublishedDashlet/UnpublishedDashlet.tsx
> +              {over === item.path && <DashletItemOptions path={item.path} />}
These should be the ListItem `secondaryAction`. Is that not available on `ListItemButton`? Also, the show hide might be achievable via css only so we can remove the hovering events.

2023-06-06 06:55 UTC, rart commented on ui/app/src/components/UnpublishedDashlet/UnpublishedDashlet.tsx
> +  const [over, setOver] = useState(null);
If this is kept, rename appropriately (e.g. `currentHoverPath`)

2023-06-06 15:42 UTC, jvega190 commented on ui/app/src/components/UnpublishedDashlet/UnpublishedDashlet.tsx
> +              {over === item.path && <DashletItemOptions path={item.path} />}
yeah `secondaryAction` is not available in `ListItemButton`

2023-06-07 08:40 UTC, rart requested changes

2023-06-07 08:40 UTC, rart commented on ui/app/src/components/ExpiringDashlet/ExpiringDashlet.tsx
> +        }
```suggestion
        sx={{ [`.${classes.secondaryAction}`]: { display: 'none' }, [`&:hover ${classes.secondaryAction}`]: { display: 'inline-block' } }}
        secondaryAction={
          <DashletItemOptions path={item.sandboxItem.path} />
        }
```

2023-06-07 08:40 UTC, rart commented on ui/app/src/components/ExpiringDashlet/ExpiringDashlet.tsx
> +        }
Apply to all

2023-06-08 19:50 UTC, rart approved these changes

2023-06-08 22:48 UTC, merged