[6135] Recoloring Icons in the Left Nav Tree does not work in new versions
craftercms/studio-ui pull request #3360
Opened 2023-06-21 22:10 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6135

2023-06-22 18:18 UTC, rart requested changes
- Does the PathNavTree need any update?
- Rollback SystemIcon and do the updates on its usage on the PathNav so we don't unintentionally affect **everything** using SystemIcon

2023-06-22 18:44 UTC, jvega190 commented on ui/app/src/components/SystemIcon/SystemIcon.tsx
> +        <ErrorRounded sx={combinedSx} className={iconClassName} />
Added className in here to apply classes in non-existing icon scenario

2023-06-22 18:45 UTC, jvega190 commented
@rart no changes needed in PathNavTree since it uses the same `PathNavigatorHeader`

2023-06-29 09:22 UTC, rart approved these changes

2023-06-29 13:11 UTC, merged