[6122] Pending approval and schedule for publish showing info of the last modifier of the item instead of the current one
craftercms/studio-ui pull request #3365
Opened 2023-06-29 21:37 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6122

2023-06-30 17:33 UTC, jvega190 commented
Waiting for addition of `dateSubmitted` prop

2023-07-04 14:42 UTC, rart requested changes
Add a `CHANGELOG.md` to `ui/app/src` and let's start tracking changes.

2023-07-04 14:42 UTC, rart commented on ui/app/src/utils/content.ts
> +        lastName: item.user,
```suggestion
        firstName: null,
        lastName: null,
```

2023-07-04 14:42 UTC, rart commented on ui/app/src/utils/content.ts
> +      lastName: item.user,
```suggestion
      firstName: null,
      lastName: null,
```

2023-07-04 14:42 UTC, rart commented on ui/app/src/state/epics/content.ts
> +        ([{ payload }, state]) => state.content.itemsByPath[payload.path].lockOwner.username === state.user.username
```suggestion
        ([{ payload }, state]) => state.content.itemsByPath[payload.path].lockOwner?.username === state.user.username
```

2023-07-04 16:58 UTC, jvega190 commented
@rart re-requested a review but I haven't added the changelog, will work on it

2023-07-05 14:07 UTC, rart approved these changes

2023-07-05 15:14 UTC, jvega190 commented
This PR needs to be merged with https://github.com/craftercms/studio/pull/3276 to avoid issues on the UI

2023-07-05 18:18 UTC, merged