[6155] Remove sites prop from user in state
craftercms/studio-ui pull request #3373
Opened 2023-07-13 16:57 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6155

2023-08-07 17:32 UTC, rart requested changes

2023-08-07 17:32 UTC, rart commented on ui/app/src/state/actions/system.ts
> -  sites: Array<Site>;
This does go into the payload of the storeInitialized, if I'm not mistaken. It just doesn't go into the users state but it goes into sites state. Where do we fetch sites otherwise?

2023-08-08 08:19 UTC, rart requested changes
This PR got mixed up with others.

2023-08-08 14:23 UTC, jvega190 commented
@rart fixed PR

2023-08-08 16:14 UTC, rart approved these changes

2023-08-08 18:06 UTC, merged