573E
craftercms/studio-ui pull request #3390
Opened 2023-08-09 23:53 UTC by jvega190

https://github.com/craftersoftware/craftercms/issues/573

2023-08-11 16:07 UTC, rart requested changes

2023-08-11 16:07 UTC, rart commented on ui/app/src/hooks/useIntCountdown.ts
> +  }, [countdown]);
As it stands, this works with a timeout rather than an interval. It continually clears the interval every second. 
```suggestion
  useEffect(() => {
    if (seconds > 0) {
      let num = seconds;
      const timer = setInterval(() => {
        setCountdown(--num);
        if (num === 0) {
          clearInterval(timer);
          onCompleteRef.current?.();
        }
      }, 1000);
      return () => clearInterval(timer);
    }
  }, [seconds]);
```

2023-08-11 16:07 UTC, rart commented on ui/app/src/hooks/useIntCountdown.ts
> +  const [countdown, setCountdown] = useState(number);
```suggestion
export const useTimer = (seconds: number, onComplete: (): void) => {
  const [countdown, setCountdown] = useState(seconds);
  const onCompleteRef = useUpdatedRefs(onComplete);
```

2023-08-11 16:07 UTC, rart commented on ui/app/src/components/LoginView/LoginView.tsx
>    }
We should be able to remove ids on these two, no?
Also, I think these can be combined into a single translation message with the conditional logic thingie.
Preferably, use the FormattedMessage API.

2023-08-11 16:07 UTC, rart commented on ui/app/src/components/LoginView/LoginView.tsx
> +  const lockedCountdown = useIntCountdown(lockedTimeSeconds);
What's the value of this prop when the user isn't locked out?

2023-08-18 18:21 UTC, jvega190 commented on ui/app/src/components/LoginView/LoginView.tsx
> +  const lockedCountdown = useIntCountdown(lockedTimeSeconds);
the value is 'undefined'

2023-08-18 18:29 UTC, jvega190 commented on ui/app/src/components/LoginView/LoginView.tsx
>    }
updated/combined translation. The error message is already using `formatMessage` for other messages, should I refactor it?

2023-08-18 20:07 UTC, rart commented on ui/app/src/components/LoginView/LoginView.tsx
>    }
nah

2023-08-18 20:10 UTC, rart approved these changes

2023-08-18 20:33 UTC, merged