[6175] Remove the maximum width on the sidebar
craftercms/studio-ui pull request #3404
Opened 2023-08-28 21:20 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6175

2023-08-29 07:30 UTC, rart requested changes

2023-08-29 07:30 UTC, rart commented on ui/app/src/hooks/usePreviewUrlControl.tsx
> +  }, [dispatch]);
1. Why here? Don't think this is the right place for this as this file is got to do with URL monitoring. Make this into a hook and call it in PreviewConcierge. 
2. You need to debounce the dispatch.
```ts 
fromEvent(window, 'resize').pipe(debounce(200)).subscribe(()=>dispatch(setWindowSize()))
```

2023-08-29 07:30 UTC, rart commented on ui/app/src/state/reducers/preview.ts
> +    if (icePanelWidth - windowSize >= 320) {
Extract 320 as a const for reuse. You'll need it in a few places.

2023-08-29 07:30 UTC, rart commented on ui/app/src/components/ICEToolsPanel/ICEToolsPanel.tsx
> +      maxWidth={windowSize}
Max width size would be `windowSize-minPreviewWidth-otherToolbarSize`?
What's this for anyway? It's controlled in reducers and it wasn't there before.

2023-08-29 07:30 UTC, rart commented on ui/app/src/components/ToolsPanel/ToolsPanel.tsx
> +      maxWidth={windowSize}
As above

2023-08-29 07:30 UTC, rart commented on ui/app/src/state/reducers/preview.ts
Haven't checked the maths but there's a bit of code repetition. Factor when you got it all clear.

2023-09-01 07:07 UTC, rart requested changes

2023-09-01 07:07 UTC, rart commented on ui/app/src/hooks/useWindowSizeControl.ts
> +  }, [toolsPanelWidth, siteId, user?.username]);
I'm not sure user.username will ever be null (ie doesn't need optional chaining). 
Did you see that case? If that was the case, the inner logic needs to consider this.

2023-09-01 07:07 UTC, rart commented on ui/app/src/hooks/useWindowSizeControl.ts
I'm thinking...
```ts
// epics/preview
  (action$, state$) =>
    action$.pipe(
      ofType(storeInitialized),
      switchMap(() =>
        fromEvent(window, 'resize').pipe(
          debounceTime(200),
          map((e) => setWindowSize({ width: e.target.innerWidth, height: e.target.innerHeight })),
          // Not quite sure where this needs to be exactly, so test 👇🏻. Might need to be put elsewhere
          // or use a different strategy to get this set on initialization.
          startWith(setWindowSize({ width: window.innerWidth, height: window.innerHeight }))
        )
      )
    ),
  (action$, state$) =>
    action$.pipe(
      ofType(setWindowSize),
      tap(([, state]) => {
        setStoredICEToolsPanelWidth(...)
        setStoredPreviewToolsPanelWidth(...)
      }),
      ignoreElements()
    ),
```
...and we get rid of this whole effect, which isn't very general purpose anyway.

2023-09-01 07:07 UTC, rart commented on ui/app/src/state/reducers/preview.ts
ReduxToolkit sends you a wrapped state object which you can modify directly — no need for spreading. It does tend to look cleaner. Let's migrate to using that style.

2023-09-01 17:51 UTC, jvega190 commented on ui/app/src/hooks/useWindowSizeControl.ts
> +  }, [toolsPanelWidth, siteId, user?.username]);
the optional chaining is not needed, removing

2023-09-05 21:21 UTC, rart commented on ui/app/src/state/reducers/preview.ts
This isn't done. Did you miss a commit?

2023-09-05 21:22 UTC, rart requested changes
Comment above

2023-09-05 22:15 UTC, jvega190 commented on ui/app/src/state/reducers/preview.ts
Yeah there was a missing commit. Though now that I think, I only updated the handlers that I modified in this ticket. Should I update all the reducer with the new style?

2023-09-07 18:33 UTC, rart approved these changes

2023-09-07 19:06 UTC, merged