[6203] Make default Preview edit mode on/off configurable
craftercms/studio-ui pull request #3411
Opened 2023-09-07 22:07 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6203

2023-09-08 14:55 UTC, rart requested changes

2023-09-08 14:55 UTC, rart commented on ui/app/src/services/configuration.ts
> +      ),
This needs to go to ui.xml. Create a new block:
```xml
<widget 
  id="craftercms.components.Preview" 
  initialEditModeOn="true|false"
  initialHighlightMode="edit|move"
/>
```

2023-09-08 14:55 UTC, rart commented on ui/app/src/components/PreviewConcierge/PreviewConcierge.tsx
> +      dispatch(setPreviewEditMode({ editMode: defaultEditMode }));
I think the idea would be to have a `initPreviewConfig` similar to all other config sets and that would set things at the reducer level. The components never look at the _initial_ config value.

2023-09-11 12:31 UTC, rart requested changes

2023-09-11 12:31 UTC, rart commented on ui/app/src/state/reducers/preview.ts
> +      ?.getAttribute('initialHighlightMode');
```suggestion
const previewConfigEl = configDOM
      .querySelector('[id="craftercms.components.Preview"]')
    const initialEditModeOn = previewConfigEl
      ?.getAttribute('initialEditModeOn');
    const initialHighlightMode = previewConfigEl
      ?.getAttribute('initialHighlightMode');
```

2023-09-11 12:31 UTC, rart commented on ui/app/src/state/reducers/preview.ts
> +    const editMode = payload.storedEditMode ?? (nnou(initialEditModeOn) ? initialEditModeOn === 'true' : null);
```suggestion
    state.editMode = payload.storedEditMode ?? (initialEditModeOn ? initialEditModeOn === 'true' : state.editMode);
```

2023-09-11 12:31 UTC, rart commented on ui/app/src/state/reducers/preview.ts
> +    const highlightMode = payload.storedHighlightMode ?? initialHighlightMode;
```suggestion
    state.highlightMode = payload.storedHighlightMode ?? (['all', 'move'].includes(initialHighlightMode) ? initialHighlightMode : state.highlightMode);
```

2023-09-11 12:31 UTC, rart commented on ui/app/src/state/reducers/preview.ts
> +    }
```suggestion
    state.editModePadding = payload.storedPaddingMode ?? state.editModePadding;
```

2023-09-11 12:31 UTC, rart commented on ui/app/src/components/PreviewConcierge/PreviewConcierge.tsx
>      startCommunicationDetectionTimeout(guestDetectionTimeoutRef, setGuestDetectionSnackbarOpen);
Let's add `xbDetectionTimeoutMs` too as a possible config. Make 0 not check at all.

2023-09-11 19:38 UTC, rart commented on ui/app/src/state/reducers/preview.ts
> +    const highlightMode = payload.storedHighlightMode ?? initialHighlightMode;
Please confirm the correct value list for `all`, `move`

2023-09-11 22:48 UTC, jvega190 commented on ui/app/src/state/reducers/preview.ts
> +    const highlightMode = payload.storedHighlightMode ?? initialHighlightMode;
`all` and `move` are correct

2023-09-12 15:01 UTC, rart commented
Conflicts.

2023-09-12 17:11 UTC, rart requested changes

2023-09-12 17:11 UTC, rart commented on ui/app/src/components/PreviewConcierge/PreviewConcierge.tsx
> +      startCommunicationDetectionTimeout(
The socket connection should stay as it was. Only XB detection should take this change.

2023-09-12 17:11 UTC, rart commented on ui/app/src/components/PreviewConcierge/PreviewConcierge.tsx
> +  // Guest detection, document domain restoring and guest key up/down notifications.
```suggestion
  // Document domain restoring.
```

2023-09-12 17:11 UTC, rart commented on ui/app/src/state/reducers/preview.ts
> +      Boolean(xbDetectionTimeoutMs) && xbDetectionTimeoutMs > 0
`0` should be a valid value which means to not execute the check.
```suggestion
      nnou(xbDetectionTimeoutMs)
```

2023-09-13 14:21 UTC, rart requested changes

2023-09-13 14:21 UTC, rart commented on ui/app/src/state/reducers/preview.ts
> +      !isNaN(xbDetectionTimeoutMs) && xbDetectionTimeoutMs > 0
```suggestion
      !isNaN(xbDetectionTimeoutMs) && xbDetectionTimeoutMs >= 0
```

2023-09-13 15:43 UTC, rart approved these changes

2023-09-13 15:55 UTC, merged