[6150] Shared component path is not updated in parent renamed
craftercms/studio-ui pull request #3426
Opened 2023-09-28 23:59 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6150

2023-10-02 06:24 UTC, rart reviewed
Let's review together.

2023-10-03 16:11 UTC, rart requested changes

2023-10-03 16:11 UTC, rart commented on ui/app/src/components/DependenciesDialog/DependenciesDialog.tsx
> +    borderRadius: '5px 5px 0 0'
Make sure to test with large list of dependencies.

2023-10-03 16:11 UTC, rart commented on ui/app/src/components/RenameContentDialog/RenameContentDialogContainer.tsx
> +    ),
There's no need for callback memoizing, `useDebouncedInput` uses a ref internally.
```suggestion
    (name: string) => {
      checkPathExistence(
        siteId,
        `${ensureSingleSlash(`${path}/${name}`)}${isPage ? '/index.xml' : '.xml'}`
      ).subscribe((exists) => {
        setItemExists(name !== strippedValue && exists);
      });
    }
```

2023-10-03 16:11 UTC, rart commented on ui/app/src/components/RenameContentDialog/RenameContentDialogContainer.tsx
> +  };
```suggestion
  const onInputChanges = (newValue: string) => {
    setName(newValue);
    refs.current.onNameUpdate$.next(name);
    const newHasPendingChanges = newValue !== strippedValue;
    onSubmittingAndOrPendingChange({ hasPendingChanges: newHasPendingChanges });
  };
```

2023-10-03 16:11 UTC, rart commented on ui/app/src/components/RenameDialogBody/RenameItemView.tsx
> +export function RenameItemView(props: RenameDialogBodyProps) {
```suggestion
export interface RenameItemViewProps {
  name: string;
  disabled: boolean;
  newNameExists: boolean;
  dependantItems: DetailedItem[];
  isSubmitting: boolean;
  confirmBrokenReferences: boolean;
  setConfirmBrokenReferences: (value: boolean) => void;
  fetchingDependantItems: boolean;
  error: AjaxError;
  onRename: () => void;
  onInputChanges: (event: React.ChangeEvent<HTMLInputElement>) => void;
  helperText?: ReactNode;
}

export function RenameItemView(props: RenameItemViewProps) {
```

2023-10-03 16:11 UTC, rart commented on ui/app/src/utils/content.ts
> +export function applyContentNameRules(name: string): string {
```suggestion
/**
 * Please add content explaining more...
 */
export function applyContentNameRules(name: string): string {
```

2023-10-04 14:54 UTC, jvega190 commented on ui/app/src/components/DependenciesDialog/DependenciesDialog.tsx
> +    borderRadius: '5px 5px 0 0'
Per conversation we'll leave it without `overflowY`

2023-10-05 11:03 UTC, rart requested changes

2023-10-05 11:03 UTC, rart commented on ui/app/src/components/RenameContentDialog/RenameContentDialogContainer.tsx
> +  }, 400);
Don't really see the need for this as a ref.

```suggestion
  const refs = useUpdateRefs({

onNameUpdate$: useDebouncedInput((name: string) => {
    checkPathExistence(siteId, `${ensureSingleSlash(`${path}/${name}`)}${isPage ? '/index.xml' : '.xml'}`).subscribe(
      (exists) => {
        setItemExists(name !== strippedValue && exists);
      }
    );
  }, 400)

});
```

2023-10-05 15:25 UTC, jvega190 commented on ui/app/src/components/RenameContentDialog/RenameContentDialogContainer.tsx
> +  }, 400);
Yeah not needed, was initially supposed to be used differently. Removing ref

2023-10-05 15:54 UTC, rart approved these changes

2023-10-05 19:50 UTC, merged