[6150][4.0.x] Shared component path is not updated in parent renamed
craftercms/studio-ui pull request #3430
Opened 2023-10-05 20:40 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6150

2023-10-06 15:57 UTC, rart requested changes

2023-10-06 15:57 UTC, rart commented on ui/app/src/components/ConfirmDialog/utils.ts
> +  cancelButtonText?: ReactNode;
Add to state props like in `develop`

2023-10-11 14:56 UTC, rart commented
@jvega190 looks like you might have forgotten about this one 🙂

2023-10-11 17:18 UTC, jvega190 commented
done :)

2023-10-12 08:46 UTC, rart approved these changes

2023-10-12 13:48 UTC, merged