[617E] Limit the size of configuration files in UI editor
craftercms/studio-ui pull request #3464
Opened 2023-11-10 21:37 UTC by jvega190

https://github.com/craftersoftware/craftercms/issues/617

2023-11-14 14:33 UTC, rart requested changes
What was the delta of the calculation in UI vs the OS?

2023-11-14 14:33 UTC, rart commented on ui/app/src/utils/content.ts
> +export const MAX_CONFIG_SIZE = 512000; // Max configuration files allowed (in bytes)
Move to constants.

2023-11-15 03:52 UTC, rart commented
What's the answer to the question above?

2023-11-15 15:03 UTC, jvega190 commented
@rart exact max size in bytes for configuration files used in backend is 512*1024, differing from the OS calculation (524277 studio vs 512000 OS). Tested with the exact max size in bytes set by backend and when using an extra char/byte the backend request fails.

2023-11-16 07:57 UTC, rart requested changes
See [comment on the ticket](https://github.com/craftersoftware/craftercms/issues/617#issuecomment-1813948305).

2023-11-16 07:57 UTC, rart commented on ui/app/src/utils/constants.ts
> +export const MAX_CONFIG_SIZE = 512 * 1024; // Max configuration files allowed (in bytes)
```suggestion
export const MAX_CONFIG_FILE_SIZE = 524288; // Max configuration file size allowed (in bytes) (512 * 1024 = 524288)
```

2023-11-16 07:57 UTC, rart commented on ui/app/src/components/GlobalConfigManagement/GlobalConfigManagement.tsx
> +      );
With the [new approach](https://github.com/craftersoftware/craftercms/issues/617#issuecomment-1813948305) in mind, perhaps we simply disable the Save button and we don't need this.

2023-11-16 07:57 UTC, rart commented on ui/app/src/components/GlobalConfigManagement/GlobalConfigManagement.tsx
> +    const contentSize = getContentSizeInBytes(value);
Let's just match the backend and check for string length.

2023-11-16 07:57 UTC, rart commented on ui/app/src/utils/content.ts
> +}
Guess we don't need this anymore.

2023-11-21 07:50 UTC, rart commented on ui/app/src/utils/content.ts
> +}
Not resolved.

2023-11-21 07:51 UTC, rart commented on ui/app/src/utils/constants.ts
> +export const MAX_CONFIG_SIZE = 512 * 1024; // Max configuration files allowed (in bytes)
Not resolved.

2023-11-21 23:01 UTC, jvega190 commented on ui/app/src/utils/content.ts
> +}
Committed

2023-11-21 23:01 UTC, jvega190 commented on ui/app/src/utils/constants.ts
> +export const MAX_CONFIG_SIZE = 512 * 1024; // Max configuration files allowed (in bytes)
Just committed

2023-11-21 23:02 UTC, jvega190 commented
@rart tested with the max config size and there is no noticeable performance downgrade

2023-11-22 13:19 UTC, rart approved these changes

2023-11-23 19:08 UTC, merged