[504E] Lock Engine in Preview mode with a token
craftercms/studio-ui pull request #3489
Opened 2023-11-27 18:36 UTC by jvega190

https://github.com/craftersoftware/craftercms/issues/504

2023-11-27 19:05 UTC, rart requested changes

2023-11-27 19:05 UTC, rart commented on ui/app/src/services/security.ts
> +  return post(`/studio/api/2/security/preview/switch`).pipe(map(() => true));
```suggestion
  return post(`/studio/api/2/security/preview/switch`).pipe(mapTo(true));
```

2023-11-27 20:17 UTC, jvega190 commented on ui/app/src/services/security.ts
> +  return post(`/studio/api/2/security/preview/switch`).pipe(map(() => true));
per conversation, we won't update `mapTo`, as its usage is deprecated

2023-12-04 15:52 UTC, rart approved these changes

2023-12-04 19:11 UTC, merged