[4730] Display unmet Site Policy condition on failed uploads
craftercms/studio-ui pull request #3492
Opened 2023-12-04 21:26 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4730

2023-12-04 21:27 UTC, jvega190 commented
Left as draft since there are some pending backend changes that need to be tested

2023-12-15 06:34 UTC, rart requested changes

2023-12-15 06:34 UTC, rart commented on ui/app/src/assets/guestMessages.ts
>    },
This doesn't need a translation definition

2023-12-15 17:15 UTC, rart approved these changes

2023-12-15 18:34 UTC, merged