[682E][4.2.x] children_by_path is slow if called repeatedly
craftercms/studio-ui pull request #3574
Opened 2024-01-03 22:21 UTC by jvega190

https://github.com/craftersoftware/craftercms/issues/682

2024-01-04 13:11 UTC, rart requested changes
These PRs are all active but this is not the whole task. All the navigators logic to use this is not done?

2024-01-04 13:11 UTC, rart commented on ui/app/src/services/content.ts
> +  return fetchChildrenByPaths(siteId, paths).pipe(map((data) => data[path]));
```suggestion
  return fetchChildrenByPaths(siteId, { [path]: options }).pipe(pluck(path));
```

2024-01-04 13:11 UTC, rart commented on ui/app/src/services/content.ts
> +    map(({ items }) => {
```suggestion
    pluck('response', 'items'),
    map((items) => {
```

2024-01-04 13:11 UTC, rart commented on ui/app/src/services/content.ts
> -      })
What about this error handling? Anything to consider here?

2024-01-08 15:24 UTC, jvega190 commented on ui/app/src/services/content.ts
> +  return fetchChildrenByPaths(siteId, paths).pipe(map((data) => data[path]));
pluck is deprecated, should we still use it?

2024-01-08 17:15 UTC, rart requested changes

2024-01-08 17:15 UTC, rart commented on ui/app/src/state/actions/pathNavigator.ts
> +  'PATH_NAVS_BACKGROUND_REFRESH'
```suggestion
  'PATH_NAV_BULK_BG_REFRESH'
```

2024-01-08 17:15 UTC, rart commented on ui/app/src/state/actions/pathNavigatorTree.ts
> +  'PATH_NAV_TREES_BACKGROUND_REFRESH'
```suggestion
  'PATH_NAV_TREE_BULK_BG_REFRESH'
```

2024-01-08 17:15 UTC, rart commented on ui/app/src/state/actions/pathNavigator.ts
> +  'PATH_NAVS_BACKGROUND_REFRESH'
Rename const too (for all)

2024-01-08 17:15 UTC, rart commented on ui/app/src/services/content.ts
> +  return fetchChildrenByPaths(siteId, paths).pipe(map((data) => data[path]));
no

2024-01-08 17:15 UTC, rart commented on ui/app/src/services/content.ts
> +    map((items) => {
If pluck is deprecated, then let's begin removing wherever it is found.

2024-01-09 16:45 UTC, rart requested changes
It seems we can still bulk more on some events. Anywhere where using the `actions.push(...)` pattern. Ping me to review if necessary.

2024-01-10 07:40 UTC, rart requested changes
Some of the revisions the comments apply to many places but I didn't write the same comment everywhere (e.g. don't dispatch if the arrays of ids are empty, don't use single actionComplete handlers to dispatch bulk action results, etc). Check all the work for those and apply everywhere.

2024-01-10 07:40 UTC, rart commented on ui/app/src/state/epics/pathNavigator.ts
> +              );
Create an action that receives the bulk response and is processed accordingly in the reducer. Follow the action, actionComplete, actionFailed pattern.

2024-01-10 07:40 UTC, rart commented on ui/app/src/state/epics/pathNavigator.ts
> +        return of(pathNavigatorBulkBackgroundRefresh({ ids: idsToRefresh }));
If we're returning a single action, you can switch from `mergeMap` to `map` and dismiss the use of `of`.
Do not dispatch if ids is empty

2024-01-10 07:40 UTC, rart commented on ui/app/src/state/epics/pathNavigator.ts
> +        actions.push(pathNavigatorBulkBackgroundRefresh({ ids: idsToBgRefresh }));
```suggestion
        idsToRefresh.length && actions.push(pathNavigatorBulkRefresh({ ids: idsToRefresh }));
        idsToBgRefresh.length && actions.push(pathNavigatorBulkBackgroundRefresh({ ids: idsToBgRefresh }));
```

2024-01-10 07:40 UTC, rart commented on ui/app/src/state/epics/pathNavigator.ts
> +        return of(pathNavigatorBulkBackgroundRefresh({ ids }));
mergeMap => map, no of
do not dispatch if ids is empty.

2024-01-22 08:08 UTC, rart commented on ui/app/src/state/epics/pathNavigator.ts
> +        return ids.length ? pathNavigatorBulkBackgroundRefresh({ ids }) : NEVER;
Can't return an observable (NEVER) from map. This is obviously untested... 👎🏻

2024-01-22 08:38 UTC, rart commented on ui/app/src/state/epics/pathNavigatorTree.ts
> +              }
What's this for? Doesn't seem to have any usage?

2024-01-25 22:01 UTC, jvega190 commented on ui/app/src/state/epics/pathNavigator.ts
> +                      item.path.startsWith(withoutIndex(state.pathNavigator[id].currentPath))
The backend doesn't send back the children in the same order as the items

2024-01-25 22:03 UTC, jvega190 commented on ui/app/src/state/epics/pathNavigatorTree.ts
> +      // TODO: There's no special handling for background vs visible. Should there be?
There doesn't seem to be any previous handling for background vs visible (in comparison with pathNavigator, that is in the reducer). The pathNavTree state doesn't have any `isFetching` or something implemented for the loading state to display. Should we create a ticket for that?

2024-01-29 17:34 UTC, rart requested changes
Apply changes from 4.1.x

2024-01-30 16:25 UTC, rart approved these changes

2024-01-30 16:31 UTC, merged