[6453] Compute bucket xml prop as before, handle xml not having the url prop, add video preview
craftercms/studio-ui pull request #3652
Opened 2024-01-26 22:45 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6453

2024-01-26 22:46 UTC, jvega190 commented on static-assets/themes/cstudioTheme/css/forms-default.css
> +  box-shadow:
@rart I got some formatted lines like with by prettier auto format, is that ok or should I revert?

2024-01-29 17:27 UTC, rart requested changes
Compare with the very latest version on 4.1.x. There's at least one difference.

2024-01-29 17:50 UTC, rart requested changes
Also recheck styles match

2024-01-30 03:27 UTC, rart approved these changes

2024-01-30 14:49 UTC, merged