[812E] Address unflattened content with components which file name is not the GUID
craftercms/studio-ui pull request #3748
Opened 2024-03-07 23:06 UTC by jvega190

https://github.com/craftersoftware/craftercms/issues/812

2024-03-07 23:07 UTC, jvega190 commented
Left as draft, there's still some work pending

2024-03-12 22:07 UTC, rart requested changes

2024-03-12 22:07 UTC, rart commented on ui/app/src/components/LegacyFormDialog/EmbeddedLegacyContainer.tsx
Add changes to changelog. 
Also, bring the 4.1.x branch content in too.

2024-03-12 22:07 UTC, rart commented on ui/app/src/components/PreviewConcierge/PreviewConcierge.tsx
> +          // TODO: Remove *all* document domain related stuff for `develop`
Not done.

2024-03-15 18:34 UTC, rart requested changes

2024-03-15 18:34 UTC, rart commented on ui/app/src/CHANGELOG.md
> +  * Removed `documentDomain` property from ExperienceBuilder component and its usage in `PreviewConcierge` component
Missing renaming of updateEditDialogConfig and removal of document domain

2024-03-22 22:32 UTC, rart approved these changes

2024-03-25 18:09 UTC, merged