[4.1.x][6615] UI not blocking when deploying studio while server is running
craftercms/studio-ui pull request #3753
Opened 2024-03-11 17:45 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6615

2024-03-11 19:15 UTC, rart requested changes

2024-03-11 19:15 UTC, rart commented on ui/app/src/components/GlobalDialogManager/GlobalDialogManager.tsx
> +          })
```suggestion
          .then((r) => {
            if (r.ok) {
              return r.text();
            } else {
              throw new Error('socket-connection-error fetch failed');
            }
          })
```

2024-03-12 05:46 UTC, rart approved these changes

2024-03-13 15:48 UTC, jvega190 commented
Left as draft as this is 4.1.5 work

2024-04-18 13:58 UTC, rart approved these changes
@sumerjabri safe to merge

2024-04-18 14:31 UTC, merged