[6517] Add a single item per line view to search and browse item selection dialogs
craftercms/studio-ui pull request #3758
Opened 2024-03-13 18:52 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6517

2024-03-13 18:53 UTC, jvega190 commented
Some decisions pending

2024-03-14 22:43 UTC, rart requested changes
Make sure to test with data of various lengths (very short/long, normal), etc

2024-03-14 22:43 UTC, rart commented on ui/app/src/utils/state.ts
> +}
Let's clean up.
- Remove getStoredBrowseDialogCompactMode
- Check for the old key in the new storing modes and if present delete and write the new.
  - The setted should delete the old and write the new
  - The getter must check the old and if not present go to the new
  - Add a clean up todo for later versions to fully remove old key
- Adjust the Account preference clean up stuff to include all this stuff too

2024-03-14 22:43 UTC, rart commented on ui/app/src/utils/state.ts
> +  const backwardsCompatibilityValue = getStoredBrowseDialogCompactMode(username) ? 'compact' : 'card';
```suggestion
  const backwardsCompatibilityValue: MediaCardViewModes = getStoredBrowseDialogCompactMode(username) ? 'compact' : 'card';
```

2024-03-19 16:52 UTC, rart requested changes
From previous review:  Account preference clean up stuff to include all this stuff too

2024-03-19 17:04 UTC, jvega190 commented
> From previous review: Account preference clean up stuff to include all this stuff too

yeap, updated removeStoredBrowseDialogCompactMode to removeStoredBrowseDialogViewMode, which is called in the preferences clean up under AccountManagement/utils.tsx

2024-03-28 12:56 UTC, rart approved these changes

2024-03-28 16:31 UTC, merged