[6571] Remove logical resource from WorkflowCancellationDialog, update component for it to show empty state if no items
craftercms/studio-ui pull request #3765
Opened 2024-03-15 17:37 UTC by jvega190

- Remove logical resource from WorkflowCancellationDialog, update component for it to show empty state if no items

https://github.com/craftercms/craftercms/issues/6571

2024-03-15 19:55 UTC, rart reviewed
Add change to changelog

2024-03-15 19:55 UTC, rart commented on ui/app/src/components/WorkflowCancellationDialog/WorkflowCancellationDialogContainer.tsx
> +  const { items = [], onClose, onContinue } = props;
Remove default and if items is nullish, render an empty state with "No items were provided as input"

2024-03-15 19:55 UTC, rart commented on ui/app/src/components/WorkflowCancellationDialog/utils.ts
> +  items: Return;
```suggestion
  items: SandboxItem[];
```

Is this `Return` used elsewhere? Remove if possible.

2024-03-19 14:58 UTC, rart requested changes
Comments from the previous review have not been address...

2024-03-19 17:20 UTC, jvega190 commented on ui/app/src/CHANGELOG.md
> +  * `WorkflowCancellationDialogUI`: prop `items` type changed from an async Resource to sync SandboxItem array.
The format for 4.2.0 changes is a bit different, so I put the component name only, under the components section

2024-03-22 22:11 UTC, rart approved these changes

2024-03-25 18:13 UTC, sumerjabri commented
@jvega190 I'm unable to merge due to a conflict.

2024-03-25 18:33 UTC, merged