[5428] Dashboard API Bugs
craftercms/studio-ui pull request #3768
Opened 2024-03-18 20:57 UTC by jvega190

- Added item comment in RecentlyPublishedDashlet
- Updated PackageDetailsDialog styles and error handling

https://github.com/craftercms/craftercms/issues/5428

2024-03-18 20:57 UTC, jvega190 commented
Left as draft as there may be more details to work on

2024-04-03 19:05 UTC, jvega190 commented
@rart there are some points in the ticket that may need some discussion and maybe some UI updates. Can you please check https://github.com/craftercms/craftercms/issues/5428#issuecomment-2004975219?

2024-05-14 12:29 UTC, rart requested changes

2024-05-14 12:29 UTC, rart commented on ui/app/src/components/RecentlyPublishedDashlet/RecentlyPublishedDashlet.tsx
> +                    {item.comment ?? (
```suggestion
                    {item.comment || (
```

2024-05-14 12:30 UTC, rart approved these changes

2024-05-14 14:19 UTC, merged