[6652] Process path for macros when opening search in components datasource
craftercms/studio-ui pull request #3805
Opened 2024-04-08 21:51 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6652

2024-04-09 08:22 UTC, rart requested changes
There's a lot more to port for this ticket.

2024-04-09 19:45 UTC, rart requested changes

2024-04-09 19:45 UTC, rart commented on ui/app/src/components/PreviewSearchPanel/PreviewSearchPanel.tsx
> +      //   Fix/match typing and usages, both from dispatchers and handlers of this action.
Fix

2024-04-10 08:11 UTC, rart requested changes

2024-04-10 08:11 UTC, rart commented on ui/guest/src/react/ExperienceBuilder.tsx
> +          dispatch(assetDragStarted(payload));
Looks like this can simply be moved to the whitelisted actions.

Also, please confirm you've reviewed the Payload typings match the usages not just at the dispatchers but at the *handlers*

2024-04-10 22:24 UTC, jvega190 commented on ui/guest/src/react/ExperienceBuilder.tsx
> +          dispatch(assetDragStarted(payload));
Yeah, I reviewed all usages of the action, including handlers.
Moving the case to the whitelisted actions.

2024-04-24 16:43 UTC, rart approved these changes

2024-04-24 18:55 UTC, merged