[6702] Validate macros in Content Type form before saving
craftercms/studio-ui pull request #3845
Opened 2024-04-30 20:51 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6707

2024-04-30 20:53 UTC, jvega190 commented
@rart I added the validation in the content-type editor, in the input for destination path pattern. I wonder if this should go in another level, and also how to display the error to the user. I'll ping you to discuss

2024-05-07 13:23 UTC, rart reviewed
Pls call to demo, review and discuss

2024-05-09 18:01 UTC, rart requested changes

2024-05-09 18:01 UTC, rart commented on static-assets/components/cstudio-admin/mods/content-types.js
> +                'success',
This should be an info.

2024-05-09 18:01 UTC, rart commented on ui/app/src/env/i18n-legacy.ts
> +    defaultMessage: 'Path contains invalid macros: {macros}'
```suggestion
    defaultMessage: 'The following invalid macros were removed: {macros}'
```

2024-05-14 12:58 UTC, rart approved these changes

2024-05-14 14:18 UTC, merged