[4.1.x][854] Update dependencies
craftercms/studio-ui pull request #3873
Opened 2024-05-13 15:47 UTC by jvega190

https://github.com/craftersoftware/craftercms/issues/854

2024-05-13 15:50 UTC, jvega190 commented
Please note that @typescript-eslint/parser and @typescript-eslint/eslint-plugin (from ticket) are not in this branch

2024-05-14 11:29 UTC, rart requested changes

2024-05-14 11:29 UTC, rart commented on yarn.lock
> +  linkType: hard
There's 4 versions of this package! Let's try to cut down. We don't actually use `@videojs/vhs-utils` directly, yet at least in develop it is listed as a direct dependency. Please check it out. See if removing and deduping helps.

2024-05-16 17:11 UTC, rart approved these changes

2024-05-16 17:50 UTC, merged