[6789] Dependency management 5/24
craftercms/studio-ui pull request #3879
Opened 2024-05-14 18:25 UTC by jvega190

- Downgrade @prettier/plugin-xml to v3.3.0

https://github.com/craftercms/craftercms/issues/6789

2024-05-14 18:32 UTC, jvega190 commented
This downgrade is due to an issue introduced in `@prettier/plugin-xml` in v3.3.1. It adds extra spaces causing the content to break

2024-05-14 18:49 UTC, rart requested changes
Use @3.3.0, no `^`. No manual edits to `yarn.lock`.

2024-05-15 06:03 UTC, rart approved these changes

2024-05-15 12:40 UTC, merged

2025-03-13 10:59 UTC, rart commented
https://github.com/prettier/plugin-xml/issues/784