[4.1.x][6954] XB does not show up added repeating group item and need a browser refresh
craftercms/studio-ui pull request #3996
Opened 2024-06-14 19:02 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6954

2024-06-18 14:25 UTC, rart requested changes

2024-06-18 14:25 UTC, rart commented on ui/guest/src/contentController.ts
> +  const newItems = index ? currentItems.splice(index, 0, instance) : [...(currentItems ?? []), instance];
Don't modify/mutate the existing array instance.

2024-06-19 06:40 UTC, rart requested changes

2024-06-19 06:40 UTC, rart commented on ui/guest/src/contentController.ts
> +  const currentItems = (models[modelId][fieldId] ?? []).slice();
```suggestion
  const currentItems = [...(models[modelId][fieldId] ?? [])];
```

2024-06-19 06:44 UTC, rart requested changes

2024-06-19 06:44 UTC, rart commented on ui/guest/src/contentController.ts
> +  });
Create a nested fields/indexes example (e.g. repeat_o.itemSelector_o, 0.1) and see if this works. My guess if we need to accommodate the dotted notation by using the utility functions we have.

2024-06-20 23:30 UTC, jvega190 commented on ui/guest/src/utils/ice.ts
> +export function getCollection(model: ContentInstance, fieldId: string, index: string | number) {
@rart will ping you to ask a couple of things about this

2024-06-25 15:46 UTC, rart requested changes

2024-06-25 15:46 UTC, rart commented on ui/guest/src/contentController.ts
> +  const field = fields.reduce((acc, field) => acc[field].fields, contentType.fields);
```suggestion
  const fieldPathArray = fieldId.split('.');
  const repeatFields = fields.reduce((acc, field) => acc[field].fields, contentType.fields);
```

2024-06-25 15:46 UTC, rart commented on ui/guest/src/contentController.ts
> +    : fieldId;
```suggestion
  const fieldPathWithIndexes = isSimple(fieldId)
    ? fieldId
    : mergeArraysAlternatively(fieldId.split('.'), indexPieces).join('.');
```

2024-06-25 15:46 UTC, rart commented on ui/guest/src/contentController.ts
> +  const currentItems = getCollection(models[modelId], concatFieldId, index) ?? [];
Strange to send the field with indexes and an index also. Pls check

2024-06-25 15:46 UTC, rart commented on ui/guest/src/contentController.ts
> +  const model = setCollection(models[modelId], fieldId, index, newItems);
Do not mutate the existing instance inside of models.

2024-06-25 15:47 UTC, rart commented on ui/guest/src/contentController.ts
> +  const model = setCollection(models[modelId], fieldId, index, newItems);
The additional complexity here is that shouldn't mutate the inner object target of the collection being set

2024-06-27 13:58 UTC, rart approved these changes

2024-06-27 17:26 UTC, merged