[6983] Improve XB ease-of-use and resilience for JS apps programmatically registering elements for XB
craftercms/studio-ui pull request #4018
Opened 2024-06-27 22:24 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6983

2024-06-28 10:20 UTC, rart requested changes
Is this finished? I don't see for example the recordIdByElementLookup being cleaned when deregister is called?

Also not sure I'm seeing work to make sure deregister would would even when the deferred request hasn't completed.

2024-06-28 17:46 UTC, jvega190 commented on ui/guest/src/store/subjects.ts
> +export const guestCheckIn$ = new ReplaySubject<boolean>(1);
There's one detail here (in the usage). We still need to listen for the `xb:loaded` so were sure we have `craftercms.xb`, then subscribe to `guestCheckIn$`

2024-07-04 14:49 UTC, rart requested changes
Let's add/move the `registerElements` and `deregisterElements` functions to the library (to the index)

2024-07-04 14:49 UTC, rart commented on ui/guest/src/elementRegistry.ts
> +        deferredRegistrationSubscription = model$(response.craftercms.id)
There are many calls to register done sequentially. A single subscription doesn't work. You need maybe a stream of deregistered ids to stop this one.

2024-07-04 14:49 UTC, rart commented on ui/guest/src/elementRegistry.ts
> +let deferredRegistrationSubscription;
What's the need for 2 subjects?

2024-07-04 21:37 UTC, jvega190 commented on ui/guest/src/elementRegistry.ts
> +let deferredRegistrationSubscription;
There are two places where we have subscriptions, in the main register funcion (if main model is not fetched) and in the `completeRegistration` function (if is an inherited field, to load the model). What I did was to add a lookup for registrations (with the id as the key), and the content is an array of the subscriptions, considering that there may be up to 2 subscriptions. Then, when deregistering, delete all of the subscriptions for the id

2024-07-05 15:49 UTC, rart requested changes

2024-07-05 15:49 UTC, rart commented on ui/guest/src/index.tsx
> +    articleElements.forEach((element) => {
These aren't articles here...
```suggestion
    const elements = container.querySelectorAll('[data-craftercms-model-id]');
    elements.forEach((element) => {
```

2024-07-05 15:49 UTC, rart commented on ui/guest/src/elementRegistry.ts
> +let registrationSubscriptions = {};
Pls apply discussed changes

2024-07-08 11:06 UTC, rart requested changes
Pls remember to port changes to 4.1 PR too

2024-07-08 11:06 UTC, rart commented on ui/guest/src/elementRegistry.ts
> +const deregister$ = new Subject<number | string>();
```suggestion
const deregister$ = new Subject<string>();
```

2024-07-08 11:06 UTC, rart commented on ui/guest/src/elementRegistry.ts
> +  const terminator$ = deregister$.pipe(filter((_id) => _id === id));
```suggestion
  const terminator$ = deregister$.pipe(filter((_id) => _id === String(id)));
```

2024-07-09 17:04 UTC, rart approved these changes

2024-07-12 13:38 UTC, merged