[4.1.x][6983] Improve XB ease-of-use and resilience for JS apps programmatically registering elements for XB
craftercms/studio-ui pull request #4020
Opened 2024-06-28 17:46 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6983

2024-07-05 15:49 UTC, rart requested changes
Discussed changes pending.

2024-07-08 11:07 UTC, rart requested changes
See changes on develop PR

2024-07-08 18:38 UTC, jvega190 commented
Updated up to https://github.com/craftercms/studio-ui/pull/4018#discussion_r1668420251

2024-07-09 17:04 UTC, rart approved these changes

2024-07-12 13:39 UTC, merged