[7018] Fix max condition validation
craftercms/studio-ui pull request #4086
Opened 2024-08-05 16:02 UTC by jvega190

https://github.com/craftercms/craftercms/issues/7018

2024-08-05 16:03 UTC, jvega190 commented on static-assets/components/cstudio-forms/controls/node-selector.js
> +                    id: 'nodeSelector.maxItemsReached',
@rart without id it breaks with the following error:
`Error: [@formatjs/intl] An `id` must be provided to format a message.`

2024-08-06 13:41 UTC, rart requested changes

2024-08-06 13:41 UTC, rart commented on static-assets/components/cstudio-forms/controls/node-selector.js
> +                    id: 'nodeSelector.maxItemsReached',
Needs to go to i18n-legacy for extraction (and auto-id) to work

2024-08-07 09:24 UTC, rart approved these changes

2024-08-07 14:27 UTC, merged