[4768] History comparison is confusing
craftercms/studio-ui pull request #4131
Opened 2024-08-28 22:25 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4768

2024-08-29 22:03 UTC, jvega190 commented
This is ready for review, leaving it as draft since it is 4.3

2024-09-04 07:49 UTC, rart requested changes

2024-09-04 07:49 UTC, rart commented on ui/app/src/components/ViewVersionDialog/ViewVersionDialog.tsx
> +import { Slide } from '@mui/material';
```suggestion
import Slide from '@mui/material/Slide';
```

2024-09-04 07:49 UTC, rart commented on ui/app/src/components/VersionList/VersionList.tsx
> +                <Checkbox checked={selected?.includes(version.versionNumber)} />
Create a local non-memoized presence table to avoid the constant array iteration

2024-09-04 07:49 UTC, rart commented on ui/app/src/components/CompareVersionsDialog/CompareVersionsDialogContainer.tsx
> -} from '../../state/actions/versions';
Check if we need to clean up (remove) some actions/action creators.

2024-09-04 07:49 UTC, rart commented on ui/app/src/components/CompareVersionsDialog/CompareVersionsDialogContainer.tsx
> -      // recent version and add it first in the list of versions to compare.
This comment seems worth keeping somewhere. Perhaps on the History dialog, if not already there.

2024-09-04 07:49 UTC, rart commented on ui/app/src/components/ContextMenu/ContextMenu.tsx
> +            return (
Unnecessary change

2024-09-04 07:49 UTC, rart commented on ui/app/src/components/CompareVersionsDialog/CompareVersionsDialog.tsx
> +      maxWidth={'xl'}
```suggestion
      maxWidth="xl"
```

2024-09-05 20:58 UTC, jvega190 commented on ui/app/src/components/CompareVersionsDialog/CompareVersionsDialogContainer.tsx
> -      // recent version and add it first in the list of versions to compare.
I was wrong before. This behavior (the one in the comment) was no longer happening. Updated the HistoryDialog to behave just like this did.

2024-09-06 15:21 UTC, rart approved these changes

2024-09-06 15:47 UTC, merged