[6694] MUIv6 Upgrade
craftercms/studio-ui pull request #4190
Opened 2024-10-16 23:00 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6694

2024-10-29 18:36 UTC, jvega190 commented
Left as draft since it is for 4.3

2024-11-14 08:17 UTC, rart requested changes
Needs changelog entries

2024-11-14 17:07 UTC, jvega190 commented
@rart updates are transparent for component's usages, I added an entry to the CHANGELOG mentioning the update to latest version (to date)

2024-11-14 17:20 UTC, rart approved these changes

2024-11-14 17:21 UTC, merged