[7420] Publishing Queue's Select all on this page not clearing Cancel Selected option button after deselect
craftercms/studio-ui pull request #4200
Opened 2024-10-22 21:37 UTC by jvega190

https://github.com/craftercms/craftercms/issues/7420

2024-10-22 21:39 UTC, jvega190 commented
Left as draft since it is for 4.3

2024-11-18 10:40 UTC, rart requested changes

2024-11-18 10:40 UTC, rart commented on ui/app/src/components/ConfirmDropdown/ConfirmDropdown.tsx
> +          {...buttonProps}
```tsx
<Button
          variant={buttonVariant}
          {...buttonProps}
          className={clsx(props.classes?.button, buttonProps?.classes)}
          sx={[sx.button, buttonProps?.sx]}
          onClick={(e) => setAnchorEl(e.currentTarget)}
          disabled={disabled}
          endIcon={<ArrowDown />}
```

2024-11-19 12:51 UTC, rart approved these changes

2024-11-19 16:35 UTC, merged