[7445] Eliminate Edit button when viewing past commit files from Item History
craftercms/studio-ui pull request #4236
Opened 2024-11-06 21:57 UTC by jvega190

https://github.com/craftercms/craftercms/issues/7445

2024-11-18 08:03 UTC, rart requested changes
Check if there's anything for this ticket that should be carried to the new Diff UX branch

2024-11-18 08:03 UTC, rart commented on ui/app/src/components/HistoryDialog/HistoryDialogContainer.tsx
> +  // endregion
There's something wrong with the `fetchItemVersions` and possibly with `versionsChangeItem` too. The epic checks properties that don't match the payload definition. Then, the reducer types the payload as something different.

Also, the action should be light on what it requires. If it just needs the path, don't expect the whole item. If the rootPath, etc is not needed, shouldn't be there. The `HistoryConfigProps` interface seems underused.

Check that family of actions, epics and reducers. If this becomes big, we might have to open a new ticket to fix.


```suggestion
  // region Item Updates Propagation
  const itemPath = item?.path;
  useEffect(() => {
    const events = [contentEvent.type];
    const hostToHost$ = getHostToHostBus();
    const subscription = hostToHost$
      .pipe(filter((e) => events.includes(e.type) && e.payload.targetPath === itemPath))
      .subscribe(() => {
        dispatch(
          fetchItemVersions({
            // add what's needed after fixing types
          })
        );
      });
    return () => {
      subscription.unsubscribe();
    };
  }, [dispatch, itemPath]);
  // endregion
```

2024-11-18 08:03 UTC, rart commented on ui/app/src/components/PreviewDialog/utils.ts
> +  hideEdit?: boolean;
Default to true on the component.
```suggestion
  showEdit?: boolean;
```

2024-11-18 22:56 UTC, jvega190 commented on ui/app/src/components/HistoryDialog/HistoryDialogContainer.tsx
> +  // endregion
I'd prefer to make those updates on the diff dialog updates branch, or after merging it since there can be multiple conflicts. What do you think?

2024-11-19 08:12 UTC, rart approved these changes

2024-11-19 08:12 UTC, rart commented on ui/app/src/components/HistoryDialog/HistoryDialogContainer.tsx
> +  // endregion
ok

2024-11-19 12:24 UTC, merged