[4.1.x][7397] Hour selection in Audience Targeting is off by one after Oct 27 in GMT+x timezones
craftercms/studio-ui pull request #4257
Opened 2024-11-15 21:56 UTC by jvega190

https://github.com/craftercms/craftercms/issues/7397

2024-11-15 21:57 UTC, jvega190 commented
@rart left as draft to dicsuss some differences in the MUI version used in 4.1.x

2024-11-19 12:49 UTC, rart requested changes

2024-11-19 12:49 UTC, rart commented on ui/app/src/components/DateTimeTimezonePicker/DateTimeTimezonePicker.tsx
> +        setControlTimezone(selectedTimezone);
I don't see the comment being done and this shows a big lack of testing...
Pick a date, then go a select a timezone with a different offset to your local timezone and see the date picker field value...

2024-11-19 15:01 UTC, jvega190 commented on ui/app/src/components/DateTimeTimezonePicker/DateTimeTimezonePicker.tsx
> +        setControlTimezone(selectedTimezone);
I did test the scenario, changing the timezone to a different offset doesn't update the date/time in the picker

https://www.loom.com/share/8dea4af44a9e4325bb35fafa7b3ee0c0

2024-11-19 17:07 UTC, rart approved these changes

2024-11-19 18:06 UTC, merged