[studio-ui] Upgrade TinyMCE to the latest #793
craftercms/studio-ui pull request #976
Opened 2018-11-05 21:05 UTC by jvega190

[studio-ui] Upgrade TinyMCE to the latest #793
[studio-ui] extend TinyMCE image/video plugin with upload/browse options #2601

2018-11-08 19:10 UTC, sumerjabri requested changes
Please replace all descriptive strings as follows:
RTE = RTE (TinyMCE 2)
RTE 2 = RTE (TinyMCE 4)
Rich Text Editor = Rich Text Editor (TinyMCE 2)
Rich Text Editor 2 = Rich Text Editor (TinyMCE 4)

Also change the code variables from `tinymce2` to `tinymce4`.

2018-11-08 19:10 UTC, sumerjabri commented
@jvega190 also ping Russ for more details about naming as needed.

2018-11-14 15:03 UTC, jvega190 commented
- Changed labels of controls to `Rich Text Editor (TinyMCE X)`
- rte2 names changed to RTE (TinyMCE4) 
- rte names (old rte) not changed since it can break sites out there 
- `tinymce2` code variables do belong to tinymce v2, not v4.

Please let me know if you need more details about changes

2018-11-15 21:53 UTC, sumerjabri approved these changes

2018-11-15 21:53 UTC, merged